# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui_asistente_inventario.ui'
#
# Created: Sun May 20 19:16:08 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Asistente(object):
    def setupUi(self, Asistente):
        Asistente.setObjectName(_fromUtf8("Asistente"))
        Asistente.resize(778, 586)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pyventa/images/png/notas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Asistente.setWindowIcon(icon)
        Asistente.setStyleSheet(_fromUtf8("QToolButton{border:0; background:transparent}\n"
"QStackedWidget{padding:10px;background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(173, 173, 173, 255), stop:0.990338 rgba(100, 100, 100, 255));}"))
        self.verticalLayout = QtGui.QVBoxLayout(Asistente)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stack = QtGui.QStackedWidget(Asistente)
        self.stack.setStyleSheet(_fromUtf8(""))
        self.stack.setObjectName(_fromUtf8("stack"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupBox_4 = QtGui.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_10 = QtGui.QFrame(self.groupBox_4)
        self.frame_10.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 58), stop:0.294686 rgba(57, 57, 57, 0));\n"
"border-radius:5;\n"
""))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.frame_10)
        self.verticalLayout_14.setMargin(4)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.tablaDeps = QtGui.QTableWidget(self.frame_10)
        self.tablaDeps.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tablaDeps.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablaDeps.setAlternatingRowColors(True)
        self.tablaDeps.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.tablaDeps.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaDeps.setObjectName(_fromUtf8("tablaDeps"))
        self.tablaDeps.setColumnCount(0)
        self.tablaDeps.setRowCount(0)
        self.tablaDeps.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_14.addWidget(self.tablaDeps)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pyventa/images/png/64-box_open.png")))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.stack.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_4 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.page_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lsColumnas = QtGui.QListWidget(self.groupBox)
        self.lsColumnas.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lsColumnas.setMovement(QtGui.QListView.Free)
        self.lsColumnas.setObjectName(_fromUtf8("lsColumnas"))
        item = QtGui.QListWidgetItem(self.lsColumnas)
        item.setCheckState(QtCore.Qt.Checked)
        item = QtGui.QListWidgetItem(self.lsColumnas)
        item.setCheckState(QtCore.Qt.Checked)
        item = QtGui.QListWidgetItem(self.lsColumnas)
        item.setCheckState(QtCore.Qt.PartiallyChecked)
        item = QtGui.QListWidgetItem(self.lsColumnas)
        item.setCheckState(QtCore.Qt.Checked)
        item = QtGui.QListWidgetItem(self.lsColumnas)
        item.setCheckState(QtCore.Qt.PartiallyChecked)
        self.verticalLayout_3.addWidget(self.lsColumnas)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.page_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.rbFam = QtGui.QRadioButton(self.groupBox_2)
        self.rbFam.setStyleSheet(_fromUtf8("color:#333"))
        self.rbFam.setChecked(True)
        self.rbFam.setObjectName(_fromUtf8("rbFam"))
        self.verticalLayout_4.addWidget(self.rbFam)
        self.rbDeps = QtGui.QRadioButton(self.groupBox_2)
        self.rbDeps.setStyleSheet(_fromUtf8("color:#333"))
        self.rbDeps.setObjectName(_fromUtf8("rbDeps"))
        self.verticalLayout_4.addWidget(self.rbDeps)
        self.rbRef = QtGui.QRadioButton(self.groupBox_2)
        self.rbRef.setStyleSheet(_fromUtf8("color:#333"))
        self.rbRef.setObjectName(_fromUtf8("rbRef"))
        self.verticalLayout_4.addWidget(self.rbRef)
        self.rbDesc = QtGui.QRadioButton(self.groupBox_2)
        self.rbDesc.setStyleSheet(_fromUtf8("color:#333"))
        self.rbDesc.setObjectName(_fromUtf8("rbDesc"))
        self.verticalLayout_4.addWidget(self.rbDesc)
        self.rbPrecio = QtGui.QRadioButton(self.groupBox_2)
        self.rbPrecio.setStyleSheet(_fromUtf8("color:#333"))
        self.rbPrecio.setObjectName(_fromUtf8("rbPrecio"))
        self.verticalLayout_4.addWidget(self.rbPrecio)
        self.rbModif = QtGui.QRadioButton(self.groupBox_2)
        self.rbModif.setStyleSheet(_fromUtf8("color:#333"))
        self.rbModif.setObjectName(_fromUtf8("rbModif"))
        self.verticalLayout_4.addWidget(self.rbModif)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.stack.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_6 = QtGui.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_8.addWidget(self.label_6)
        self.frame_4 = QtGui.QFrame(self.page_3)
        self.frame_4.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 58), stop:0.294686 rgba(57, 57, 57, 0));\n"
"border-radius:5;\n"
""))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setMargin(4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame_7 = QtGui.QFrame(self.frame_4)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 19))
        self.frame_7.setStyleSheet(_fromUtf8("QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(234, 234, 234, 255), stop:1 rgba(179, 179, 179, 255));color:#555;}\n"
"QToolButton{background:none; border:0;}"))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.tbImprimir = QtGui.QToolButton(self.frame_7)
        self.tbImprimir.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pyventa/images/32/Printer-blue-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbImprimir.setIcon(icon1)
        self.tbImprimir.setIconSize(QtCore.QSize(16, 16))
        self.tbImprimir.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbImprimir.setObjectName(_fromUtf8("tbImprimir"))
        self.horizontalLayout_8.addWidget(self.tbImprimir)
        self.toolButton_3 = QtGui.QToolButton(self.frame_7)
        self.toolButton_3.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pyventa/images/32/tablaexcel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setIconSize(QtCore.QSize(16, 16))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.horizontalLayout_8.addWidget(self.toolButton_3)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.tablaProductos = QtGui.QTableWidget(self.frame_4)
        self.tablaProductos.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tablaProductos.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablaProductos.setAlternatingRowColors(True)
        self.tablaProductos.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaProductos.setObjectName(_fromUtf8("tablaProductos"))
        self.tablaProductos.setColumnCount(0)
        self.tablaProductos.setRowCount(0)
        self.tablaProductos.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.tablaProductos)
        self.verticalLayout_8.addWidget(self.frame_4)
        self.stack.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_7 = QtGui.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_13.addWidget(self.label_7)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.groupBox_5 = QtGui.QGroupBox(self.page_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet(_fromUtf8("QGroupBox{ background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(234, 234, 234, 255), stop:1 rgba(179, 179, 179, 255));border:1.5px solid rgb(37, 83, 144); border-radius:5px;color:#555}\n"
""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_10.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.frame_6 = QtGui.QFrame(self.groupBox_5)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_6.setStyleSheet(_fromUtf8("border:1.3px solid #999; border-radius:5px; color:#555;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(41, 41, 41, 255), stop:0.05 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(0, 2, 0, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.leFiltro = QtGui.QLineEdit(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.leFiltro.setFont(font)
        self.leFiltro.setStyleSheet(_fromUtf8("border:0;background:white"))
        self.leFiltro.setObjectName(_fromUtf8("leFiltro"))
        self.horizontalLayout_6.addWidget(self.leFiltro)
        self.toolButton_7 = QtGui.QToolButton(self.frame_6)
        self.toolButton_7.setStyleSheet(_fromUtf8("border:0;background:none"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pyventa/images/32/search-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon3)
        self.toolButton_7.setObjectName(_fromUtf8("toolButton_7"))
        self.horizontalLayout_6.addWidget(self.toolButton_7)
        self.verticalLayout_10.addWidget(self.frame_6)
        self.tabla = QtGui.QTableView(self.groupBox_5)
        self.tabla.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabla.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabla.setSortingEnabled(True)
        self.tabla.setObjectName(_fromUtf8("tabla"))
        self.tabla.horizontalHeader().setCascadingSectionResizes(True)
        self.tabla.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_10.addWidget(self.tabla)
        self.horizontalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.page_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet(_fromUtf8("QGroupBox{ background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(234, 234, 234, 255), stop:1 rgba(179, 179, 179, 255));border:1.5px solid rgb(255, 153, 37); border-radius:5px;color:#555}\n"
""))
        self.groupBox_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.frame_5 = QtGui.QFrame(self.groupBox_6)
        self.frame_5.setStyleSheet(_fromUtf8("border:0;"))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tbAntProd = QtGui.QToolButton(self.frame_5)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pyventa/images/48/go-previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbAntProd.setIcon(icon4)
        self.tbAntProd.setIconSize(QtCore.QSize(100, 32))
        self.tbAntProd.setObjectName(_fromUtf8("tbAntProd"))
        self.horizontalLayout_5.addWidget(self.tbAntProd)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.tbSigProd = QtGui.QToolButton(self.frame_5)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pyventa/images/48/go-next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSigProd.setIcon(icon5)
        self.tbSigProd.setIconSize(QtCore.QSize(100, 32))
        self.tbSigProd.setObjectName(_fromUtf8("tbSigProd"))
        self.horizontalLayout_5.addWidget(self.tbSigProd)
        self.verticalLayout_9.addWidget(self.frame_5)
        self.lblProducto = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.lblProducto.setFont(font)
        self.lblProducto.setObjectName(_fromUtf8("lblProducto"))
        self.verticalLayout_9.addWidget(self.lblProducto)
        self.lbCProducto = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbCProducto.setFont(font)
        self.lbCProducto.setText(_fromUtf8(""))
        self.lbCProducto.setWordWrap(True)
        self.lbCProducto.setObjectName(_fromUtf8("lbCProducto"))
        self.verticalLayout_9.addWidget(self.lbCProducto)
        self.lbCPrecio = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbCPrecio.setFont(font)
        self.lbCPrecio.setObjectName(_fromUtf8("lbCPrecio"))
        self.verticalLayout_9.addWidget(self.lbCPrecio)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.tbManual = QtGui.QCheckBox(self.groupBox_6)
        self.tbManual.setObjectName(_fromUtf8("tbManual"))
        self.verticalLayout_9.addWidget(self.tbManual)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.leExistencias = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExistencias.sizePolicy().hasHeightForWidth())
        self.leExistencias.setSizePolicy(sizePolicy)
        self.leExistencias.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setWeight(75)
        font.setBold(True)
        self.leExistencias.setFont(font)
        self.leExistencias.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leExistencias.setObjectName(_fromUtf8("leExistencias"))
        self.horizontalLayout_10.addWidget(self.leExistencias)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.tbSetStock = QtGui.QToolButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.tbSetStock.setFont(font)
        self.tbSetStock.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(137, 137, 137, 255), stop:0.0545455 rgba(156, 156, 156, 255), stop:1 rgba(191, 191, 191, 255));border:1.3px solid #999; border-radius:12px; color:#555;"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pyventa/images/32/Check-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSetStock.setIcon(icon6)
        self.tbSetStock.setIconSize(QtCore.QSize(16, 24))
        self.tbSetStock.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbSetStock.setObjectName(_fromUtf8("tbSetStock"))
        self.horizontalLayout_11.addWidget(self.tbSetStock)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_7.addWidget(self.groupBox_6)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.stack.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.frame_12 = QtGui.QFrame(self.page_5)
        self.frame_12.setStyleSheet(_fromUtf8("QWidget{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(180, 180, 180, 255), stop:0.02 rgba(158, 158, 158, 255), stop:1 rgba(124, 124, 124, 255));color:#fff;border:0;}\n"
"QToolButton{ border:0px; background:none}"))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.frame_12)
        self.horizontalLayout_13.setContentsMargins(2, 9, 2, 5)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.toolButton_10 = QtGui.QToolButton(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.toolButton_10.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pyventa/images/32/application-pdf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_10.setIcon(icon7)
        self.toolButton_10.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_10.setObjectName(_fromUtf8("toolButton_10"))
        self.horizontalLayout_13.addWidget(self.toolButton_10)
        self.tbIncon = QtGui.QToolButton(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.tbIncon.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pyventa/images/32/blog_accept.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbIncon.setIcon(icon8)
        self.tbIncon.setIconSize(QtCore.QSize(24, 24))
        self.tbIncon.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbIncon.setAutoRaise(True)
        self.tbIncon.setObjectName(_fromUtf8("tbIncon"))
        self.horizontalLayout_13.addWidget(self.tbIncon)
        self.tbImprimir_2 = QtGui.QToolButton(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.tbImprimir_2.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../usr/share/pyventa/images/32/print-down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbImprimir_2.setIcon(icon9)
        self.tbImprimir_2.setIconSize(QtCore.QSize(32, 32))
        self.tbImprimir_2.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.tbImprimir_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbImprimir_2.setAutoRaise(True)
        self.tbImprimir_2.setObjectName(_fromUtf8("tbImprimir_2"))
        self.horizontalLayout_13.addWidget(self.tbImprimir_2)
        self.verticalLayout_12.addWidget(self.frame_12)
        self.frame_8 = QtGui.QFrame(self.page_5)
        self.frame_8.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 58), stop:0.294686 rgba(57, 57, 57, 0));\n"
"border-radius:5;\n"
""))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setMargin(4)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.qteResumen = QtGui.QTextEdit(self.frame_8)
        self.qteResumen.setStyleSheet(_fromUtf8("background:#FFF;"))
        self.qteResumen.setReadOnly(True)
        self.qteResumen.setObjectName(_fromUtf8("qteResumen"))
        self.verticalLayout_11.addWidget(self.qteResumen)
        self.verticalLayout_12.addWidget(self.frame_8)
        self.stack.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.page_6)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.frame_11 = QtGui.QFrame(self.page_6)
        self.frame_11.setStyleSheet(_fromUtf8("QWidget{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(180, 180, 180, 255), stop:0.02 rgba(158, 158, 158, 255), stop:1 rgba(124, 124, 124, 255));color:#fff;border:0;}\n"
"QToolButton{ border:0px; background:none}"))
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.frame_11)
        self.horizontalLayout_12.setContentsMargins(2, 5, 2, 5)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.bCorteP = QtGui.QToolButton(self.frame_11)
        self.bCorteP.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bCorteP.sizePolicy().hasHeightForWidth())
        self.bCorteP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.bCorteP.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../usr/share/pyventa/images/32/vcards-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bCorteP.setIcon(icon10)
        self.bCorteP.setIconSize(QtCore.QSize(24, 24))
        self.bCorteP.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bCorteP.setObjectName(_fromUtf8("bCorteP"))
        self.horizontalLayout_12.addWidget(self.bCorteP)
        self.tbPrintInc = QtGui.QToolButton(self.frame_11)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.tbPrintInc.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../usr/share/pyventa/images/32/printer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPrintInc.setIcon(icon11)
        self.tbPrintInc.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbPrintInc.setObjectName(_fromUtf8("tbPrintInc"))
        self.horizontalLayout_12.addWidget(self.tbPrintInc)
        self.verticalLayout_16.addWidget(self.frame_11)
        self.tvInconsistencias = QtGui.QTableView(self.page_6)
        self.tvInconsistencias.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tvInconsistencias.setAlternatingRowColors(True)
        self.tvInconsistencias.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvInconsistencias.setSortingEnabled(True)
        self.tvInconsistencias.setObjectName(_fromUtf8("tvInconsistencias"))
        self.verticalLayout_16.addWidget(self.tvInconsistencias)
        self.stack.addWidget(self.page_6)
        self.verticalLayout.addWidget(self.stack)
        self.frame = QtGui.QFrame(Asistente)
        self.frame.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(234, 234, 234, 255), stop:1 rgba(179, 179, 179, 255));"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tbCancelar = QtGui.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.tbCancelar.setFont(font)
        self.tbCancelar.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(137, 137, 137, 255), stop:0.0545455 rgba(156, 156, 156, 255), stop:1 rgba(191, 191, 191, 255));border:1.3px solid #999; border-radius:12px; color:#555;"))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pyventa/images/32/Delete-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbCancelar.setIcon(icon12)
        self.tbCancelar.setIconSize(QtCore.QSize(16, 24))
        self.tbCancelar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbCancelar.setObjectName(_fromUtf8("tbCancelar"))
        self.horizontalLayout.addWidget(self.tbCancelar)
        self.lbStatus = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Sans"))
        self.lbStatus.setFont(font)
        self.lbStatus.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.lbStatus.setObjectName(_fromUtf8("lbStatus"))
        self.horizontalLayout.addWidget(self.lbStatus)
        spacerItem6 = QtGui.QSpacerItem(341, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.tbAtras = QtGui.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.tbAtras.setFont(font)
        self.tbAtras.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(137, 137, 137, 255), stop:0.0545455 rgba(156, 156, 156, 255), stop:1 rgba(191, 191, 191, 255));border:1.3px solid #999; border-radius:12px; color:#555;"))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pyventa/images/32/left-green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbAtras.setIcon(icon13)
        self.tbAtras.setIconSize(QtCore.QSize(16, 24))
        self.tbAtras.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbAtras.setObjectName(_fromUtf8("tbAtras"))
        self.horizontalLayout.addWidget(self.tbAtras)
        self.tbAdelante = QtGui.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.tbAdelante.setFont(font)
        self.tbAdelante.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(137, 137, 137, 255), stop:0.0545455 rgba(156, 156, 156, 255), stop:1 rgba(191, 191, 191, 255));border:1.3px solid #999; border-radius:12px; color:#555;"))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../usr/share/pyventa/images/32/right-green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbAdelante.setIcon(icon14)
        self.tbAdelante.setIconSize(QtCore.QSize(16, 24))
        self.tbAdelante.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbAdelante.setObjectName(_fromUtf8("tbAdelante"))
        self.horizontalLayout.addWidget(self.tbAdelante)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Asistente)
        self.stack.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Asistente)

    def retranslateUi(self, Asistente):
        Asistente.setWindowTitle(QtGui.QApplication.translate("Asistente", "Asistente de inventarios", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Asistente", "Seleccione los departamentos que participaran en el inventario.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Asistente", "Consideraciones previas.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Asistente", "Una vez seleccionados los departamentos se levantara un candado para evitar cualquier conflicto con las cantidades. Este bloqueo quedara liberado una vez que se de por terminado el inventario y se haya confirmado por el auditor y el responsable o cuando se cancele el inventario antes del comenzar el conteo. ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Asistente", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:600;\">Formato de la lista de articulos que estaran participando en el inventario.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Personalice la vista y el orden en que se mostraran los productos ya que este orden se mantendra para el conteo asistido y la cantidad de columnas que apareceran en la impresion del listado de productos, es recomendable que escoga aquellas columnas que sean realmente necesarias.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Asistente", "Columnas.", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.lsColumnas.isSortingEnabled()
        self.lsColumnas.setSortingEnabled(False)
        self.lsColumnas.item(0).setText(QtGui.QApplication.translate("Asistente", "Referencia", None, QtGui.QApplication.UnicodeUTF8))
        self.lsColumnas.item(1).setText(QtGui.QApplication.translate("Asistente", "Descripcion", None, QtGui.QApplication.UnicodeUTF8))
        self.lsColumnas.item(2).setText(QtGui.QApplication.translate("Asistente", "Costo", None, QtGui.QApplication.UnicodeUTF8))
        self.lsColumnas.item(3).setText(QtGui.QApplication.translate("Asistente", "Precio", None, QtGui.QApplication.UnicodeUTF8))
        self.lsColumnas.item(4).setText(QtGui.QApplication.translate("Asistente", "Stock logico", None, QtGui.QApplication.UnicodeUTF8))
        self.lsColumnas.setSortingEnabled(__sortingEnabled)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Asistente", "Ordenar  articulos", None, QtGui.QApplication.UnicodeUTF8))
        self.rbFam.setText(QtGui.QApplication.translate("Asistente", "Por familias", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDeps.setText(QtGui.QApplication.translate("Asistente", "Por departamento", None, QtGui.QApplication.UnicodeUTF8))
        self.rbRef.setText(QtGui.QApplication.translate("Asistente", "Por referencia", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDesc.setText(QtGui.QApplication.translate("Asistente", "Por descripcion", None, QtGui.QApplication.UnicodeUTF8))
        self.rbPrecio.setText(QtGui.QApplication.translate("Asistente", "Por precio", None, QtGui.QApplication.UnicodeUTF8))
        self.rbModif.setText(QtGui.QApplication.translate("Asistente", "Por ultima modificacion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Asistente", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:600;\">Lista de productos a contar.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9;\">Esta es la lista de productos que se contabilizaran, dependiendo de su modo de conteo, usted puede imprimir toda la lista para llenarla manualmente y luego pasar los datos con el conteo asistido o puede exportarla como una hoja de calculo, llenarla y despues importarla para el vaciado de datos.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tbImprimir.setText(QtGui.QApplication.translate("Asistente", "Imprimir lista", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_3.setText(QtGui.QApplication.translate("Asistente", "Exportar lista", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Asistente", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:600;\">Metodo de conteo</span></p>\n"
"<p align=\"justify\" style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Seleccione el modo en que desea contar, este puede ser de manera asistida que le pregunta la existencia  producto a producto de acuerdo a al orden establecido, y el modo manual que permite establecer la existencias seleccionando el producto.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Asistente", "Conteo Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.leFiltro.setToolTip(QtGui.QApplication.translate("Asistente", "Busque por descripcion,  referencia o codigo de barras el articulo", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_7.setText(QtGui.QApplication.translate("Asistente", "Buscar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabla.setToolTip(QtGui.QApplication.translate("Asistente", "Haga doble click para establecer las existencias de ese articulo.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Asistente", "Conteo asistido", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAntProd.setToolTip(QtGui.QApplication.translate("Asistente", "Pasar al anterior", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAntProd.setText(QtGui.QApplication.translate("Asistente", "Anterior", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAntProd.setShortcut(QtGui.QApplication.translate("Asistente", "Alt+Left", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSigProd.setToolTip(QtGui.QApplication.translate("Asistente", "Pasar al siguiente", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSigProd.setText(QtGui.QApplication.translate("Asistente", "Siguiente", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSigProd.setShortcut(QtGui.QApplication.translate("Asistente", "Alt+Right", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProducto.setText(QtGui.QApplication.translate("Asistente", "Producto:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbCPrecio.setText(QtGui.QApplication.translate("Asistente", "Precio:\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.tbManual.setText(QtGui.QApplication.translate("Asistente", "Conteo Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.tbManual.setShortcut(QtGui.QApplication.translate("Asistente", "Ins", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Asistente", "Existencias fisicas:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSetStock.setToolTip(QtGui.QApplication.translate("Asistente", "<h4>Contrl+G</h4>Establece la cantidad de existencias fisicas en el producto seleccionado.", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSetStock.setText(QtGui.QApplication.translate("Asistente", "Confirmar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSetStock.setShortcut(QtGui.QApplication.translate("Asistente", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_10.setText(QtGui.QApplication.translate("Asistente", "Exportar reporte", None, QtGui.QApplication.UnicodeUTF8))
        self.tbIncon.setText(QtGui.QApplication.translate("Asistente", "Ver inconsistencias", None, QtGui.QApplication.UnicodeUTF8))
        self.tbImprimir_2.setText(QtGui.QApplication.translate("Asistente", "Imprimir", None, QtGui.QApplication.UnicodeUTF8))
        self.qteResumen.setHtml(QtGui.QApplication.translate("Asistente", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\n"
"<tr>\n"
"<td bgcolor=\"#eeeeee\">\n"
"<p style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:xx-large; font-weight:600;\">Resumen de inventario</span><br /><span style=\" font-size:large; font-weight:600;\">$empresa</span></p></td>\n"
"<td bgcolor=\"#eeeeee\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Fecha:  $fecha<br />Departamentos:  $deps</span></p></td></tr></table>\n"
"<hr />\n"
"<table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\">\n"
"<tr>\n"
"<td></td>\n"
"<td></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Total de articulos contabilizados: </p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">$nacontados</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Valor del inventario (costo): </p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">$invalor</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Articulos con inconsistencias: </p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">$naicon</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Balance de inconsistencias (costo): </p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">$baincon</span></p></td></tr></table></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.bCorteP.setText(QtGui.QApplication.translate("Asistente", "Agrupar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPrintInc.setText(QtGui.QApplication.translate("Asistente", "Imprimir", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCancelar.setText(QtGui.QApplication.translate("Asistente", "Cancelar inventario", None, QtGui.QApplication.UnicodeUTF8))
        self.lbStatus.setText(QtGui.QApplication.translate("Asistente", "Preparacion de la base de datos 1 de 6", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAtras.setText(QtGui.QApplication.translate("Asistente", "Retroceder", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAdelante.setText(QtGui.QApplication.translate("Asistente", "Continuar", None, QtGui.QApplication.UnicodeUTF8))

