# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogos/ui_checador.ui'
#
# Created: Sun Oct  3 13:04:36 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 539)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/pyventa/images/png/64-barcode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbTop = QtGui.QToolButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbTop.sizePolicy().hasHeightForWidth())
        self.tbTop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.tbTop.setFont(font)
        self.tbTop.setObjectName("tbTop")
        self.horizontalLayout.addWidget(self.tbTop)
        self.codigo = QtGui.QLineEdit(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.codigo.sizePolicy().hasHeightForWidth())
        self.codigo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.codigo.setFont(font)
        self.codigo.setStyleSheet("""color:#eee;border:1px solid #bbb;
background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.772727 rgba(100, 100, 100, 255), stop:1 rgba(74, 74, 74, 255));""")
        self.codigo.setAlignment(QtCore.Qt.AlignCenter)
        self.codigo.setObjectName("codigo")
        self.horizontalLayout.addWidget(self.codigo)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.stack = QtGui.QStackedWidget(self.centralwidget)
        self.stack.setObjectName("stack")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtGui.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.stack.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtGui.QWidget(self.page_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblInfo = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblInfo.sizePolicy().hasHeightForWidth())
        self.lblInfo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setBold(True)
        self.lblInfo.setFont(font)
        self.lblInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblInfo.setWordWrap(True)
        self.lblInfo.setMargin(10)
        self.lblInfo.setObjectName("lblInfo")
        self.verticalLayout_3.addWidget(self.lblInfo)
        self.verticalLayout_4.addWidget(self.widget)
        self.lblPrecio = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPrecio.sizePolicy().hasHeightForWidth())
        self.lblPrecio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(44)
        font.setWeight(75)
        font.setBold(True)
        self.lblPrecio.setFont(font)
        self.lblPrecio.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPrecio.setObjectName("lblPrecio")
        self.verticalLayout_4.addWidget(self.lblPrecio)
        self.stack.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stack)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stack.setCurrentIndex(0)
        QtCore.QObject.connect(self.tbTop, QtCore.SIGNAL("triggered(QAction*)"), MainWindow.showFullScreen)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Checador de precios", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(25, 97, 112, 255), stop:1 rgba(20, 57, 72, 255));color:#fff;", None, QtGui.QApplication.UnicodeUTF8))
        self.widget_2.setStyleSheet(QtGui.QApplication.translate("MainWindow", "padding:10px;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(137, 137, 137, 255), stop:0.0545455 rgba(156, 156, 156, 255), stop:1 rgba(191, 191, 191, 255));\n"
"border:solid 1px #eee;", None, QtGui.QApplication.UnicodeUTF8))
        self.tbTop.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background:none;", None, QtGui.QApplication.UnicodeUTF8))
        self.tbTop.setText(QtGui.QApplication.translate("MainWindow", "Verificador de precios", None, QtGui.QApplication.UnicodeUTF8))
        self.tbTop.setShortcut(QtGui.QApplication.translate("MainWindow", "F11", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background:none;", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Pase el producto por el escaner.", None, QtGui.QApplication.UnicodeUTF8))
        self.widget.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background-color: rgba(10,10,10,100); border-radius:solid", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInfo.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background:none;", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInfo.setText(QtGui.QApplication.translate("MainWindow", "Informacion del producto\n"
" escaneado...", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPrecio.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background:none;", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPrecio.setText(QtGui.QApplication.translate("MainWindow", "Precio:", None, QtGui.QApplication.UnicodeUTF8))

