DELETE FROM cajas where num_caja>1 ;
DELETE FROM clientes where id>1 ;
DELETE FROM codigos ;
DELETE FROM compras ;
DELETE FROM comprados ;
DELETE FROM conexiones ;
DELETE FROM consultas ;
DELETE FROM departamentos where id>1 ;
DELETE FROM existencia ;
DELETE FROM familias where id>1 ;
DELETE FROM faltantes ;
DELETE FROM gastos ;
DELETE FROM impuestos where id>1 ;
DELETE FROM inventarios ;
DELETE FROM movimientos ;
DELETE FROM notas;
DELETE FROM notas_cobradas ;
DELETE FROM usuarios where id_usuario>2 ;
DELETE FROM unidades where id>1 ;
DELETE FROM ofertas ;
DELETE FROM productos ;
DELETE FROM promociones ;
DELETE FROM subproductos ;
DELETE FROM vendidos ;
DELETE FROM ventas ;
UPDATE usuarios set clave='1ddff545424249df81f3c4ab552dbb3d' where `id_usuario`=2;
