# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/modulos/ui_control1.ui'
#
# Created: Wed Apr 17 14:34:00 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Masul(object):
    def setupUi(self, Masul):
        Masul.setObjectName(_fromUtf8("Masul"))
        Masul.resize(698, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/window.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Masul.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Masul)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.topModule = QtGui.QWidget(Masul)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topModule.sizePolicy().hasHeightForWidth())
        self.topModule.setSizePolicy(sizePolicy)
        self.topModule.setStyleSheet(_fromUtf8("#topModule{padding:10px}"))
        self.topModule.setObjectName(_fromUtf8("topModule"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.topModule)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.fBuscar_6 = QtGui.QFrame(self.topModule)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fBuscar_6.sizePolicy().hasHeightForWidth())
        self.fBuscar_6.setSizePolicy(sizePolicy)
        self.fBuscar_6.setStyleSheet(_fromUtf8(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QLineEdit{background:transparent; border:0px; padding:3px}"))
        self.fBuscar_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fBuscar_6.setFrameShadow(QtGui.QFrame.Raised)
        self.fBuscar_6.setObjectName(_fromUtf8("fBuscar_6"))
        self.horizontalLayout_51 = QtGui.QHBoxLayout(self.fBuscar_6)
        self.horizontalLayout_51.setSpacing(0)
        self.horizontalLayout_51.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.tbHome = QtGui.QToolButton(self.fBuscar_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbHome.sizePolicy().hasHeightForWidth())
        self.tbHome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tbHome.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbHome.setIcon(icon1)
        self.tbHome.setIconSize(QtCore.QSize(18, 18))
        self.tbHome.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbHome.setObjectName(_fromUtf8("tbHome"))
        self.horizontalLayout_51.addWidget(self.tbHome)
        self.leTitulo = QtGui.QLabel(self.fBuscar_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.leTitulo.setFont(font)
        self.leTitulo.setText(_fromUtf8(""))
        self.leTitulo.setObjectName(_fromUtf8("leTitulo"))
        self.horizontalLayout_51.addWidget(self.leTitulo)
        self.lineEdit = QtGui.QLineEdit(self.fBuscar_6)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_51.addWidget(self.lineEdit)
        self._2.addWidget(self.fBuscar_6)
        self.verticalLayout_9.addLayout(self._2)
        self.horizontalLayout_52 = QtGui.QHBoxLayout()
        self.horizontalLayout_52.setSpacing(3)
        self.horizontalLayout_52.setObjectName(_fromUtf8("horizontalLayout_52"))
        self.tbLimpiar = QtGui.QToolButton(self.topModule)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbLimpiar.sizePolicy().hasHeightForWidth())
        self.tbLimpiar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbLimpiar.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbLimpiar.setIcon(icon2)
        self.tbLimpiar.setIconSize(QtCore.QSize(18, 18))
        self.tbLimpiar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbLimpiar.setAutoRaise(True)
        self.tbLimpiar.setObjectName(_fromUtf8("tbLimpiar"))
        self.horizontalLayout_52.addWidget(self.tbLimpiar)
        self.tbModif = QtGui.QToolButton(self.topModule)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbModif.sizePolicy().hasHeightForWidth())
        self.tbModif.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbModif.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/diskette.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbModif.setIcon(icon3)
        self.tbModif.setIconSize(QtCore.QSize(18, 18))
        self.tbModif.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbModif.setAutoRaise(True)
        self.tbModif.setObjectName(_fromUtf8("tbModif"))
        self.horizontalLayout_52.addWidget(self.tbModif)
        self.tbAgregar = QtGui.QToolButton(self.topModule)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbAgregar.sizePolicy().hasHeightForWidth())
        self.tbAgregar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbAgregar.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/copy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbAgregar.setIcon(icon4)
        self.tbAgregar.setIconSize(QtCore.QSize(18, 18))
        self.tbAgregar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbAgregar.setAutoRaise(True)
        self.tbAgregar.setObjectName(_fromUtf8("tbAgregar"))
        self.horizontalLayout_52.addWidget(self.tbAgregar)
        self.tbEliminar = QtGui.QToolButton(self.topModule)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbEliminar.sizePolicy().hasHeightForWidth())
        self.tbEliminar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbEliminar.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbEliminar.setIcon(icon5)
        self.tbEliminar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbEliminar.setAutoRaise(True)
        self.tbEliminar.setObjectName(_fromUtf8("tbEliminar"))
        self.horizontalLayout_52.addWidget(self.tbEliminar)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem)
        self.verticalLayout_9.addLayout(self.horizontalLayout_52)
        self.verticalLayout_3.addWidget(self.topModule)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tvTabla = QtGui.QTableView(Masul)
        self.tvTabla.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tvTabla.setAlternatingRowColors(True)
        self.tvTabla.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvTabla.setGridStyle(QtCore.Qt.DashLine)
        self.tvTabla.setSortingEnabled(True)
        self.tvTabla.setObjectName(_fromUtf8("tvTabla"))
        self.tvTabla.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tvTabla)
        self.splitter = QtGui.QSplitter(Masul)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.fDatos = QtGui.QFrame(self.splitter)
        self.fDatos.setObjectName(_fromUtf8("fDatos"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.fDatos)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblDatos = QtGui.QLabel(self.fDatos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDatos.sizePolicy().hasHeightForWidth())
        self.lblDatos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblDatos.setFont(font)
        self.lblDatos.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDatos.setWordWrap(True)
        self.lblDatos.setMargin(4)
        self.lblDatos.setObjectName(_fromUtf8("lblDatos"))
        self.verticalLayout_2.addWidget(self.lblDatos)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblInfo = QtGui.QLabel(self.fDatos)
        self.lblInfo.setWordWrap(True)
        self.lblInfo.setMargin(3)
        self.lblInfo.setObjectName(_fromUtf8("lblInfo"))
        self.horizontalLayout_3.addWidget(self.lblInfo)
        self.lblLogo = QtGui.QLabel(self.fDatos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLogo.sizePolicy().hasHeightForWidth())
        self.lblLogo.setSizePolicy(sizePolicy)
        self.lblLogo.setMaximumSize(QtCore.QSize(16777215, 64))
        self.lblLogo.setText(_fromUtf8(""))
        self.lblLogo.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../Users/usr/share/pyventa/images/png/64-box_open.png")))
        self.lblLogo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblLogo.setObjectName(_fromUtf8("lblLogo"))
        self.horizontalLayout_3.addWidget(self.lblLogo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.frame = QtGui.QFrame(self.fDatos)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.inDatos = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inDatos.sizePolicy().hasHeightForWidth())
        self.inDatos.setSizePolicy(sizePolicy)
        self.inDatos.setObjectName(_fromUtf8("inDatos"))
        self.formLay = QtGui.QFormLayout(self.inDatos)
        self.formLay.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLay.setObjectName(_fromUtf8("formLay"))
        self.verticalLayout_4.addWidget(self.inDatos)
        self.verticalLayout_2.addWidget(self.frame)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.splitter)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Masul)
        QtCore.QMetaObject.connectSlotsByName(Masul)

    def retranslateUi(self, Masul):
        Masul.setWindowTitle(QtGui.QApplication.translate("Masul", "Control administrativo", None, QtGui.QApplication.UnicodeUTF8))
        self.tbHome.setText(QtGui.QApplication.translate("Masul", "Tienda", None, QtGui.QApplication.UnicodeUTF8))
        self.tbHome.setShortcut(QtGui.QApplication.translate("Masul", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLimpiar.setToolTip(QtGui.QApplication.translate("Masul", "Nuevo producto", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLimpiar.setText(QtGui.QApplication.translate("Masul", "&Nuevo", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLimpiar.setShortcut(QtGui.QApplication.translate("Masul", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.tbModif.setToolTip(QtGui.QApplication.translate("Masul", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbModif.setText(QtGui.QApplication.translate("Masul", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbModif.setShortcut(QtGui.QApplication.translate("Masul", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAgregar.setToolTip(QtGui.QApplication.translate("Masul", "Restaurar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbAgregar.setText(QtGui.QApplication.translate("Masul", "Duplicar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbEliminar.setText(QtGui.QApplication.translate("Masul", "Eliminar", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDatos.setText(QtGui.QApplication.translate("Masul", "Detalle de elemento", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInfo.setText(QtGui.QApplication.translate("Masul", "Titulo del objeto", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
