# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui_nueva_lista.ui'
#
# Created: Tue Aug 16 04:18:43 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(605, 566)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget_17 = QtGui.QWidget(Form)
        self.widget_17.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_17.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_17.setStyleSheet(_fromUtf8("*{background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(13, 13, 13, 255), stop:0.504545 rgba(0, 0, 0, 255), stop:0.507692 rgba(27, 27, 27, 255), stop:1 rgba(69, 69, 69, 255));color: rgb(255, 255, 255);font-weight:700;}\n"
"QLabel{background:rgba(0,0,0,0)}"))
        self.widget_17.setObjectName(_fromUtf8("widget_17"))
        self.horizontalLayout_66 = QtGui.QHBoxLayout(self.widget_17)
        self.horizontalLayout_66.setMargin(0)
        self.horizontalLayout_66.setObjectName(_fromUtf8("horizontalLayout_66"))
        self.lblLogo = QtGui.QLabel(self.widget_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLogo.sizePolicy().hasHeightForWidth())
        self.lblLogo.setSizePolicy(sizePolicy)
        self.lblLogo.setMaximumSize(QtCore.QSize(32, 32))
        self.lblLogo.setText(_fromUtf8(""))
        self.lblLogo.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/png/Basket-64.png")))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setObjectName(_fromUtf8("lblLogo"))
        self.horizontalLayout_66.addWidget(self.lblLogo)
        self.lbTitulo = QtGui.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setWeight(87)
        font.setBold(True)
        self.lbTitulo.setFont(font)
        self.lbTitulo.setObjectName(_fromUtf8("lbTitulo"))
        self.horizontalLayout_66.addWidget(self.lbTitulo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_66.addItem(spacerItem)
        self.widget_18 = QtGui.QWidget(self.widget_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(87)
        font.setBold(True)
        self.widget_18.setFont(font)
        self.widget_18.setObjectName(_fromUtf8("widget_18"))
        self.horizontalLayout_67 = QtGui.QHBoxLayout(self.widget_18)
        self.horizontalLayout_67.setSpacing(2)
        self.horizontalLayout_67.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_67.setObjectName(_fromUtf8("horizontalLayout_67"))
        self.tbCancelar = QtGui.QToolButton(self.widget_18)
        font = QtGui.QFont()
        font.setWeight(87)
        font.setBold(True)
        self.tbCancelar.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/pyventa/images/32/silver/cancelar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbCancelar.setIcon(icon)
        self.tbCancelar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbCancelar.setObjectName(_fromUtf8("tbCancelar"))
        self.horizontalLayout_67.addWidget(self.tbCancelar)
        self.label_129 = QtGui.QLabel(self.widget_18)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_129.sizePolicy().hasHeightForWidth())
        self.label_129.setSizePolicy(sizePolicy)
        self.label_129.setMaximumSize(QtCore.QSize(20, 60))
        self.label_129.setText(_fromUtf8(""))
        self.label_129.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/pyventa/images/fx/separation.png")))
        self.label_129.setScaledContents(True)
        self.label_129.setObjectName(_fromUtf8("label_129"))
        self.horizontalLayout_67.addWidget(self.label_129)
        self.tbGuardar = QtGui.QToolButton(self.widget_18)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbGuardar.sizePolicy().hasHeightForWidth())
        self.tbGuardar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(87)
        font.setBold(True)
        self.tbGuardar.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../usr/share/pyventa/images/32/Check-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbGuardar.setIcon(icon1)
        self.tbGuardar.setIconSize(QtCore.QSize(24, 24))
        self.tbGuardar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbGuardar.setObjectName(_fromUtf8("tbGuardar"))
        self.horizontalLayout_67.addWidget(self.tbGuardar)
        self.toolButton_14 = QtGui.QToolButton(self.widget_18)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_14.sizePolicy().hasHeightForWidth())
        self.toolButton_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(87)
        font.setBold(True)
        self.toolButton_14.setFont(font)
        self.toolButton_14.setText(_fromUtf8(""))
        self.toolButton_14.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_14.setObjectName(_fromUtf8("toolButton_14"))
        self.horizontalLayout_67.addWidget(self.toolButton_14)
        self.horizontalLayout_66.addWidget(self.widget_18)
        self.verticalLayout.addWidget(self.widget_17)
        self.frame = QtGui.QFrame(Form)
        self.frame.setStyleSheet(_fromUtf8("#frame {background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(158, 158, 158, 255), stop:0.43 rgba(163, 163, 163, 255), stop:1 rgba(124, 124, 124, 255));}\n"
""))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.leCodigo = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.leCodigo.setFont(font)
        self.leCodigo.setStyleSheet(_fromUtf8("border:1px solid #999; border-radius:7px; padding:5px; \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(41, 41, 41, 255), stop:0.05 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.leCodigo.setObjectName(_fromUtf8("leCodigo"))
        self.gridLayout.addWidget(self.leCodigo, 1, 1, 1, 1)
        self.pbAgregar = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbAgregar.sizePolicy().hasHeightForWidth())
        self.pbAgregar.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/32/Add-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbAgregar.setIcon(icon2)
        self.pbAgregar.setIconSize(QtCore.QSize(32, 32))
        self.pbAgregar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.pbAgregar.setAutoRaise(True)
        self.pbAgregar.setObjectName(_fromUtf8("pbAgregar"))
        self.gridLayout.addWidget(self.pbAgregar, 1, 6, 1, 1)
        self.tbCambiar = QtGui.QToolButton(self.frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/32/Synchronize-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbCambiar.setIcon(icon3)
        self.tbCambiar.setIconSize(QtCore.QSize(32, 32))
        self.tbCambiar.setAutoRaise(True)
        self.tbCambiar.setObjectName(_fromUtf8("tbCambiar"))
        self.gridLayout.addWidget(self.tbCambiar, 1, 7, 1, 1)
        self.leCantidad = QtGui.QLineEdit(self.frame)
        self.leCantidad.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.leCantidad.setFont(font)
        self.leCantidad.setStyleSheet(_fromUtf8("border:1px solid #999; border-radius:7px; padding:5px; \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(41, 41, 41, 255), stop:0.05 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.leCantidad.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leCantidad.setObjectName(_fromUtf8("leCantidad"))
        self.gridLayout.addWidget(self.leCantidad, 1, 5, 1, 1)
        self.label_60 = QtGui.QLabel(self.frame)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout.addWidget(self.label_60, 0, 5, 1, 1)
        self.label_58 = QtGui.QLabel(self.frame)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout.addWidget(self.label_58, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.tabla = QtGui.QTableView(Form)
        self.tabla.setStyleSheet(_fromUtf8("background-color: qradialgradient(spread:pad, cx:0.677455, cy:0.659, radius:1.377, fx:0.149545, fy:0.244, stop:0.00454545 rgba(201, 215, 215, 255), stop:0.672727 rgba(255, 255, 255, 255), stop:1 rgba(181, 199, 223, 255));"))
        self.tabla.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabla.setAlternatingRowColors(True)
        self.tabla.setObjectName(_fromUtf8("tabla"))
        self.tabla.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.tabla)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.leCodigo, self.leCantidad)
        Form.setTabOrder(self.leCantidad, self.pbAgregar)
        Form.setTabOrder(self.pbAgregar, self.tbCambiar)
        Form.setTabOrder(self.tbCambiar, self.tabla)
        Form.setTabOrder(self.tabla, self.tbCancelar)
        Form.setTabOrder(self.tbCancelar, self.toolButton_14)
        Form.setTabOrder(self.toolButton_14, self.tbGuardar)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.lbTitulo.setStyleSheet(QtGui.QApplication.translate("Form", "background:none", None, QtGui.QApplication.UnicodeUTF8))
        self.lbTitulo.setText(QtGui.QApplication.translate("Form", "Nueva compra", None, QtGui.QApplication.UnicodeUTF8))
        self.widget_18.setStyleSheet(QtGui.QApplication.translate("Form", "border-radius:9px;\n"
"border: 2px solid #000;", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCancelar.setStyleSheet(QtGui.QApplication.translate("Form", " border:0px; background:none", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCancelar.setText(QtGui.QApplication.translate("Form", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_129.setStyleSheet(QtGui.QApplication.translate("Form", "background:none;border:0px", None, QtGui.QApplication.UnicodeUTF8))
        self.tbGuardar.setStyleSheet(QtGui.QApplication.translate("Form", " border:0px; background:none", None, QtGui.QApplication.UnicodeUTF8))
        self.tbGuardar.setText(QtGui.QApplication.translate("Form", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_14.setStyleSheet(QtGui.QApplication.translate("Form", " border:0px; background:none", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAgregar.setToolTip(QtGui.QApplication.translate("Form", "Agregar a la compra", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAgregar.setText(QtGui.QApplication.translate("Form", "Agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAgregar.setShortcut(QtGui.QApplication.translate("Form", "Ins", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCambiar.setToolTip(QtGui.QApplication.translate("Form", "Cambiar precio y agregar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCambiar.setText(QtGui.QApplication.translate("Form", "Calcular", None, QtGui.QApplication.UnicodeUTF8))
        self.leCantidad.setText(QtGui.QApplication.translate("Form", "1.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("Form", "Cantidad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("Form", "Producto", None, QtGui.QApplication.UnicodeUTF8))

