# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui_cobro.ui'
#
# Created: Wed Mar 23 23:52:42 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(694, 567)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titulo = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo.sizePolicy().hasHeightForWidth())
        self.titulo.setSizePolicy(sizePolicy)
        self.titulo.setObjectName("titulo")
        self.verticalLayout_2.addWidget(self.titulo)
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_2 = QtGui.QSplitter(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_28 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_28.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_28.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.twNotas = QtGui.QTableWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twNotas.sizePolicy().hasHeightForWidth())
        self.twNotas.setSizePolicy(sizePolicy)
        self.twNotas.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.twNotas.setFont(font)
        self.twNotas.setAcceptDrops(True)
        self.twNotas.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.twNotas.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twNotas.setObjectName("twNotas")
        self.twNotas.setColumnCount(0)
        self.twNotas.setRowCount(0)
        self.twNotas.verticalHeader().setHighlightSections(False)
        self.verticalLayout_28.addWidget(self.twNotas)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.leNumero = QtGui.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.leNumero.setFont(font)
        self.leNumero.setObjectName("leNumero")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.leNumero)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ncactualizar = QtGui.QToolButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ncactualizar.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../usr/share/pyventa/images/32/Synchronize-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ncactualizar.setIcon(icon)
        self.ncactualizar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.ncactualizar.setObjectName("ncactualizar")
        self.horizontalLayout_2.addWidget(self.ncactualizar)
        self.cbTipo = QtGui.QComboBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTipo.sizePolicy().hasHeightForWidth())
        self.cbTipo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbTipo.setFont(font)
        self.cbTipo.setObjectName("cbTipo")
        self.cbTipo.addItem("")
        self.cbTipo.addItem("")
        self.cbTipo.addItem("")
        self.horizontalLayout_2.addWidget(self.cbTipo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.bScliente = QtGui.QCommandLinkButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bScliente.sizePolicy().hasHeightForWidth())
        self.bScliente.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../usr/share/pyventa/images/32/User-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bScliente.setIcon(icon1)
        self.bScliente.setObjectName("bScliente")
        self.verticalLayout.addWidget(self.bScliente)
        self.scrollArea = QtGui.QScrollArea(self.layoutWidget1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 356, 148))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ncnotas = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ncnotas.setFont(font)
        self.ncnotas.setWordWrap(True)
        self.ncnotas.setMargin(10)
        self.ncnotas.setObjectName("ncnotas")
        self.verticalLayout_6.addWidget(self.ncnotas)
        self.pbLimpiar = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbLimpiar.sizePolicy().hasHeightForWidth())
        self.pbLimpiar.setSizePolicy(sizePolicy)
        self.pbLimpiar.setObjectName("pbLimpiar")
        self.verticalLayout_6.addWidget(self.pbLimpiar)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.nctotal = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nctotal.sizePolicy().hasHeightForWidth())
        self.nctotal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.nctotal.setFont(font)
        self.nctotal.setTextFormat(QtCore.Qt.PlainText)
        self.nctotal.setAlignment(QtCore.Qt.AlignCenter)
        self.nctotal.setWordWrap(True)
        self.nctotal.setMargin(10)
        self.nctotal.setObjectName("nctotal")
        self.verticalLayout.addWidget(self.nctotal)
        self.label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rbEfectivo = QtGui.QRadioButton(self.layoutWidget1)
        self.rbEfectivo.setChecked(True)
        self.rbEfectivo.setObjectName("rbEfectivo")
        self.verticalLayout_3.addWidget(self.rbEfectivo)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbCredito = QtGui.QRadioButton(self.layoutWidget1)
        self.rbCredito.setEnabled(False)
        self.rbCredito.setObjectName("rbCredito")
        self.horizontalLayout.addWidget(self.rbCredito)
        self.BClientSelect = QtGui.QCommandLinkButton(self.layoutWidget1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../usr/share/pyventa/images/16/user_16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BClientSelect.setIcon(icon2)
        self.BClientSelect.setObjectName("BClientSelect")
        self.horizontalLayout.addWidget(self.BClientSelect)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 8, -1, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_48 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_17.addWidget(self.label_48)
        self.ncrecibo = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ncrecibo.sizePolicy().hasHeightForWidth())
        self.ncrecibo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setWeight(75)
        font.setBold(True)
        self.ncrecibo.setFont(font)
        self.ncrecibo.setAlignment(QtCore.Qt.AlignCenter)
        self.ncrecibo.setDragEnabled(True)
        self.ncrecibo.setObjectName("ncrecibo")
        self.horizontalLayout_17.addWidget(self.ncrecibo)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.nccobrar = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nccobrar.sizePolicy().hasHeightForWidth())
        self.nccobrar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.nccobrar.setFont(font)
        self.nccobrar.setStyleSheet("padding:9;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../usr/share/pyventa/images/png/Money-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nccobrar.setIcon(icon3)
        self.nccobrar.setObjectName("nccobrar")
        self.verticalLayout.addWidget(self.nccobrar)
        self.verticalLayout_2.addWidget(self.splitter)

        self.retranslateUi(Form)
        self.cbTipo.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.leNumero, self.nccobrar)
        Form.setTabOrder(self.nccobrar, self.twNotas)
        Form.setTabOrder(self.twNotas, self.scrollArea)
        Form.setTabOrder(self.scrollArea, self.rbEfectivo)
        Form.setTabOrder(self.rbEfectivo, self.rbCredito)
        Form.setTabOrder(self.rbCredito, self.BClientSelect)
        Form.setTabOrder(self.BClientSelect, self.ncrecibo)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.titulo.setText(QtGui.QApplication.translate("Form", "Modulo de cobro de ventas.", None, QtGui.QApplication.UnicodeUTF8))
        self.twNotas.setSortingEnabled(True)
        self.label_2.setText(QtGui.QApplication.translate("Form", "Nota:", None, QtGui.QApplication.UnicodeUTF8))
        self.ncactualizar.setText(QtGui.QApplication.translate("Form", "Actualizar listado", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTipo.setToolTip(QtGui.QApplication.translate("Form", "Muestra la tabla de notas y/o facturas sin pagar del dia en curso.", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTipo.setItemText(0, QtGui.QApplication.translate("Form", "Todas las ventas", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTipo.setItemText(1, QtGui.QApplication.translate("Form", "Notas", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTipo.setItemText(2, QtGui.QApplication.translate("Form", "Facturas", None, QtGui.QApplication.UnicodeUTF8))
        self.bScliente.setToolTip(QtGui.QApplication.translate("Form", "Selecciona un cliente para mostrar el historial de \n"
"ventas en credito de ese cliente en particular.", None, QtGui.QApplication.UnicodeUTF8))
        self.bScliente.setText(QtGui.QApplication.translate("Form", "Seleccionar ventas pendientes por cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.ncnotas.setText(QtGui.QApplication.translate("Form", "Notas:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLimpiar.setText(QtGui.QApplication.translate("Form", "Limpiar", None, QtGui.QApplication.UnicodeUTF8))
        self.nctotal.setText(QtGui.QApplication.translate("Form", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Modo de pago", None, QtGui.QApplication.UnicodeUTF8))
        self.rbEfectivo.setText(QtGui.QApplication.translate("Form", "Efectivo", None, QtGui.QApplication.UnicodeUTF8))
        self.rbCredito.setText(QtGui.QApplication.translate("Form", "Credito cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.BClientSelect.setText(QtGui.QApplication.translate("Form", "Seleccionar cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("Form", "Recibo:", None, QtGui.QApplication.UnicodeUTF8))
        self.nccobrar.setText(QtGui.QApplication.translate("Form", "Cobrar", None, QtGui.QApplication.UnicodeUTF8))

