# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui_pyventa.ui'
#
# Created: Sun Jun  9 06:34:41 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Principal(object):
    def setupUi(self, Principal):
        Principal.setObjectName(_fromUtf8("Principal"))
        Principal.resize(938, 612)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/modulos/images/pyventa.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Principal.setWindowIcon(icon)
        Principal.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(Principal)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.head = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.head.sizePolicy().hasHeightForWidth())
        self.head.setSizePolicy(sizePolicy)
        self.head.setObjectName(_fromUtf8("head"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.head)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lpinfo = QtGui.QWidget(self.head)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lpinfo.sizePolicy().hasHeightForWidth())
        self.lpinfo.setSizePolicy(sizePolicy)
        self.lpinfo.setObjectName(_fromUtf8("lpinfo"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.lpinfo)
        self.verticalLayout_4.setContentsMargins(3, 0, 3, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3.addWidget(self.lpinfo)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tbmPyventa = QtGui.QToolButton(self.head)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbmPyventa.sizePolicy().hasHeightForWidth())
        self.tbmPyventa.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbmPyventa.setFont(font)
        self.tbmPyventa.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.tbmPyventa.setAutoRaise(True)
        self.tbmPyventa.setArrowType(QtCore.Qt.NoArrow)
        self.tbmPyventa.setObjectName(_fromUtf8("tbmPyventa"))
        self.horizontalLayout_2.addWidget(self.tbmPyventa)
        self.tbmArchivo = QtGui.QToolButton(self.head)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbmArchivo.sizePolicy().hasHeightForWidth())
        self.tbmArchivo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbmArchivo.setFont(font)
        self.tbmArchivo.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.tbmArchivo.setAutoRaise(True)
        self.tbmArchivo.setArrowType(QtCore.Qt.NoArrow)
        self.tbmArchivo.setObjectName(_fromUtf8("tbmArchivo"))
        self.horizontalLayout_2.addWidget(self.tbmArchivo)
        self.tbmEdicion = QtGui.QToolButton(self.head)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbmEdicion.sizePolicy().hasHeightForWidth())
        self.tbmEdicion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbmEdicion.setFont(font)
        self.tbmEdicion.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.tbmEdicion.setAutoRaise(True)
        self.tbmEdicion.setArrowType(QtCore.Qt.NoArrow)
        self.tbmEdicion.setObjectName(_fromUtf8("tbmEdicion"))
        self.horizontalLayout_2.addWidget(self.tbmEdicion)
        self.tbmModulos = QtGui.QToolButton(self.head)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbmModulos.sizePolicy().hasHeightForWidth())
        self.tbmModulos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbmModulos.setFont(font)
        self.tbmModulos.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.tbmModulos.setAutoRaise(True)
        self.tbmModulos.setObjectName(_fromUtf8("tbmModulos"))
        self.horizontalLayout_2.addWidget(self.tbmModulos)
        self.tbmHerramientas = QtGui.QToolButton(self.head)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbmHerramientas.sizePolicy().hasHeightForWidth())
        self.tbmHerramientas.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbmHerramientas.setFont(font)
        self.tbmHerramientas.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.tbmHerramientas.setAutoRaise(True)
        self.tbmHerramientas.setArrowType(QtCore.Qt.NoArrow)
        self.tbmHerramientas.setObjectName(_fromUtf8("tbmHerramientas"))
        self.horizontalLayout_2.addWidget(self.tbmHerramientas)
        self.tbmSesion = QtGui.QToolButton(self.head)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbmSesion.sizePolicy().hasHeightForWidth())
        self.tbmSesion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbmSesion.setFont(font)
        self.tbmSesion.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.tbmSesion.setAutoRaise(True)
        self.tbmSesion.setArrowType(QtCore.Qt.NoArrow)
        self.tbmSesion.setObjectName(_fromUtf8("tbmSesion"))
        self.horizontalLayout_2.addWidget(self.tbmSesion)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_12.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.fLine = QtGui.QFrame(self.head)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fLine.sizePolicy().hasHeightForWidth())
        self.fLine.setSizePolicy(sizePolicy)
        self.fLine.setStyleSheet(_fromUtf8(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QLineEdit,QDoubleSpinBox{background:transparent; border:0px; padding:3px}"))
        self.fLine.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fLine.setFrameShadow(QtGui.QFrame.Raised)
        self.fLine.setObjectName(_fromUtf8("fLine"))
        self.horizontalLayout_51 = QtGui.QHBoxLayout(self.fLine)
        self.horizontalLayout_51.setSpacing(0)
        self.horizontalLayout_51.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_51.setMargin(0)
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.codigo = QtGui.QLineEdit(self.fLine)
        self.codigo.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.codigo.setFont(font)
        self.codigo.setObjectName(_fromUtf8("codigo"))
        self.horizontalLayout_51.addWidget(self.codigo)
        self.dsbPrecio = QtGui.QDoubleSpinBox(self.fLine)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.dsbPrecio.setFont(font)
        self.dsbPrecio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbPrecio.setReadOnly(True)
        self.dsbPrecio.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dsbPrecio.setMaximum(99999.99)
        self.dsbPrecio.setObjectName(_fromUtf8("dsbPrecio"))
        self.horizontalLayout_51.addWidget(self.dsbPrecio)
        self.horizontalLayout_6.addWidget(self.fLine)
        self.fcant = QtGui.QFrame(self.head)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fcant.sizePolicy().hasHeightForWidth())
        self.fcant.setSizePolicy(sizePolicy)
        self.fcant.setStyleSheet(_fromUtf8(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QLineEdit{background:transparent; border:0px; padding:3px}"))
        self.fcant.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fcant.setFrameShadow(QtGui.QFrame.Raised)
        self.fcant.setObjectName(_fromUtf8("fcant"))
        self.horizontalLayout_52 = QtGui.QHBoxLayout(self.fcant)
        self.horizontalLayout_52.setSpacing(0)
        self.horizontalLayout_52.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_52.setObjectName(_fromUtf8("horizontalLayout_52"))
        self.cant = QtGui.QLineEdit(self.fcant)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cant.sizePolicy().hasHeightForWidth())
        self.cant.setSizePolicy(sizePolicy)
        self.cant.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cant.setFont(font)
        self.cant.setStyleSheet(_fromUtf8(""))
        self.cant.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cant.setObjectName(_fromUtf8("cant"))
        self.horizontalLayout_52.addWidget(self.cant)
        self.horizontalLayout_6.addWidget(self.fcant)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        spacerItem1 = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.hlm = QtGui.QHBoxLayout()
        self.hlm.setSpacing(1)
        self.hlm.setObjectName(_fromUtf8("hlm"))
        self.bventa = QtGui.QToolButton(self.head)
        self.bventa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/modulos/images/png/elegant/ventas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bventa.setIcon(icon1)
        self.bventa.setIconSize(QtCore.QSize(36, 36))
        self.bventa.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bventa.setAutoRaise(True)
        self.bventa.setObjectName(_fromUtf8("bventa"))
        self.hlm.addWidget(self.bventa)
        self.horizontalLayout_3.addLayout(self.hlm)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tbFull = QtGui.QToolButton(self.head)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/white_18/resize2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbFull.setIcon(icon2)
        self.tbFull.setIconSize(QtCore.QSize(18, 18))
        self.tbFull.setAutoRaise(True)
        self.tbFull.setObjectName(_fromUtf8("tbFull"))
        self.verticalLayout_7.addWidget(self.tbFull)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_10.addWidget(self.head)
        self.stack = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stack.sizePolicy().hasHeightForWidth())
        self.stack.setSizePolicy(sizePolicy)
        self.stack.setObjectName(_fromUtf8("stack"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frTablas = QtGui.QFrame(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frTablas.sizePolicy().hasHeightForWidth())
        self.frTablas.setSizePolicy(sizePolicy)
        self.frTablas.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frTablas.setFrameShadow(QtGui.QFrame.Raised)
        self.frTablas.setObjectName(_fromUtf8("frTablas"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frTablas)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.splitter = QtGui.QSplitter(self.frTablas)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(1)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lista2 = QtGui.QTableView(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lista2.setFont(font)
        self.lista2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lista2.setLineWidth(0)
        self.lista2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lista2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lista2.setAlternatingRowColors(True)
        self.lista2.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lista2.setShowGrid(False)
        self.lista2.setObjectName(_fromUtf8("lista2"))
        self.lista2.horizontalHeader().setVisible(False)
        self.lista2.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.lista2)
        self.gcanasta = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gcanasta.sizePolicy().hasHeightForWidth())
        self.gcanasta.setSizePolicy(sizePolicy)
        self.gcanasta.setObjectName(_fromUtf8("gcanasta"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.gcanasta)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gingreso = QtGui.QFrame(self.gcanasta)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.gingreso.sizePolicy().hasHeightForWidth())
        self.gingreso.setSizePolicy(sizePolicy)
        self.gingreso.setObjectName(_fromUtf8("gingreso"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.gingreso)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.widget_2 = QtGui.QWidget(self.gingreso)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.logo = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.logo.setFont(font)
        self.logo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.logo.setObjectName(_fromUtf8("logo"))
        self.verticalLayout_6.addWidget(self.logo)
        self.csCliente = QtGui.QToolButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csCliente.sizePolicy().hasHeightForWidth())
        self.csCliente.setSizePolicy(sizePolicy)
        self.csCliente.setMaximumSize(QtCore.QSize(190, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/administrator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.csCliente.setIcon(icon3)
        self.csCliente.setIconSize(QtCore.QSize(18, 18))
        self.csCliente.setAutoRepeat(True)
        self.csCliente.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.csCliente.setObjectName(_fromUtf8("csCliente"))
        self.verticalLayout_6.addWidget(self.csCliente)
        self.horizontalLayout_9.addWidget(self.widget_2)
        self.wLetreros = QtGui.QWidget(self.gingreso)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wLetreros.sizePolicy().hasHeightForWidth())
        self.wLetreros.setSizePolicy(sizePolicy)
        self.wLetreros.setObjectName(_fromUtf8("wLetreros"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wLetreros)
        self.gridLayout_2.setContentsMargins(-1, 2, -1, 2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lfecha = QtGui.QLabel(self.wLetreros)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfecha.sizePolicy().hasHeightForWidth())
        self.lfecha.setSizePolicy(sizePolicy)
        self.lfecha.setTextFormat(QtCore.Qt.RichText)
        self.lfecha.setObjectName(_fromUtf8("lfecha"))
        self.gridLayout_2.addWidget(self.lfecha, 0, 0, 1, 1)
        self.lnota = QtGui.QLabel(self.wLetreros)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnota.sizePolicy().hasHeightForWidth())
        self.lnota.setSizePolicy(sizePolicy)
        self.lnota.setTextFormat(QtCore.Qt.RichText)
        self.lnota.setObjectName(_fromUtf8("lnota"))
        self.gridLayout_2.addWidget(self.lnota, 1, 0, 1, 1)
        self.lblModo = QtGui.QLabel(self.wLetreros)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblModo.sizePolicy().hasHeightForWidth())
        self.lblModo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblModo.setFont(font)
        self.lblModo.setObjectName(_fromUtf8("lblModo"))
        self.gridLayout_2.addWidget(self.lblModo, 3, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.wLetreros)
        self.widget_5 = QtGui.QWidget(self.gingreso)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setContentsMargins(-1, -1, -1, 3)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.resumen = QtGui.QLabel(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resumen.sizePolicy().hasHeightForWidth())
        self.resumen.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resumen.setFont(font)
        self.resumen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resumen.setObjectName(_fromUtf8("resumen"))
        self.verticalLayout_15.addWidget(self.resumen)
        self.ltotal = QtGui.QLabel(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ltotal.sizePolicy().hasHeightForWidth())
        self.ltotal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.ltotal.setFont(font)
        self.ltotal.setScaledContents(True)
        self.ltotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ltotal.setMargin(5)
        self.ltotal.setObjectName(_fromUtf8("ltotal"))
        self.verticalLayout_15.addWidget(self.ltotal)
        self.horizontalLayout_9.addWidget(self.widget_5)
        self.verticalLayout_5.addWidget(self.gingreso)
        self.wResumen = QtGui.QWidget(self.gcanasta)
        self.wResumen.setMinimumSize(QtCore.QSize(0, 20))
        self.wResumen.setObjectName(_fromUtf8("wResumen"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.wResumen)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.widget = QtGui.QWidget(self.wResumen)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.chbImprimirTicket = QtGui.QCheckBox(self.widget)
        self.chbImprimirTicket.setChecked(True)
        self.chbImprimirTicket.setObjectName(_fromUtf8("chbImprimirTicket"))
        self.verticalLayout_11.addWidget(self.chbImprimirTicket)
        self.horizontalLayout_5.addWidget(self.widget)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.wResumen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dsbRecibido = QtGui.QDoubleSpinBox(self.wResumen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbRecibido.sizePolicy().hasHeightForWidth())
        self.dsbRecibido.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.dsbRecibido.setFont(font)
        self.dsbRecibido.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbRecibido.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dsbRecibido.setMaximum(99999.99)
        self.dsbRecibido.setObjectName(_fromUtf8("dsbRecibido"))
        self.gridLayout.addWidget(self.dsbRecibido, 0, 1, 1, 1)
        self.lblCambio = QtGui.QLabel(self.wResumen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCambio.sizePolicy().hasHeightForWidth())
        self.lblCambio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lblCambio.setFont(font)
        self.lblCambio.setObjectName(_fromUtf8("lblCambio"))
        self.gridLayout.addWidget(self.lblCambio, 1, 0, 1, 1)
        self.dsbCambio = QtGui.QDoubleSpinBox(self.wResumen)
        self.dsbCambio.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbCambio.sizePolicy().hasHeightForWidth())
        self.dsbCambio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.dsbCambio.setFont(font)
        self.dsbCambio.setFrame(True)
        self.dsbCambio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbCambio.setReadOnly(True)
        self.dsbCambio.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dsbCambio.setMaximum(99999.99)
        self.dsbCambio.setObjectName(_fromUtf8("dsbCambio"))
        self.gridLayout.addWidget(self.dsbCambio, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.wResumen)
        self.footer = QtGui.QWidget(self.gcanasta)
        self.footer.setObjectName(_fromUtf8("footer"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.footer)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.Promo = QtGui.QLabel(self.footer)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Promo.setFont(font)
        self.Promo.setStyleSheet(_fromUtf8(""))
        self.Promo.setText(_fromUtf8(""))
        self.Promo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Promo.setWordWrap(True)
        self.Promo.setMargin(5)
        self.Promo.setObjectName(_fromUtf8("Promo"))
        self.horizontalLayout_4.addWidget(self.Promo)
        self.verticalLayout_5.addWidget(self.footer)
        self.tabla = QtGui.QTableView(self.gcanasta)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabla.setFont(font)
        self.tabla.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tabla.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabla.setAlternatingRowColors(True)
        self.tabla.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tabla.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabla.setShowGrid(False)
        self.tabla.setSortingEnabled(True)
        self.tabla.setObjectName(_fromUtf8("tabla"))
        self.tabla.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.tabla)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.frTablas)
        self.stack.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.layoutWidget1 = QtGui.QWidget(self.page_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(470, 230, 213, 31))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.tbTrash = QtGui.QToolButton(self.layoutWidget1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/trash_can.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbTrash.setIcon(icon4)
        self.tbTrash.setIconSize(QtCore.QSize(18, 18))
        self.tbTrash.setAutoRaise(True)
        self.tbTrash.setObjectName(_fromUtf8("tbTrash"))
        self.horizontalLayout.addWidget(self.tbTrash)
        self.tbOpen = QtGui.QToolButton(self.layoutWidget1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbOpen.setIcon(icon5)
        self.tbOpen.setIconSize(QtCore.QSize(18, 18))
        self.tbOpen.setAutoRaise(True)
        self.tbOpen.setObjectName(_fromUtf8("tbOpen"))
        self.horizontalLayout.addWidget(self.tbOpen)
        self.tbSave = QtGui.QToolButton(self.layoutWidget1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/diskette.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSave.setIcon(icon6)
        self.tbSave.setIconSize(QtCore.QSize(18, 18))
        self.tbSave.setAutoRaise(True)
        self.tbSave.setObjectName(_fromUtf8("tbSave"))
        self.horizontalLayout.addWidget(self.tbSave)
        self.tbExport = QtGui.QToolButton(self.layoutWidget1)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/clip.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbExport.setIcon(icon7)
        self.tbExport.setIconSize(QtCore.QSize(18, 18))
        self.tbExport.setAutoRaise(True)
        self.tbExport.setObjectName(_fromUtf8("tbExport"))
        self.horizontalLayout.addWidget(self.tbExport)
        self.tbRegist = QtGui.QToolButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbRegist.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/thunder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbRegist.setIcon(icon8)
        self.tbRegist.setIconSize(QtCore.QSize(18, 18))
        self.tbRegist.setAutoRaise(True)
        self.tbRegist.setObjectName(_fromUtf8("tbRegist"))
        self.horizontalLayout.addWidget(self.tbRegist)
        self.stack.addWidget(self.page_2)
        self.verticalLayout_10.addWidget(self.stack)
        Principal.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Principal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 938, 26))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuModulos = QtGui.QMenu(self.menubar)
        self.menuModulos.setObjectName(_fromUtf8("menuModulos"))
        self.menuEdicion = QtGui.QMenu(self.menubar)
        self.menuEdicion.setObjectName(_fromUtf8("menuEdicion"))
        self.menuSesion = QtGui.QMenu(self.menubar)
        self.menuSesion.setObjectName(_fromUtf8("menuSesion"))
        self.menuHerramientas = QtGui.QMenu(self.menubar)
        self.menuHerramientas.setObjectName(_fromUtf8("menuHerramientas"))
        self.menuPyventa = QtGui.QMenu(self.menubar)
        self.menuPyventa.setObjectName(_fromUtf8("menuPyventa"))
        self.menuMostrar = QtGui.QMenu(self.menuPyventa)
        self.menuMostrar.setObjectName(_fromUtf8("menuMostrar"))
        Principal.setMenuBar(self.menubar)
        self.actionNueva = QtGui.QAction(Principal)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNueva.setIcon(icon9)
        self.actionNueva.setIconVisibleInMenu(True)
        self.actionNueva.setObjectName(_fromUtf8("actionNueva"))
        self.actionImprimir = QtGui.QAction(Principal)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImprimir.setIcon(icon10)
        self.actionImprimir.setIconVisibleInMenu(True)
        self.actionImprimir.setObjectName(_fromUtf8("actionImprimir"))
        self.actionEliminar = QtGui.QAction(Principal)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../.designer/backup/images/icons/elimina.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEliminar.setIcon(icon11)
        self.actionEliminar.setObjectName(_fromUtf8("actionEliminar"))
        self.actionBuscador = QtGui.QAction(Principal)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/search_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBuscador.setIcon(icon12)
        self.actionBuscador.setObjectName(_fromUtf8("actionBuscador"))
        self.actionAdministrador = QtGui.QAction(Principal)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../.designer/backup/images/icons/16/plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdministrador.setIcon(icon13)
        self.actionAdministrador.setObjectName(_fromUtf8("actionAdministrador"))
        self.actionVentas_del_dia = QtGui.QAction(Principal)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/statistics_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVentas_del_dia.setIcon(icon14)
        self.actionVentas_del_dia.setObjectName(_fromUtf8("actionVentas_del_dia"))
        self.aGuardar = QtGui.QAction(Principal)
        self.aGuardar.setIcon(icon6)
        self.aGuardar.setIconVisibleInMenu(True)
        self.aGuardar.setObjectName(_fromUtf8("aGuardar"))
        self.actionOpen = QtGui.QAction(Principal)
        self.actionOpen.setIcon(icon5)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionAgregar_clientes = QtGui.QAction(Principal)
        self.actionAgregar_clientes.setObjectName(_fromUtf8("actionAgregar_clientes"))
        self.actionCartera_de_clientes = QtGui.QAction(Principal)
        self.actionCartera_de_clientes.setObjectName(_fromUtf8("actionCartera_de_clientes"))
        self.action_Cambiar_cliente_actual = QtGui.QAction(Principal)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../.designer/backup/images/icons/camuser.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Cambiar_cliente_actual.setIcon(icon15)
        self.action_Cambiar_cliente_actual.setObjectName(_fromUtf8("action_Cambiar_cliente_actual"))
        self.actionBase_de_datos = QtGui.QAction(Principal)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/database-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBase_de_datos.setIcon(icon16)
        self.actionBase_de_datos.setObjectName(_fromUtf8("actionBase_de_datos"))
        self.actionRespaldar = QtGui.QAction(Principal)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/warning_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRespaldar.setIcon(icon17)
        self.actionRespaldar.setObjectName(_fromUtf8("actionRespaldar"))
        self.actionUpdate = QtGui.QAction(Principal)
        self.actionUpdate.setObjectName(_fromUtf8("actionUpdate"))
        self.actionCompleta = QtGui.QAction(Principal)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/32/monitor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompleta.setIcon(icon18)
        self.actionCompleta.setIconVisibleInMenu(True)
        self.actionCompleta.setObjectName(_fromUtf8("actionCompleta"))
        self.actionNormal = QtGui.QAction(Principal)
        self.actionNormal.setIconVisibleInMenu(True)
        self.actionNormal.setObjectName(_fromUtf8("actionNormal"))
        self.actionMini = QtGui.QAction(Principal)
        self.actionMini.setIconVisibleInMenu(True)
        self.actionMini.setObjectName(_fromUtf8("actionMini"))
        self.actionPlantilla_de_presupuesto = QtGui.QAction(Principal)
        self.actionPlantilla_de_presupuesto.setObjectName(_fromUtf8("actionPlantilla_de_presupuesto"))
        self.actionNota_de_venta = QtGui.QAction(Principal)
        self.actionNota_de_venta.setObjectName(_fromUtf8("actionNota_de_venta"))
        self.actionA_Pyventa = QtGui.QAction(Principal)
        self.actionA_Pyventa.setIconVisibleInMenu(True)
        self.actionA_Pyventa.setObjectName(_fromUtf8("actionA_Pyventa"))
        self.actionVersion = QtGui.QAction(Principal)
        self.actionVersion.setObjectName(_fromUtf8("actionVersion"))
        self.actionGuardar = QtGui.QAction(Principal)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/hard_disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardar.setIcon(icon19)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionCerrar = QtGui.QAction(Principal)
        self.actionCerrar.setObjectName(_fromUtf8("actionCerrar"))
        self.actionReimprimir = QtGui.QAction(Principal)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/gray_18/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReimprimir.setIcon(icon20)
        self.actionReimprimir.setObjectName(_fromUtf8("actionReimprimir"))
        self.actionFactura = QtGui.QAction(Principal)
        self.actionFactura.setObjectName(_fromUtf8("actionFactura"))
        self.actionCancelar_nota = QtGui.QAction(Principal)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCancelar_nota.setIcon(icon21)
        self.actionCancelar_nota.setIconVisibleInMenu(True)
        self.actionCancelar_nota.setObjectName(_fromUtf8("actionCancelar_nota"))
        self.actionEditar_ticket = QtGui.QAction(Principal)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/pencil_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditar_ticket.setIcon(icon22)
        self.actionEditar_ticket.setObjectName(_fromUtf8("actionEditar_ticket"))
        self.actionQuitar_prod = QtGui.QAction(Principal)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuitar_prod.setIcon(icon23)
        self.actionQuitar_prod.setIconVisibleInMenu(True)
        self.actionQuitar_prod.setObjectName(_fromUtf8("actionQuitar_prod"))
        self.actionRecibos = QtGui.QAction(Principal)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/globe_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecibos.setIcon(icon24)
        self.actionRecibos.setObjectName(_fromUtf8("actionRecibos"))
        self.actionCopiar_nota = QtGui.QAction(Principal)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/clipboard_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopiar_nota.setIcon(icon25)
        self.actionCopiar_nota.setObjectName(_fromUtf8("actionCopiar_nota"))
        self.actionCerrar_nota = QtGui.QAction(Principal)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/checkmark2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCerrar_nota.setIcon(icon26)
        self.actionCerrar_nota.setIconVisibleInMenu(True)
        self.actionCerrar_nota.setObjectName(_fromUtf8("actionCerrar_nota"))
        self.actionVer_barra = QtGui.QAction(Principal)
        self.actionVer_barra.setCheckable(False)
        self.actionVer_barra.setChecked(False)
        self.actionVer_barra.setObjectName(_fromUtf8("actionVer_barra"))
        self.actionCobrar_notas = QtGui.QAction(Principal)
        self.actionCobrar_notas.setObjectName(_fromUtf8("actionCobrar_notas"))
        self.aAbrir = QtGui.QAction(Principal)
        self.aAbrir.setIcon(icon5)
        self.aAbrir.setIconVisibleInMenu(True)
        self.aAbrir.setObjectName(_fromUtf8("aAbrir"))
        self.actionPreferencias = QtGui.QAction(Principal)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/gear_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferencias.setIcon(icon27)
        self.actionPreferencias.setObjectName(_fromUtf8("actionPreferencias"))
        self.actionPunto_de_venta = QtGui.QAction(Principal)
        self.actionPunto_de_venta.setIcon(icon1)
        self.actionPunto_de_venta.setIconVisibleInMenu(True)
        self.actionPunto_de_venta.setObjectName(_fromUtf8("actionPunto_de_venta"))
        self.actionIngresar = QtGui.QAction(Principal)
        self.actionIngresar.setIcon(icon9)
        self.actionIngresar.setIconVisibleInMenu(True)
        self.actionIngresar.setObjectName(_fromUtf8("actionIngresar"))
        self.actionFacturar = QtGui.QAction(Principal)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFacturar.setIcon(icon28)
        self.actionFacturar.setIconVisibleInMenu(True)
        self.actionFacturar.setObjectName(_fromUtf8("actionFacturar"))
        self.actionProductos = QtGui.QAction(Principal)
        self.actionProductos.setObjectName(_fromUtf8("actionProductos"))
        self.actionCambiar_estilo = QtGui.QAction(Principal)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/32/paint.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCambiar_estilo.setIcon(icon29)
        self.actionCambiar_estilo.setObjectName(_fromUtf8("actionCambiar_estilo"))
        self.actionModo_rapido = QtGui.QAction(Principal)
        self.actionModo_rapido.setCheckable(True)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/fast_forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModo_rapido.setIcon(icon30)
        self.actionModo_rapido.setObjectName(_fromUtf8("actionModo_rapido"))
        self.actionPresupuesto = QtGui.QAction(Principal)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/document.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPresupuesto.setIcon(icon31)
        self.actionPresupuesto.setIconVisibleInMenu(True)
        self.actionPresupuesto.setObjectName(_fromUtf8("actionPresupuesto"))
        self.actionAutorizar_descuento = QtGui.QAction(Principal)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/key.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAutorizar_descuento.setIcon(icon32)
        self.actionAutorizar_descuento.setObjectName(_fromUtf8("actionAutorizar_descuento"))
        self.actionAbrir_cajon = QtGui.QAction(Principal)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/bell.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbrir_cajon.setIcon(icon33)
        self.actionAbrir_cajon.setIconVisibleInMenu(True)
        self.actionAbrir_cajon.setObjectName(_fromUtf8("actionAbrir_cajon"))
        self.actionCambiar_usuario = QtGui.QAction(Principal)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/group.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCambiar_usuario.setIcon(icon34)
        self.actionCambiar_usuario.setIconVisibleInMenu(True)
        self.actionCambiar_usuario.setObjectName(_fromUtf8("actionCambiar_usuario"))
        self.actionNueva_sesion = QtGui.QAction(Principal)
        self.actionNueva_sesion.setIcon(icon3)
        self.actionNueva_sesion.setIconVisibleInMenu(True)
        self.actionNueva_sesion.setObjectName(_fromUtf8("actionNueva_sesion"))
        self.actionCerrar_sesion = QtGui.QAction(Principal)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/disconnect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCerrar_sesion.setIcon(icon35)
        self.actionCerrar_sesion.setIconVisibleInMenu(True)
        self.actionCerrar_sesion.setObjectName(_fromUtf8("actionCerrar_sesion"))
        self.aConfigBd = QtGui.QAction(Principal)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/spreadsheet.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aConfigBd.setIcon(icon36)
        self.aConfigBd.setObjectName(_fromUtf8("aConfigBd"))
        self.actionGuardarcompra = QtGui.QAction(Principal)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/download2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardarcompra.setIcon(icon37)
        self.actionGuardarcompra.setIconVisibleInMenu(True)
        self.actionGuardarcompra.setObjectName(_fromUtf8("actionGuardarcompra"))
        self.actionAbrir_compra = QtGui.QAction(Principal)
        self.actionAbrir_compra.setIcon(icon5)
        self.actionAbrir_compra.setObjectName(_fromUtf8("actionAbrir_compra"))
        self.actionNueva_compra = QtGui.QAction(Principal)
        self.actionNueva_compra.setIcon(icon9)
        self.actionNueva_compra.setObjectName(_fromUtf8("actionNueva_compra"))
        self.actionSwap = QtGui.QAction(Principal)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/arrow_bidirectional.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSwap.setIcon(icon38)
        self.actionSwap.setIconVisibleInMenu(True)
        self.actionSwap.setObjectName(_fromUtf8("actionSwap"))
        self.action = QtGui.QAction(Principal)
        self.action.setObjectName(_fromUtf8("action"))
        self.actionAbrir_venta_extemporanea = QtGui.QAction(Principal)
        self.actionAbrir_venta_extemporanea.setIcon(icon5)
        self.actionAbrir_venta_extemporanea.setObjectName(_fromUtf8("actionAbrir_venta_extemporanea"))
        self.actionReimprimir_archivada = QtGui.QAction(Principal)
        self.actionReimprimir_archivada.setIcon(icon10)
        self.actionReimprimir_archivada.setObjectName(_fromUtf8("actionReimprimir_archivada"))
        self.menuArchivo.addAction(self.actionOpen)
        self.menuArchivo.addAction(self.aAbrir)
        self.menuArchivo.addAction(self.actionAbrir_venta_extemporanea)
        self.menuArchivo.addAction(self.actionAbrir_compra)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.aGuardar)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardarcompra)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionNueva)
        self.menuArchivo.addAction(self.actionNueva_compra)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionFacturar)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionImprimir)
        self.menuArchivo.addAction(self.actionReimprimir)
        self.menuArchivo.addAction(self.actionReimprimir_archivada)
        self.menuArchivo.addAction(self.actionPresupuesto)
        self.menuArchivo.addSeparator()
        self.menuModulos.addAction(self.actionPunto_de_venta)
        self.menuModulos.addSeparator()
        self.menuModulos.addAction(self.actionVer_barra)
        self.menuEdicion.addAction(self.actionCerrar_nota)
        self.menuEdicion.addAction(self.actionCancelar_nota)
        self.menuEdicion.addSeparator()
        self.menuEdicion.addAction(self.actionIngresar)
        self.menuEdicion.addAction(self.actionQuitar_prod)
        self.menuEdicion.addAction(self.actionModo_rapido)
        self.menuEdicion.addAction(self.actionAutorizar_descuento)
        self.menuEdicion.addAction(self.actionAbrir_cajon)
        self.menuSesion.addAction(self.actionNueva_sesion)
        self.menuSesion.addAction(self.actionCambiar_usuario)
        self.menuSesion.addAction(self.actionCerrar_sesion)
        self.menuHerramientas.addAction(self.actionSwap)
        self.menuHerramientas.addAction(self.aConfigBd)
        self.menuMostrar.addAction(self.actionMini)
        self.menuMostrar.addAction(self.actionNormal)
        self.menuMostrar.addAction(self.actionCompleta)
        self.menuPyventa.addAction(self.actionA_Pyventa)
        self.menuPyventa.addAction(self.menuMostrar.menuAction())
        self.menuPyventa.addAction(self.actionCerrar)
        self.menubar.addAction(self.menuPyventa.menuAction())
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEdicion.menuAction())
        self.menubar.addAction(self.menuModulos.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())
        self.menubar.addAction(self.menuSesion.menuAction())

        self.retranslateUi(Principal)
        self.stack.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionNormal, QtCore.SIGNAL(_fromUtf8("triggered()")), Principal.showMaximized)
        QtCore.QObject.connect(self.actionCompleta, QtCore.SIGNAL(_fromUtf8("triggered()")), Principal.showFullScreen)
        QtCore.QObject.connect(self.actionCerrar, QtCore.SIGNAL(_fromUtf8("triggered()")), Principal.close)
        QtCore.QMetaObject.connectSlotsByName(Principal)
        Principal.setTabOrder(self.codigo, self.lista2)
        Principal.setTabOrder(self.lista2, self.cant)
        Principal.setTabOrder(self.cant, self.tabla)
        Principal.setTabOrder(self.tabla, self.tbTrash)
        Principal.setTabOrder(self.tbTrash, self.tbOpen)
        Principal.setTabOrder(self.tbOpen, self.tbSave)
        Principal.setTabOrder(self.tbSave, self.tbExport)
        Principal.setTabOrder(self.tbExport, self.tbRegist)
        Principal.setTabOrder(self.tbRegist, self.dsbRecibido)
        Principal.setTabOrder(self.dsbRecibido, self.dsbCambio)
        Principal.setTabOrder(self.dsbCambio, self.csCliente)
        Principal.setTabOrder(self.csCliente, self.tbmPyventa)
        Principal.setTabOrder(self.tbmPyventa, self.tbmArchivo)
        Principal.setTabOrder(self.tbmArchivo, self.tbFull)
        Principal.setTabOrder(self.tbFull, self.dsbPrecio)
        Principal.setTabOrder(self.dsbPrecio, self.tbmEdicion)
        Principal.setTabOrder(self.tbmEdicion, self.tbmModulos)
        Principal.setTabOrder(self.tbmModulos, self.tbmHerramientas)
        Principal.setTabOrder(self.tbmHerramientas, self.tbmSesion)
        Principal.setTabOrder(self.tbmSesion, self.bventa)

    def retranslateUi(self, Principal):
        Principal.setWindowTitle(_translate("Principal", "Pyventa - Punto de venta", None))
        self.tbmPyventa.setText(_translate("Principal", "Pyventa", None))
        self.tbmArchivo.setText(_translate("Principal", "Archivo", None))
        self.tbmEdicion.setText(_translate("Principal", "Edicion", None))
        self.tbmModulos.setText(_translate("Principal", "Modulos", None))
        self.tbmHerramientas.setText(_translate("Principal", "Herramientas", None))
        self.tbmSesion.setText(_translate("Principal", "Sesion", None))
        self.codigo.setToolTip(_translate("Principal", "Referencia, codigo o descripcion", None))
        self.dsbPrecio.setToolTip(_translate("Principal", "Precio", None))
        self.dsbPrecio.setPrefix(_translate("Principal", "$", None))
        self.cant.setToolTip(_translate("Principal", "Cantidad", None))
        self.cant.setText(_translate("Principal", "1.00", None))
        self.bventa.setToolTip(_translate("Principal", "<h1>Insert</h1>Ir a la venta", None))
        self.bventa.setText(_translate("Principal", "Punto", None))
        self.tbFull.setText(_translate("Principal", "...", None))
        self.logo.setText(_translate("Principal", "Nota de Venta", None))
        self.csCliente.setToolTip(_translate("Principal", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Para seleccionar un cliente de manera rapida solo presione las teclas \"<span style=\" font-weight:600;\">Control</span>\" y \"<span style=\" font-weight:600;\">K</span>\"</p></body></html>", None))
        self.csCliente.setText(_translate("Principal", "Seleccionar un cliente", None))
        self.csCliente.setShortcut(_translate("Principal", "Ctrl+K", None))
        self.lfecha.setText(_translate("Principal", "<b>Fecha:</b>", None))
        self.lnota.setText(_translate("Principal", "Nota:", None))
        self.lblModo.setText(_translate("Principal", "Ingreso manual", None))
        self.resumen.setText(_translate("Principal", "Gran Total", None))
        self.ltotal.setText(_translate("Principal", "$000.00", None))
        self.chbImprimirTicket.setText(_translate("Principal", "Imprimir comprobante", None))
        self.label.setText(_translate("Principal", "Recibido:", None))
        self.dsbRecibido.setPrefix(_translate("Principal", "$", None))
        self.lblCambio.setText(_translate("Principal", "Cambio", None))
        self.dsbCambio.setPrefix(_translate("Principal", "$", None))
        self.tbTrash.setToolTip(_translate("Principal", "Cancelar", None))
        self.tbTrash.setText(_translate("Principal", "Cancelar", None))
        self.tbOpen.setToolTip(_translate("Principal", "Abrir venta", None))
        self.tbOpen.setText(_translate("Principal", "Abrir", None))
        self.tbSave.setToolTip(_translate("Principal", "Guardar", None))
        self.tbSave.setText(_translate("Principal", "Guardar", None))
        self.tbExport.setToolTip(_translate("Principal", "Exportar", None))
        self.tbExport.setText(_translate("Principal", "Exportar", None))
        self.tbRegist.setToolTip(_translate("Principal", "Finalizar venta F5", None))
        self.tbRegist.setText(_translate("Principal", "Completar", None))
        self.menuArchivo.setTitle(_translate("Principal", "Archivo", None))
        self.menuModulos.setTitle(_translate("Principal", "Modulos", None))
        self.menuEdicion.setTitle(_translate("Principal", "Edicion", None))
        self.menuSesion.setTitle(_translate("Principal", "Sesion", None))
        self.menuHerramientas.setTitle(_translate("Principal", "Herramientas", None))
        self.menuPyventa.setTitle(_translate("Principal", "Pyventa", None))
        self.menuMostrar.setTitle(_translate("Principal", "Modo de ventana", None))
        self.actionNueva.setText(_translate("Principal", "&Nueva nota", None))
        self.actionNueva.setShortcut(_translate("Principal", "Ctrl+N", None))
        self.actionImprimir.setText(_translate("Principal", "Im&primir ", None))
        self.actionImprimir.setShortcut(_translate("Principal", "Ctrl+P", None))
        self.actionEliminar.setText(_translate("Principal", "Eliminar nota", None))
        self.actionBuscador.setText(_translate("Principal", "Buscador", None))
        self.actionBuscador.setShortcut(_translate("Principal", "F3", None))
        self.actionAdministrador.setText(_translate("Principal", "Administrador", None))
        self.actionVentas_del_dia.setText(_translate("Principal", "Reporte de ventas", None))
        self.aGuardar.setText(_translate("Principal", "&Guardar", None))
        self.aGuardar.setShortcut(_translate("Principal", "Ctrl+G", None))
        self.actionOpen.setText(_translate("Principal", "&Abrir archivo", None))
        self.actionOpen.setShortcut(_translate("Principal", "Ctrl+O", None))
        self.actionAgregar_clientes.setText(_translate("Principal", "Alta de clientes.", None))
        self.actionCartera_de_clientes.setText(_translate("Principal", "Cartera de clientes.", None))
        self.action_Cambiar_cliente_actual.setText(_translate("Principal", " Cambiar cliente actual", None))
        self.actionBase_de_datos.setText(_translate("Principal", "Base de datos", None))
        self.actionRespaldar.setText(_translate("Principal", "Generar Respaldo", None))
        self.actionUpdate.setText(_translate("Principal", "Actualizacion", None))
        self.actionCompleta.setText(_translate("Principal", "Pantalla Completa", None))
        self.actionCompleta.setShortcut(_translate("Principal", "F11", None))
        self.actionNormal.setText(_translate("Principal", "Normal", None))
        self.actionNormal.setShortcut(_translate("Principal", "F10", None))
        self.actionMini.setText(_translate("Principal", "Compacta", None))
        self.actionPlantilla_de_presupuesto.setText(_translate("Principal", "Plantilla de presupuesto", None))
        self.actionNota_de_venta.setText(_translate("Principal", "Nota de venta", None))
        self.actionA_Pyventa.setText(_translate("Principal", "Acerca de Pyventa", None))
        self.actionVersion.setText(_translate("Principal", "Acerca de Ottarw", None))
        self.actionGuardar.setText(_translate("Principal", "&Guardar como...", None))
        self.actionGuardar.setShortcut(_translate("Principal", "Ctrl+S", None))
        self.actionCerrar.setText(_translate("Principal", "Cerrar Pyventa", None))
        self.actionCerrar.setToolTip(_translate("Principal", "Cierra el programa.", None))
        self.actionCerrar.setShortcut(_translate("Principal", "Ctrl+Q", None))
        self.actionReimprimir.setText(_translate("Principal", "&Reimprimir", None))
        self.actionFactura.setText(_translate("Principal", "Factura", None))
        self.actionCancelar_nota.setText(_translate("Principal", "Cancelar venta", None))
        self.actionEditar_ticket.setText(_translate("Principal", "Editar ticket", None))
        self.actionQuitar_prod.setText(_translate("Principal", "Quitar producto", None))
        self.actionQuitar_prod.setShortcut(_translate("Principal", "Del", None))
        self.actionRecibos.setText(_translate("Principal", "Recibos telmex", None))
        self.actionRecibos.setShortcut(_translate("Principal", "F4", None))
        self.actionCopiar_nota.setText(_translate("Principal", "Copiar venta", None))
        self.actionCopiar_nota.setShortcut(_translate("Principal", "Ctrl+C", None))
        self.actionCerrar_nota.setText(_translate("Principal", "Finalizar", None))
        self.actionCerrar_nota.setShortcut(_translate("Principal", "F5", None))
        self.actionVer_barra.setText(_translate("Principal", "Ver Barra de modulos", None))
        self.actionCobrar_notas.setText(_translate("Principal", "Cobrar Notas", None))
        self.aAbrir.setText(_translate("Principal", "Abrir venta", None))
        self.aAbrir.setStatusTip(_translate("Principal", "Cancela la nota enterior y copia sus valores a la nota actual", None))
        self.aAbrir.setShortcut(_translate("Principal", "Ctrl+A", None))
        self.actionPreferencias.setText(_translate("Principal", "Preferencias", None))
        self.actionPunto_de_venta.setText(_translate("Principal", "Punto de venta", None))
        self.actionPunto_de_venta.setShortcut(_translate("Principal", "Home", None))
        self.actionIngresar.setText(_translate("Principal", "Ingresar producto", None))
        self.actionIngresar.setShortcut(_translate("Principal", "Ins", None))
        self.actionFacturar.setText(_translate("Principal", "&Facturar", None))
        self.actionFacturar.setShortcut(_translate("Principal", "Ctrl+F", None))
        self.actionProductos.setText(_translate("Principal", "Productos", None))
        self.actionCambiar_estilo.setText(_translate("Principal", "Cambiar estilo", None))
        self.actionModo_rapido.setText(_translate("Principal", "Modo  rapido", None))
        self.actionModo_rapido.setShortcut(_translate("Principal", "F7", None))
        self.actionPresupuesto.setText(_translate("Principal", "Imprimir como presupuesto", None))
        self.actionAutorizar_descuento.setText(_translate("Principal", "Autorizar descuento", None))
        self.actionAutorizar_descuento.setShortcut(_translate("Principal", "F2", None))
        self.actionAbrir_cajon.setText(_translate("Principal", "Abrir cajon", None))
        self.actionAbrir_cajon.setShortcut(_translate("Principal", "F1", None))
        self.actionCambiar_usuario.setText(_translate("Principal", "Cambiar usuario", None))
        self.actionNueva_sesion.setText(_translate("Principal", "Iniciar sesion", None))
        self.actionCerrar_sesion.setText(_translate("Principal", "Cerrar sesion", None))
        self.aConfigBd.setText(_translate("Principal", "Configurador de BD", None))
        self.actionGuardarcompra.setText(_translate("Principal", "Guardar como compra", None))
        self.actionGuardarcompra.setShortcut(_translate("Principal", "Ctrl+F5", None))
        self.actionAbrir_compra.setText(_translate("Principal", "Abrir compra", None))
        self.actionAbrir_compra.setShortcut(_translate("Principal", "Ctrl+Shift+A", None))
        self.actionNueva_compra.setText(_translate("Principal", "Nueva compra", None))
        self.actionNueva_compra.setShortcut(_translate("Principal", "Ctrl+Shift+N", None))
        self.actionSwap.setText(_translate("Principal", "Intecambiar productos", None))
        self.action.setText(_translate("Principal", "Respaldos", None))
        self.actionAbrir_venta_extemporanea.setText(_translate("Principal", "Abrir venta archivada", None))
        self.actionReimprimir_archivada.setText(_translate("Principal", "Reimprimir archivada", None))

import icons_rc
