# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/modulos/ui_reportes.ui'
#
# Created: Thu May 23 02:45:29 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(793, 544)
        self.verticalLayout_5 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.topReportes = QtGui.QWidget(Form)
        self.topReportes.setObjectName(_fromUtf8("topReportes"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.topReportes)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitter = QtGui.QSplitter(self.topReportes)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.titulo = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo.sizePolicy().hasHeightForWidth())
        self.titulo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setMargin(7)
        self.titulo.setIndent(8)
        self.titulo.setObjectName(_fromUtf8("titulo"))
        self.verticalLayout_3.addWidget(self.titulo)
        self.widget = QtGui.QWidget(self.layoutWidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_17 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.deFrom = QtGui.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deFrom.setFont(font)
        self.deFrom.setAlignment(QtCore.Qt.AlignCenter)
        self.deFrom.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.deFrom.setAccelerated(True)
        self.deFrom.setCalendarPopup(True)
        self.deFrom.setObjectName(_fromUtf8("deFrom"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.deFrom)
        self.label_4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.deTo = QtGui.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deTo.setFont(font)
        self.deTo.setAlignment(QtCore.Qt.AlignCenter)
        self.deTo.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.deTo.setAccelerated(True)
        self.deTo.setCalendarPopup(True)
        self.deTo.setObjectName(_fromUtf8("deTo"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.deTo)
        self.label_8 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.cbListas = QtGui.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbListas.setFont(font)
        self.cbListas.setObjectName(_fromUtf8("cbListas"))
        self.cbListas.addItem(_fromUtf8(""))
        self.cbListas.addItem(_fromUtf8(""))
        self.cbListas.addItem(_fromUtf8(""))
        self.cbListas.addItem(_fromUtf8(""))
        self.cbListas.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbListas)
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.cbCaja = QtGui.QComboBox(self.widget)
        self.cbCaja.setObjectName(_fromUtf8("cbCaja"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cbCaja)
        self.pbListaVentas = QtGui.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pbListaVentas.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbListaVentas.setIcon(icon)
        self.pbListaVentas.setIconSize(QtCore.QSize(18, 18))
        self.pbListaVentas.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pbListaVentas.setObjectName(_fromUtf8("pbListaVentas"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.pbListaVentas)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.verticalLayout_3.addWidget(self.widget)
        self.frame = QtGui.QFrame(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet(_fromUtf8(".QFrame{\n"
"border: 1.2px solid #999;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));}\n"
"QToolButton::hover{\n"
"    background-color:rgba(133, 217, 255, 100);\n"
"}\n"
"QToolButton::pressed{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(239, 239, 239, 27), stop:1 rgba(68, 68, 68, 205));\n"
"}\n"
"QToolButton, QLabel{padding:2 4 2 4; color:#555;border:0;}\n"
" \n"
""))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tbListar = QtGui.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbListar.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbListar.setIcon(icon1)
        self.tbListar.setIconSize(QtCore.QSize(18, 18))
        self.tbListar.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.tbListar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbListar.setAutoRaise(True)
        self.tbListar.setObjectName(_fromUtf8("tbListar"))
        self.horizontalLayout_3.addWidget(self.tbListar)
        self.tbDetallar = QtGui.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDetallar.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/clipboard.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbDetallar.setIcon(icon2)
        self.tbDetallar.setIconSize(QtCore.QSize(18, 18))
        self.tbDetallar.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.tbDetallar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbDetallar.setAutoRaise(True)
        self.tbDetallar.setObjectName(_fromUtf8("tbDetallar"))
        self.horizontalLayout_3.addWidget(self.tbDetallar)
        self.tbGraficas = QtGui.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbGraficas.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/stats_bars.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbGraficas.setIcon(icon3)
        self.tbGraficas.setIconSize(QtCore.QSize(18, 18))
        self.tbGraficas.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbGraficas.setAutoRaise(True)
        self.tbGraficas.setObjectName(_fromUtf8("tbGraficas"))
        self.horizontalLayout_3.addWidget(self.tbGraficas)
        self.bCorteT = QtGui.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bCorteT.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/scissors.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bCorteT.setIcon(icon4)
        self.bCorteT.setIconSize(QtCore.QSize(18, 18))
        self.bCorteT.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bCorteT.setObjectName(_fromUtf8("bCorteT"))
        self.horizontalLayout_3.addWidget(self.bCorteT)
        self.verticalLayout_3.addWidget(self.frame)
        self.teDetalles = QtGui.QTextEdit(self.layoutWidget)
        self.teDetalles.setMaximumSize(QtCore.QSize(320, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Sans"))
        font.setPointSize(10)
        self.teDetalles.setFont(font)
        self.teDetalles.setObjectName(_fromUtf8("teDetalles"))
        self.verticalLayout_3.addWidget(self.teDetalles)
        self.stackReportes = QtGui.QStackedWidget(self.splitter)
        self.stackReportes.setObjectName(_fromUtf8("stackReportes"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gToolbar_4 = QtGui.QWidget(self.page_5)
        self.gToolbar_4.setStyleSheet(_fromUtf8(".QWidget{background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(228, 228, 228, 255));}"))
        self.gToolbar_4.setObjectName(_fromUtf8("gToolbar_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.gToolbar_4)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tbLExportar = QtGui.QToolButton(self.gToolbar_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbLExportar.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/spreadsheet.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbLExportar.setIcon(icon5)
        self.tbLExportar.setIconSize(QtCore.QSize(18, 18))
        self.tbLExportar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbLExportar.setAutoRaise(True)
        self.tbLExportar.setObjectName(_fromUtf8("tbLExportar"))
        self.horizontalLayout_9.addWidget(self.tbLExportar)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout.addWidget(self.gToolbar_4)
        self.tVentas = QtGui.QTableView(self.page_5)
        self.tVentas.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tVentas.setAlternatingRowColors(True)
        self.tVentas.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tVentas.setSortingEnabled(True)
        self.tVentas.setObjectName(_fromUtf8("tVentas"))
        self.tVentas.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tVentas)
        self.stackReportes.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_6)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gToolbar_3 = QtGui.QWidget(self.page_6)
        self.gToolbar_3.setStyleSheet(_fromUtf8(".QWidget{background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(228, 228, 228, 255));}"))
        self.gToolbar_3.setObjectName(_fromUtf8("gToolbar_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.gToolbar_3)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.tbGColorear = QtGui.QToolButton(self.gToolbar_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbGColorear.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/history.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbGColorear.setIcon(icon6)
        self.tbGColorear.setIconSize(QtCore.QSize(18, 18))
        self.tbGColorear.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbGColorear.setAutoRaise(True)
        self.tbGColorear.setObjectName(_fromUtf8("tbGColorear"))
        self.horizontalLayout_8.addWidget(self.tbGColorear)
        self.tbGGuardar = QtGui.QToolButton(self.gToolbar_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbGGuardar.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/diskette.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbGGuardar.setIcon(icon7)
        self.tbGGuardar.setIconSize(QtCore.QSize(18, 18))
        self.tbGGuardar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbGGuardar.setAutoRaise(True)
        self.tbGGuardar.setObjectName(_fromUtf8("tbGGuardar"))
        self.horizontalLayout_8.addWidget(self.tbGGuardar)
        self.tbGImprimir = QtGui.QToolButton(self.gToolbar_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbGImprimir.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbGImprimir.setIcon(icon8)
        self.tbGImprimir.setIconSize(QtCore.QSize(18, 18))
        self.tbGImprimir.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbGImprimir.setAutoRaise(True)
        self.tbGImprimir.setObjectName(_fromUtf8("tbGImprimir"))
        self.horizontalLayout_8.addWidget(self.tbGImprimir)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.gToolbar_3)
        self.grafica = QtGui.QGraphicsView(self.page_6)
        self.grafica.setRenderHints(QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.TextAntialiasing)
        self.grafica.setObjectName(_fromUtf8("grafica"))
        self.verticalLayout_2.addWidget(self.grafica)
        self.stackReportes.addWidget(self.page_6)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.scrollArea = QtGui.QScrollArea(self.page_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 437, 538))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gToolbar_2 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.gToolbar_2.setStyleSheet(_fromUtf8(".QWidget{background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(228, 228, 228, 255));}"))
        self.gToolbar_2.setObjectName(_fromUtf8("gToolbar_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.gToolbar_2)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tbRExportar = QtGui.QToolButton(self.gToolbar_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbRExportar.setFont(font)
        self.tbRExportar.setIcon(icon5)
        self.tbRExportar.setIconSize(QtCore.QSize(18, 18))
        self.tbRExportar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbRExportar.setAutoRaise(True)
        self.tbRExportar.setObjectName(_fromUtf8("tbRExportar"))
        self.horizontalLayout_7.addWidget(self.tbRExportar)
        self.tbImprimir = QtGui.QToolButton(self.gToolbar_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbImprimir.setFont(font)
        self.tbImprimir.setIcon(icon8)
        self.tbImprimir.setIconSize(QtCore.QSize(18, 18))
        self.tbImprimir.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.tbImprimir.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbImprimir.setAutoRaise(True)
        self.tbImprimir.setObjectName(_fromUtf8("tbImprimir"))
        self.horizontalLayout_7.addWidget(self.tbImprimir)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_8.addWidget(self.gToolbar_2)
        self.teResumen = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.teResumen.setMaximumSize(QtCore.QSize(700, 16777215))
        self.teResumen.setReadOnly(True)
        self.teResumen.setObjectName(_fromUtf8("teResumen"))
        self.verticalLayout_8.addWidget(self.teResumen)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.stackReportes.addWidget(self.page_3)
        self.verticalLayout_4.addWidget(self.splitter)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addWidget(self.topReportes)

        self.retranslateUi(Form)
        self.stackReportes.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.titulo.setText(_translate("Form", "Reportes de ventas:", None))
        self.label_17.setText(_translate("Form", "Desde:", None))
        self.deFrom.setDisplayFormat(_translate("Form", "dd MMM yyyy", None))
        self.label_4.setText(_translate("Form", "Hasta:", None))
        self.deTo.setDisplayFormat(_translate("Form", "dd MMM yyyy", None))
        self.label_8.setText(_translate("Form", "Filtrar formato:", None))
        self.cbListas.setItemText(0, _translate("Form", "Ventas", None))
        self.cbListas.setItemText(1, _translate("Form", "Compras", None))
        self.cbListas.setItemText(2, _translate("Form", "Gastos", None))
        self.cbListas.setItemText(3, _translate("Form", "Retiros", None))
        self.cbListas.setItemText(4, _translate("Form", "Depositos", None))
        self.label.setText(_translate("Form", "Filtrar caja:", None))
        self.pbListaVentas.setText(_translate("Form", "Actualizar datos", None))
        self.tbListar.setText(_translate("Form", "Listar", None))
        self.tbDetallar.setText(_translate("Form", "Detallar", None))
        self.tbGraficas.setText(_translate("Form", "Graficar", None))
        self.bCorteT.setToolTip(_translate("Form", "Realizar corte de ventas.", None))
        self.bCorteT.setText(_translate("Form", "Corte", None))
        self.teDetalles.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-weight:600;\">Tabla general de ventas</span></p>\n"
"<table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" width=\"100%\" cellspacing=\"4\" cellpadding=\"0\">\n"
"<tr>\n"
"<td>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-weight:600;\">Concepto</span></p></td>\n"
"<td>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-weight:600;\">Monto</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">Ventas realizadas</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">$</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">Ventas cobradas</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">$</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">Facturas</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">$</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">Notas</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">$</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">En efectivo</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">$</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">En credito</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">$</span></p></td></tr></table></body></html>", None))
        self.tbLExportar.setText(_translate("Form", "Exportar", None))
        self.tbGColorear.setText(_translate("Form", "Cambiar color", None))
        self.tbGGuardar.setText(_translate("Form", "Guardar", None))
        self.tbGImprimir.setText(_translate("Form", "Imprimir", None))
        self.tbRExportar.setText(_translate("Form", "Exportar a xls", None))
        self.tbImprimir.setText(_translate("Form", "Imprimir", None))

import icons_rc
