# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dave/Dropbox/Pyventa/pyventa-2.3/qt/dl_scliente.ui'
#
# Created: Sun Mar 17 00:07:16 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Seleccion(object):
    def setupUi(self, Seleccion):
        Seleccion.setObjectName("Seleccion")
        Seleccion.resize(450, 553)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/messenger.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Seleccion.setWindowIcon(icon)
        Seleccion.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Seleccion)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top = QtWidgets.QWidget(Seleccion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top.sizePolicy().hasHeightForWidth())
        self.top.setSizePolicy(sizePolicy)
        self.top.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top.setObjectName("top")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout_14.setContentsMargins(2, 5, 2, 5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_4 = QtWidgets.QLabel(self.top)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_14.addWidget(self.label_4)
        self.fLine = QtWidgets.QFrame(self.top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fLine.sizePolicy().hasHeightForWidth())
        self.fLine.setSizePolicy(sizePolicy)
        self.fLine.setStyleSheet(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QLineEdit{background:transparent; border:0px; padding:3px}")
        self.fLine.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fLine.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fLine.setObjectName("fLine")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.fLine)
        self.horizontalLayout_51.setSpacing(0)
        self.horizontalLayout_51.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.texto = QtWidgets.QLineEdit(self.fLine)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.texto.sizePolicy().hasHeightForWidth())
        self.texto.setSizePolicy(sizePolicy)
        self.texto.setObjectName("texto")
        self.horizontalLayout_51.addWidget(self.texto)
        self.bbuscar = QtWidgets.QToolButton(self.fLine)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.bbuscar.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/zoom.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bbuscar.setIcon(icon1)
        self.bbuscar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bbuscar.setObjectName("bbuscar")
        self.horizontalLayout_51.addWidget(self.bbuscar)
        self.horizontalLayout_14.addWidget(self.fLine)
        self.verticalLayout.addWidget(self.top)
        self.tabla = QtWidgets.QTableWidget(Seleccion)
        self.tabla.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tabla.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(3)
        self.tabla.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla.setHorizontalHeaderItem(2, item)
        self.tabla.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tabla)

        self.retranslateUi(Seleccion)
        QtCore.QMetaObject.connectSlotsByName(Seleccion)

    def retranslateUi(self, Seleccion):
        Seleccion.setWindowTitle(QtCore.QCoreApplication.translate("Seleccion", "Seleccione el cliente"))
        Seleccion.setWindowFilePath(QtCore.QCoreApplication.translate("Seleccion", "Qt::Popup"))
        self.label_4.setStyleSheet(QtCore.QCoreApplication.translate("Seleccion", "background:none"))
        self.label_4.setText(QtCore.QCoreApplication.translate("Seleccion", "Seleccionar cliente"))
        self.bbuscar.setText(QtCore.QCoreApplication.translate("Seleccion", "Buscar"))
        item = self.tabla.horizontalHeaderItem(0)
        item.setText(QtCore.QCoreApplication.translate("Seleccion", "Id"))
        item = self.tabla.horizontalHeaderItem(1)
        item.setText(QtCore.QCoreApplication.translate("Seleccion", "Nombre o Razon Social"))
        item = self.tabla.horizontalHeaderItem(2)
        item.setText(QtCore.QCoreApplication.translate("Seleccion", "RFC"))
# 
import icons_rc
  # TODO: regenerate with pyrcc6