# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui_agregar_gasto.ui'
#
# Created: Mon Jun 18 01:08:18 2012
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(498, 184)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../usr/share/pyventa/images/32/pyventa-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));")
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbinfo = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbinfo.sizePolicy().hasHeightForWidth())
        self.lbinfo.setSizePolicy(sizePolicy)
        self.lbinfo.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lbinfo.setText("")
        self.lbinfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbinfo.setWordWrap(True)
        self.lbinfo.setObjectName("lbinfo")
        self.verticalLayout.addWidget(self.lbinfo)
        self.frame_4 = QtGui.QFrame(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("background-color: rgba(0,0,0,0);border-radius:5px;")
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_2 = QtGui.QFormLayout(self.frame_4)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.dsbCantidad = QtGui.QDoubleSpinBox(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbCantidad.sizePolicy().hasHeightForWidth())
        self.dsbCantidad.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.dsbCantidad.setFont(font)
        self.dsbCantidad.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(41, 41, 41, 255), stop:0.118182 rgba(255, 255, 255, 255), stop:0.281818 rgba(255, 255, 255, 255), stop:0.686364 rgba(250, 249, 225, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:1px solid #888; border-radius:5px; padding:4px;")
        self.dsbCantidad.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbCantidad.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dsbCantidad.setMaximum(99999.99)
        self.dsbCantidad.setObjectName("dsbCantidad")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.dsbCantidad)
        self.leConcepto = QtGui.QLineEdit(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.leConcepto.setFont(font)
        self.leConcepto.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(41, 41, 41, 255), stop:0.118182 rgba(255, 255, 255, 255), stop:0.281818 rgba(255, 255, 255, 255), stop:0.686364 rgba(250, 249, 225, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border:1px solid #888; border-radius:5px; padding:4px;")
        self.leConcepto.setAlignment(QtCore.Qt.AlignCenter)
        self.leConcepto.setObjectName("leConcepto")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.leConcepto)
        self.label_20 = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background:none;border:0;")
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_20)
        self.label_19 = QtGui.QLabel(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background:none;border:0;")
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_19)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Dual_3 = QtGui.QSplitter(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dual_3.sizePolicy().hasHeightForWidth())
        self.Dual_3.setSizePolicy(sizePolicy)
        self.Dual_3.setStyleSheet("QSplitter{border-radius:4px;\n"
"border: 1.2px solid #999;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));}\n"
"QToolButton::hover{\n"
"    background-color:rgba(133, 217, 255, 100);\n"
"}\n"
"QToolButton::pressed{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(239, 239, 239, 27), stop:1 rgba(68, 68, 68, 205));\n"
"}\n"
"QToolButton{padding:4px}\n"
" \n"
"")
        self.Dual_3.setLineWidth(0)
        self.Dual_3.setMidLineWidth(1)
        self.Dual_3.setOrientation(QtCore.Qt.Horizontal)
        self.Dual_3.setHandleWidth(1)
        self.Dual_3.setObjectName("Dual_3")
        self.tbCancelar = QtGui.QToolButton(self.Dual_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbCancelar.sizePolicy().hasHeightForWidth())
        self.tbCancelar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.tbCancelar.setFont(font)
        self.tbCancelar.setStyleSheet(" border:0px;border-right:1px solid #999;border-radius:0;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../usr/share/pyventa/images/16/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbCancelar.setIcon(icon1)
        self.tbCancelar.setIconSize(QtCore.QSize(12, 16))
        self.tbCancelar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbCancelar.setObjectName("tbCancelar")
        self.tbDone = QtGui.QToolButton(self.Dual_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbDone.sizePolicy().hasHeightForWidth())
        self.tbDone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.tbDone.setFont(font)
        self.tbDone.setStyleSheet(" border:0px;\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../usr/share/pyventa/images/32/sub_black_accept.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbDone.setIcon(icon2)
        self.tbDone.setIconSize(QtCore.QSize(16, 16))
        self.tbDone.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbDone.setObjectName("tbDone")
        self.horizontalLayout.addWidget(self.Dual_3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Registrar salida de dinero", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Cantidad: $", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "Concepto:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCancelar.setText(QtGui.QApplication.translate("Form", "Cerrar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbDone.setText(QtGui.QApplication.translate("Form", "Registrar", None, QtGui.QApplication.UnicodeUTF8))

