# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/dialogos/ui_asistente_inventario.ui'
#
# Created: Tue Apr 30 15:53:06 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Asistente(object):
    def setupUi(self, Asistente):
        Asistente.setObjectName("Asistente")
        Asistente.resize(778, 589)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/wizard.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Asistente.setWindowIcon(icon)
        Asistente.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Asistente)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbStatus = QtWidgets.QLabel(Asistente)
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        self.lbStatus.setFont(font)
        self.lbStatus.setStyleSheet("background-color: rgb(52, 52, 52);color:#fff;padding:5px;")
        self.lbStatus.setObjectName("lbStatus")
        self.verticalLayout.addWidget(self.lbStatus)
        self.stack = QtWidgets.QStackedWidget(Asistente)
        self.stack.setObjectName("stack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tablaDeps = QtWidgets.QTableWidget(self.groupBox_4)
        self.tablaDeps.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tablaDeps.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tablaDeps.setAlternatingRowColors(True)
        self.tablaDeps.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.tablaDeps.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tablaDeps.setObjectName("tablaDeps")
        self.tablaDeps.setColumnCount(0)
        self.tablaDeps.setRowCount(0)
        self.tablaDeps.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tablaDeps)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background-color: rgb(244, 244, 244);")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../../../../../../usr/share/pyventa/images/png/64-box_open.png"))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.stack.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.page_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lsColumnas = QtWidgets.QListWidget(self.groupBox)
        self.lsColumnas.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lsColumnas.setMovement(QtWidgets.QListView.Free)
        self.lsColumnas.setObjectName("lsColumnas")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.Checked)
        self.lsColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.Checked)
        self.lsColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.PartiallyChecked)
        self.lsColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.Checked)
        self.lsColumnas.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.PartiallyChecked)
        self.lsColumnas.addItem(item)
        self.verticalLayout_3.addWidget(self.lsColumnas)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rbFam = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbFam.setStyleSheet("color:#333")
        self.rbFam.setChecked(True)
        self.rbFam.setObjectName("rbFam")
        self.verticalLayout_4.addWidget(self.rbFam)
        self.rbDeps = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbDeps.setStyleSheet("color:#333")
        self.rbDeps.setObjectName("rbDeps")
        self.verticalLayout_4.addWidget(self.rbDeps)
        self.rbRef = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbRef.setStyleSheet("color:#333")
        self.rbRef.setObjectName("rbRef")
        self.verticalLayout_4.addWidget(self.rbRef)
        self.rbDesc = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbDesc.setStyleSheet("color:#333")
        self.rbDesc.setObjectName("rbDesc")
        self.verticalLayout_4.addWidget(self.rbDesc)
        self.rbPrecio = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbPrecio.setStyleSheet("color:#333")
        self.rbPrecio.setObjectName("rbPrecio")
        self.verticalLayout_4.addWidget(self.rbPrecio)
        self.rbModif = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbModif.setStyleSheet("color:#333")
        self.rbModif.setObjectName("rbModif")
        self.verticalLayout_4.addWidget(self.rbModif)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.stack.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setIndent(7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.widget_4 = QtWidgets.QWidget(self.page_3)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_7 = QtWidgets.QFrame(self.widget_4)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 19))
        self.frame_7.setStyleSheet(".QFrame{background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(228, 228, 228, 255));}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.tbImprimir = QtWidgets.QToolButton(self.frame_7)
        self.tbImprimir.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/print.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbImprimir.setIcon(icon1)
        self.tbImprimir.setIconSize(QtCore.QSize(16, 16))
        self.tbImprimir.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbImprimir.setAutoRaise(True)
        self.tbImprimir.setObjectName("tbImprimir")
        self.horizontalLayout_8.addWidget(self.tbImprimir)
        self.toolButton_3 = QtWidgets.QToolButton(self.frame_7)
        self.toolButton_3.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../../usr/share/pyventa/images/32/tablaexcel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setIconSize(QtCore.QSize(16, 16))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_8.addWidget(self.toolButton_3)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.tablaProductos = QtWidgets.QTableWidget(self.widget_4)
        self.tablaProductos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tablaProductos.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tablaProductos.setAlternatingRowColors(True)
        self.tablaProductos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tablaProductos.setObjectName("tablaProductos")
        self.tablaProductos.setColumnCount(0)
        self.tablaProductos.setRowCount(0)
        self.tablaProductos.horizontalHeader().setStretchLastSection(True)
        self.tablaProductos.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.tablaProductos)
        self.verticalLayout_8.addWidget(self.widget_4)
        self.stack.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_7 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_13.addWidget(self.label_7)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet(".QGroupBox{background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(228, 228, 228, 255));\n"
"border:1px solid #777;\n"
"}")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_10.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_6 = QtWidgets.QFrame(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_6.setStyleSheet("border:1.3px solid #999; border-radius:5px; color:#555;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(41, 41, 41, 255), stop:0.05 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.leFiltro = QtWidgets.QLineEdit(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.leFiltro.setFont(font)
        self.leFiltro.setStyleSheet("border:0;background:white")
        self.leFiltro.setObjectName("leFiltro")
        self.horizontalLayout_6.addWidget(self.leFiltro)
        self.verticalLayout_10.addWidget(self.frame_6)
        self.tabla = QtWidgets.QTableView(self.groupBox_5)
        self.tabla.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tabla.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tabla.setSortingEnabled(True)
        self.tabla.setObjectName("tabla")
        self.tabla.horizontalHeader().setCascadingSectionResizes(True)
        self.tabla.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_10.addWidget(self.tabla)
        self.horizontalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet(".QGroupBox{background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(228, 228, 228, 255));\n"
"border:1px solid #777;\n"
"}")
        self.groupBox_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_5 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_5.setStyleSheet("border:0;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tbAntProd = QtWidgets.QToolButton(self.frame_5)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../../usr/share/pyventa/images/48/go-previous.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbAntProd.setIcon(icon3)
        self.tbAntProd.setIconSize(QtCore.QSize(100, 32))
        self.tbAntProd.setObjectName("tbAntProd")
        self.horizontalLayout_5.addWidget(self.tbAntProd)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.tbSigProd = QtWidgets.QToolButton(self.frame_5)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../../../usr/share/pyventa/images/48/go-next.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbSigProd.setIcon(icon4)
        self.tbSigProd.setIconSize(QtCore.QSize(100, 32))
        self.tbSigProd.setObjectName("tbSigProd")
        self.horizontalLayout_5.addWidget(self.tbSigProd)
        self.verticalLayout_9.addWidget(self.frame_5)
        self.lblProducto = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lblProducto.setFont(font)
        self.lblProducto.setObjectName("lblProducto")
        self.verticalLayout_9.addWidget(self.lblProducto)
        self.lbCProducto = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbCProducto.setFont(font)
        self.lbCProducto.setText("")
        self.lbCProducto.setWordWrap(True)
        self.lbCProducto.setObjectName("lbCProducto")
        self.verticalLayout_9.addWidget(self.lbCProducto)
        self.lbCPrecio = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbCPrecio.setFont(font)
        self.lbCPrecio.setObjectName("lbCPrecio")
        self.verticalLayout_9.addWidget(self.lbCPrecio)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.tbManual = QtWidgets.QCheckBox(self.groupBox_6)
        self.tbManual.setObjectName("tbManual")
        self.verticalLayout_9.addWidget(self.tbManual)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.leExistencias = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leExistencias.sizePolicy().hasHeightForWidth())
        self.leExistencias.setSizePolicy(sizePolicy)
        self.leExistencias.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.leExistencias.setFont(font)
        self.leExistencias.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.leExistencias.setObjectName("leExistencias")
        self.horizontalLayout_10.addWidget(self.leExistencias)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.tbSetStock = QtWidgets.QToolButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tbSetStock.setFont(font)
        self.tbSetStock.setStyleSheet("QToolButton, QAbstractButton{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(87, 159, 10, 255), stop:1 rgba(161, 210, 0, 255));\n"
"color:#222;\n"
"border-radius:4px;border:1px solid #777; padding:2 9 2 9;\n"
"}\n"
"QAbstractButton::pressed{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 66, 255, 255), stop:1 rgba(0, 107, 227, 255));\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/checkmark2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbSetStock.setIcon(icon5)
        self.tbSetStock.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbSetStock.setObjectName("tbSetStock")
        self.horizontalLayout_11.addWidget(self.tbSetStock)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_7.addWidget(self.groupBox_6)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.stack.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_12 = QtWidgets.QFrame(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setStyleSheet("QWidget{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(228, 228, 228, 255));\n"
"color:#555;border:0;}\n"
"QToolButton{ border:0px; background:none}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_13.setContentsMargins(2, 9, 2, 5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.toolButton_10 = QtWidgets.QToolButton(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.toolButton_10.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/spreadsheet.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_10.setIcon(icon6)
        self.toolButton_10.setIconSize(QtCore.QSize(18, 18))
        self.toolButton_10.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_10.setObjectName("toolButton_10")
        self.horizontalLayout_13.addWidget(self.toolButton_10)
        self.tbIncon = QtWidgets.QToolButton(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbIncon.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/list.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbIncon.setIcon(icon7)
        self.tbIncon.setIconSize(QtCore.QSize(18, 18))
        self.tbIncon.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbIncon.setAutoRaise(True)
        self.tbIncon.setObjectName("tbIncon")
        self.horizontalLayout_13.addWidget(self.tbIncon)
        self.tbImprimir_2 = QtWidgets.QToolButton(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbImprimir_2.setFont(font)
        self.tbImprimir_2.setIcon(icon1)
        self.tbImprimir_2.setIconSize(QtCore.QSize(18, 18))
        self.tbImprimir_2.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.tbImprimir_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbImprimir_2.setAutoRaise(True)
        self.tbImprimir_2.setObjectName("tbImprimir_2")
        self.horizontalLayout_13.addWidget(self.tbImprimir_2)
        self.verticalLayout_12.addWidget(self.frame_12)
        self.qteResumen = QtWidgets.QTextEdit(self.page_5)
        self.qteResumen.setStyleSheet("background:#FFF;")
        self.qteResumen.setReadOnly(True)
        self.qteResumen.setObjectName("qteResumen")
        self.verticalLayout_12.addWidget(self.qteResumen)
        self.stack.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_11 = QtWidgets.QFrame(self.page_6)
        self.frame_11.setStyleSheet("QWidget{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(228, 228, 228, 255));\n"
"color:#333;border:0;}\n"
"QToolButton{ border:0px; background:none}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_12.setContentsMargins(0, 5, 5, 5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem6)
        self.bCorteP = QtWidgets.QToolButton(self.frame_11)
        self.bCorteP.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bCorteP.sizePolicy().hasHeightForWidth())
        self.bCorteP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bCorteP.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/group.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bCorteP.setIcon(icon8)
        self.bCorteP.setIconSize(QtCore.QSize(24, 24))
        self.bCorteP.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bCorteP.setObjectName("bCorteP")
        self.horizontalLayout_12.addWidget(self.bCorteP)
        self.tbPrintInc = QtWidgets.QToolButton(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbPrintInc.setFont(font)
        self.tbPrintInc.setIcon(icon1)
        self.tbPrintInc.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbPrintInc.setObjectName("tbPrintInc")
        self.horizontalLayout_12.addWidget(self.tbPrintInc)
        self.verticalLayout_16.addWidget(self.frame_11)
        self.tvInconsistencias = QtWidgets.QTableView(self.page_6)
        self.tvInconsistencias.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tvInconsistencias.setAlternatingRowColors(True)
        self.tvInconsistencias.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tvInconsistencias.setSortingEnabled(True)
        self.tvInconsistencias.setObjectName("tvInconsistencias")
        self.verticalLayout_16.addWidget(self.tvInconsistencias)
        self.stack.addWidget(self.page_6)
        self.verticalLayout.addWidget(self.stack)
        self.frame = QtWidgets.QFrame(Asistente)
        self.frame.setStyleSheet(".QFrame{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(228, 228, 228, 255));\n"
"}\n"
"QToolButton, QAbstractButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));\n"
"border-radius:4px;border:1px solid #777; padding:2 9 2 9;color:#333;\n"
"}\n"
"QAbstractButton::pressed{\n"
"color:#fff;\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 66, 255, 255), stop:1 rgba(0, 107, 227, 255));\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbCancelar = QtWidgets.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbCancelar.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../../../../../../usr/share/pyventa/images/32/Delete-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbCancelar.setIcon(icon9)
        self.tbCancelar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbCancelar.setObjectName("tbCancelar")
        self.horizontalLayout.addWidget(self.tbCancelar)
        spacerItem7 = QtWidgets.QSpacerItem(341, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.tbAtras = QtWidgets.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbAtras.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../../../../../../usr/share/pyventa/images/32/left-green.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbAtras.setIcon(icon10)
        self.tbAtras.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbAtras.setObjectName("tbAtras")
        self.horizontalLayout.addWidget(self.tbAtras)
        self.tbAdelante = QtWidgets.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tbAdelante.setFont(font)
        self.tbAdelante.setStyleSheet("QToolButton, QAbstractButton{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(10, 125, 159, 255), stop:1 rgba(0, 188, 255, 255));color:#fff;\n"
"border-radius:4px;border:1px solid #777; padding:2 9 2 9;\n"
"}\n"
"QAbstractButton::pressed{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 66, 255, 255), stop:1 rgba(0, 107, 227, 255));\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../../../../../../usr/share/pyventa/images/32/right-green.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbAdelante.setIcon(icon11)
        self.tbAdelante.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbAdelante.setObjectName("tbAdelante")
        self.horizontalLayout.addWidget(self.tbAdelante)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Asistente)
        self.stack.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Asistente)

    def retranslateUi(self, Asistente):
        Asistente.setWindowTitle(QtCore.QCoreApplication.translate("Asistente", "Asistente de inventarios"))
        self.lbStatus.setText(QtCore.QCoreApplication.translate("Asistente", "Preparacion de la base de datos 1 de 6"))
        self.groupBox_4.setTitle(QtCore.QCoreApplication.translate("Asistente", "Seleccione los departamentos que participaran en el inventario."))
        self.label.setText(QtCore.QCoreApplication.translate("Asistente", "Consideraciones previas."))
        self.label_2.setText(QtCore.QCoreApplication.translate("Asistente", "Una vez seleccionados los departamentos se levantara un candado para evitar cualquier conflicto con las cantidades. Este bloqueo quedara liberado una vez que se de por terminado el inventario y se haya confirmado por el auditor y el responsable o cuando se cancele el inventario antes del comenzar el conteo. "))
        self.label_4.setText(QtWidgets.QApplication.translate("Asistente", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:600;\">Formato de la lista de articulos que estaran participando en el inventario.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Personalice la vista y el orden en que se mostraran los productos ya que este orden se mantendra para el conteo asistido y la cantidad de columnas que apareceran en la impresion del listado de productos, es recomendable que escoga aquellas columnas que sean realmente necesarias.</span></p></body></html>", None, QtWidgets.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtCore.QCoreApplication.translate("Asistente", "Columnas."))
        __sortingEnabled = self.lsColumnas.isSortingEnabled()
        self.lsColumnas.setSortingEnabled(False)
        item = self.lsColumnas.item(0)
        item.setText(QtCore.QCoreApplication.translate("Asistente", "Referencia"))
        item = self.lsColumnas.item(1)
        item.setText(QtCore.QCoreApplication.translate("Asistente", "Descripcion"))
        item = self.lsColumnas.item(2)
        item.setText(QtCore.QCoreApplication.translate("Asistente", "Costo"))
        item = self.lsColumnas.item(3)
        item.setText(QtCore.QCoreApplication.translate("Asistente", "Precio"))
        item = self.lsColumnas.item(4)
        item.setText(QtCore.QCoreApplication.translate("Asistente", "Stock logico"))
        self.lsColumnas.setSortingEnabled(__sortingEnabled)
        self.groupBox_2.setTitle(QtCore.QCoreApplication.translate("Asistente", "Ordenar  articulos"))
        self.rbFam.setText(QtCore.QCoreApplication.translate("Asistente", "Por familias"))
        self.rbDeps.setText(QtCore.QCoreApplication.translate("Asistente", "Por departamento"))
        self.rbRef.setText(QtCore.QCoreApplication.translate("Asistente", "Por referencia"))
        self.rbDesc.setText(QtCore.QCoreApplication.translate("Asistente", "Por descripcion"))
        self.rbPrecio.setText(QtCore.QCoreApplication.translate("Asistente", "Por precio"))
        self.rbModif.setText(QtCore.QCoreApplication.translate("Asistente", "Por ultima modificacion"))
        self.label_6.setText(QtWidgets.QApplication.translate("Asistente", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:600;\">Lista de productos a contar.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9;\">Esta es la lista de productos que se contabilizaran, dependiendo de su modo de conteo, usted puede imprimir toda la lista para llenarla manualmente y luego pasar los datos con el conteo asistido o puede exportarla como una hoja de calculo, llenarla y despues importarla para el vaciado de datos.</span></p></body></html>", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tbImprimir.setText(QtCore.QCoreApplication.translate("Asistente", "Imprimir lista"))
        self.toolButton_3.setText(QtCore.QCoreApplication.translate("Asistente", "Exportar lista"))
        self.label_7.setText(QtWidgets.QApplication.translate("Asistente", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:600;\">Metodo de conteo</span></p>\n"
"<p align=\"justify\" style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Seleccione el modo en que desea contar, este puede ser de manera asistida que le pregunta la existencia  producto a producto de acuerdo a al orden establecido, y el modo manual que permite establecer la existencias seleccionando el producto.</p></body></html>", None, QtWidgets.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtCore.QCoreApplication.translate("Asistente", "Conteo Manual"))
        self.leFiltro.setToolTip(QtCore.QCoreApplication.translate("Asistente", "Busque por descripcion,  referencia o codigo de barras el articulo"))
        self.tabla.setToolTip(QtCore.QCoreApplication.translate("Asistente", "Haga doble click para establecer las existencias de ese articulo."))
        self.groupBox_6.setTitle(QtCore.QCoreApplication.translate("Asistente", "Conteo asistido"))
        self.tbAntProd.setToolTip(QtCore.QCoreApplication.translate("Asistente", "Pasar al anterior"))
        self.tbAntProd.setText(QtCore.QCoreApplication.translate("Asistente", "Anterior"))
        self.tbAntProd.setShortcut(QtCore.QCoreApplication.translate("Asistente", "Alt+Left"))
        self.tbSigProd.setToolTip(QtCore.QCoreApplication.translate("Asistente", "Pasar al siguiente"))
        self.tbSigProd.setText(QtCore.QCoreApplication.translate("Asistente", "Siguiente"))
        self.tbSigProd.setShortcut(QtCore.QCoreApplication.translate("Asistente", "Alt+Right"))
        self.lblProducto.setText(QtCore.QCoreApplication.translate("Asistente", "Producto:"))
        self.lbCPrecio.setText(QtWidgets.QApplication.translate("Asistente", "Precio:\n"
"", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tbManual.setText(QtCore.QCoreApplication.translate("Asistente", "Conteo Manual"))
        self.tbManual.setShortcut(QtCore.QCoreApplication.translate("Asistente", "Ins"))
        self.label_10.setText(QtCore.QCoreApplication.translate("Asistente", "Existencias fisicas:"))
        self.tbSetStock.setToolTip(QtCore.QCoreApplication.translate("Asistente", "<h4>Contrl+G</h4>Establece la cantidad de existencias fisicas en el producto seleccionado."))
        self.tbSetStock.setText(QtCore.QCoreApplication.translate("Asistente", "Confirmar"))
        self.tbSetStock.setShortcut(QtCore.QCoreApplication.translate("Asistente", "Ctrl+G"))
        self.toolButton_10.setText(QtCore.QCoreApplication.translate("Asistente", "Exportar reporte"))
        self.tbIncon.setText(QtCore.QCoreApplication.translate("Asistente", "Ver inconsistencias"))
        self.tbImprimir_2.setText(QtCore.QCoreApplication.translate("Asistente", "Imprimir"))
        self.qteResumen.setHtml(QtWidgets.QApplication.translate("Asistente", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\n"
"<tr>\n"
"<td bgcolor=\"#eeeeee\">\n"
"<p style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Resumen de inventario</span><span style=\" font-family:\'Sans\'; font-size:10pt;\"><br /></span><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">$empresa</span></p></td>\n"
"<td bgcolor=\"#eeeeee\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\"><br /></span></p>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Fecha:  $fecha<br />Departamentos:  $deps</span></p></td></tr></table>\n"
"<hr />\n"
"<table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\">\n"
"<tr>\n"
"<td></td>\n"
"<td></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Total de articulos contabilizados: </span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">$nacontados</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Valor del inventario (costo): </span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">$invalor</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Articulos con inconsistencias: </span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">$naicon</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Balance de inconsistencias (costo): </span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">$baincon</span></p></td></tr></table></body></html>", None, QtWidgets.QApplication.UnicodeUTF8))
        self.bCorteP.setText(QtCore.QCoreApplication.translate("Asistente", "Agrupar"))
        self.tbPrintInc.setText(QtCore.QCoreApplication.translate("Asistente", "Imprimir"))
        self.tbCancelar.setText(QtCore.QCoreApplication.translate("Asistente", "Cancelar inventario"))
        self.tbAtras.setText(QtCore.QCoreApplication.translate("Asistente", "Retroceder"))
        self.tbAdelante.setText(QtCore.QCoreApplication.translate("Asistente", "Continuar"))
# 
import icons_rc
  # TODO: regenerate with pyrcc6