# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/dialogos/ui_cobrador.ui'
#
# Created: Sat May 11 15:46:29 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Cobrador(object):
    def setupUi(self, Cobrador):
        Cobrador.setObjectName("Cobrador")
        Cobrador.resize(668, 334)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/coin.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Cobrador.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Cobrador)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Cobrador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(14, 84, 175);color:#fff;")
        self.label.setMargin(4)
        self.label.setIndent(13)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.tabla = QtWidgets.QTableView(Cobrador)
        self.tabla.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tabla.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tabla.setObjectName("tabla")
        self.verticalLayout_2.addWidget(self.tabla)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.frame = QtWidgets.QFrame(Cobrador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet(".QFrame{background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(228, 228, 228, 255));}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.fLine_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fLine_2.sizePolicy().hasHeightForWidth())
        self.fLine_2.setSizePolicy(sizePolicy)
        self.fLine_2.setStyleSheet(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QLineEdit{background:transparent; border:0px; padding:3px}")
        self.fLine_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fLine_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fLine_2.setObjectName("fLine_2")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.fLine_2)
        self.horizontalLayout_52.setSpacing(0)
        self.horizontalLayout_52.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.leRecibo = QtWidgets.QLineEdit(self.fLine_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leRecibo.sizePolicy().hasHeightForWidth())
        self.leRecibo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.leRecibo.setFont(font)
        self.leRecibo.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.leRecibo.setObjectName("leRecibo")
        self.horizontalLayout_52.addWidget(self.leRecibo)
        self.gridLayout.addWidget(self.fLine_2, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.dsbTotal = QtWidgets.QDoubleSpinBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.dsbTotal.setFont(font)
        self.dsbTotal.setStyleSheet("background:transparent;")
        self.dsbTotal.setFrame(False)
        self.dsbTotal.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsbTotal.setReadOnly(True)
        self.dsbTotal.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dsbTotal.setAccelerated(True)
        self.dsbTotal.setMaximum(99999.99)
        self.dsbTotal.setObjectName("dsbTotal")
        self.gridLayout.addWidget(self.dsbTotal, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.wCambio = QtWidgets.QWidget(self.frame)
        self.wCambio.setStyleSheet("background-color: rgb(255, 195, 55);color:#222;")
        self.wCambio.setObjectName("wCambio")
        self.formLayout_2 = QtWidgets.QFormLayout(self.wCambio)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.wCambio)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dsbCambio = QtWidgets.QDoubleSpinBox(self.wCambio)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.dsbCambio.setFont(font)
        self.dsbCambio.setStyleSheet("background:transparent;")
        self.dsbCambio.setFrame(False)
        self.dsbCambio.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsbCambio.setReadOnly(True)
        self.dsbCambio.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dsbCambio.setAccelerated(True)
        self.dsbCambio.setMaximum(99999.99)
        self.dsbCambio.setObjectName("dsbCambio")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dsbCambio)
        self.verticalLayout.addWidget(self.wCambio)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.botonUnion = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonUnion.sizePolicy().hasHeightForWidth())
        self.botonUnion.setSizePolicy(sizePolicy)
        self.botonUnion.setStyleSheet("*{border-radius:8px;\n"
"border: 1.2px solid #999;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));}\n"
"QToolButton::hover,QPushButton::hover{\n"
"    background-color:rgba(133, 217, 255, 100);\n"
"}\n"
"QToolButton::pressed,QPushButton::pressed{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(239, 239, 239, 27), stop:1 rgba(68, 68, 68, 205));\n"
"}\n"
"QPushButton,QToolButton{padding:4px; background:transparent; border-radius:0;}\n"
" \n"
"")
        self.botonUnion.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.botonUnion.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.botonUnion.setObjectName("botonUnion")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.botonUnion)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pbCerrar = QtWidgets.QPushButton(self.botonUnion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCerrar.sizePolicy().hasHeightForWidth())
        self.pbCerrar.setSizePolicy(sizePolicy)
        self.pbCerrar.setStyleSheet(" border:0px;border-radius:0;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/cancel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbCerrar.setIcon(icon1)
        self.pbCerrar.setIconSize(QtCore.QSize(18, 18))
        self.pbCerrar.setAutoDefault(False)
        self.pbCerrar.setObjectName("pbCerrar")
        self.horizontalLayout_4.addWidget(self.pbCerrar)
        self.tbCobrar = QtWidgets.QPushButton(self.botonUnion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbCobrar.sizePolicy().hasHeightForWidth())
        self.tbCobrar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tbCobrar.setFont(font)
        self.tbCobrar.setStyleSheet(" border:0px;border-left:1px solid #999;  \n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/bill.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbCobrar.setIcon(icon2)
        self.tbCobrar.setIconSize(QtCore.QSize(18, 18))
        self.tbCobrar.setCheckable(False)
        self.tbCobrar.setChecked(False)
        self.tbCobrar.setDefault(True)
        self.tbCobrar.setObjectName("tbCobrar")
        self.horizontalLayout_4.addWidget(self.tbCobrar)
        self.verticalLayout.addWidget(self.botonUnion)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Cobrador)
        self.pbCerrar.clicked.connect(Cobrador.accept)
        QtCore.QMetaObject.connectSlotsByName(Cobrador)
        Cobrador.setTabOrder(self.leRecibo, self.tbCobrar)
        Cobrador.setTabOrder(self.tbCobrar, self.pbCerrar)
        Cobrador.setTabOrder(self.pbCerrar, self.tabla)
        Cobrador.setTabOrder(self.tabla, self.dsbCambio)
        Cobrador.setTabOrder(self.dsbCambio, self.dsbTotal)

    def retranslateUi(self, Cobrador):
        Cobrador.setWindowTitle(QtCore.QCoreApplication.translate("Cobrador", "Cobrar ventas"))
        self.label.setText(QtCore.QCoreApplication.translate("Cobrador", "Ventas a cobrar"))
        self.label_3.setText(QtCore.QCoreApplication.translate("Cobrador", "Recibido:"))
        self.leRecibo.setText(QtCore.QCoreApplication.translate("Cobrador", "0"))
        self.label_2.setText(QtCore.QCoreApplication.translate("Cobrador", "Total:"))
        self.dsbTotal.setPrefix(QtCore.QCoreApplication.translate("Cobrador", " $ "))
        self.label_4.setText(QtCore.QCoreApplication.translate("Cobrador", "Cambio:"))
        self.dsbCambio.setPrefix(QtCore.QCoreApplication.translate("Cobrador", " $ "))
        self.pbCerrar.setText(QtCore.QCoreApplication.translate("Cobrador", "Cerrar"))
        self.tbCobrar.setToolTip(QtCore.QCoreApplication.translate("Cobrador", "Cobrar ventas"))
        self.tbCobrar.setText(QtCore.QCoreApplication.translate("Cobrador", "Cobrar"))
# 
import icons_rc
  # TODO: regenerate with pyrcc6