# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/modulos/ui_config.ui'
#
# Created: Sat Jun  8 08:13:54 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(679, 616)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/gear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.titulo = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo.sizePolicy().hasHeightForWidth())
        self.titulo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setObjectName(_fromUtf8("titulo"))
        self.horizontalLayout_5.addWidget(self.titulo)
        self.tbSalir = QtGui.QToolButton(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/checkmark.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSalir.setIcon(icon1)
        self.tbSalir.setIconSize(QtCore.QSize(18, 18))
        self.tbSalir.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbSalir.setAutoRaise(True)
        self.tbSalir.setObjectName(_fromUtf8("tbSalir"))
        self.horizontalLayout_5.addWidget(self.tbSalir)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.stack = QtGui.QTabWidget(Form)
        self.stack.setMinimumSize(QtCore.QSize(0, 0))
        self.stack.setObjectName(_fromUtf8("stack"))
        self.stackPage3 = QtGui.QWidget()
        self.stackPage3.setObjectName(_fromUtf8("stackPage3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.stackPage3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pbEditar = QtGui.QPushButton(self.stackPage3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbEditar.sizePolicy().hasHeightForWidth())
        self.pbEditar.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/pencil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbEditar.setIcon(icon2)
        self.pbEditar.setObjectName(_fromUtf8("pbEditar"))
        self.horizontalLayout.addWidget(self.pbEditar)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gbBox = QtGui.QGroupBox(self.stackPage3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbBox.sizePolicy().hasHeightForWidth())
        self.gbBox.setSizePolicy(sizePolicy)
        self.gbBox.setCheckable(True)
        self.gbBox.setChecked(True)
        self.gbBox.setObjectName(_fromUtf8("gbBox"))
        self.formLayout_5 = QtGui.QFormLayout(self.gbBox)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.fLine_4 = QtGui.QFrame(self.gbBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fLine_4.sizePolicy().hasHeightForWidth())
        self.fLine_4.setSizePolicy(sizePolicy)
        self.fLine_4.setStyleSheet(_fromUtf8(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QDoubleSpinBox{background:transparent; border:0px; padding:3px}"))
        self.fLine_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fLine_4.setFrameShadow(QtGui.QFrame.Raised)
        self.fLine_4.setObjectName(_fromUtf8("fLine_4"))
        self.horizontalLayout_55 = QtGui.QHBoxLayout(self.fLine_4)
        self.horizontalLayout_55.setSpacing(0)
        self.horizontalLayout_55.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_55.setObjectName(_fromUtf8("horizontalLayout_55"))
        self.sbCaja = QtGui.QSpinBox(self.fLine_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCaja.sizePolicy().hasHeightForWidth())
        self.sbCaja.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sbCaja.setFont(font)
        self.sbCaja.setFrame(False)
        self.sbCaja.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbCaja.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.sbCaja.setObjectName(_fromUtf8("sbCaja"))
        self.horizontalLayout_55.addWidget(self.sbCaja)
        self.tbBuscarCaja = QtGui.QToolButton(self.fLine_4)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/zoom.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbBuscarCaja.setIcon(icon3)
        self.tbBuscarCaja.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbBuscarCaja.setObjectName(_fromUtf8("tbBuscarCaja"))
        self.horizontalLayout_55.addWidget(self.tbBuscarCaja)
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.fLine_4)
        self.label_8 = QtGui.QLabel(self.gbBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.chbRecibePagos = QtGui.QCheckBox(self.gbBox)
        self.chbRecibePagos.setObjectName(_fromUtf8("chbRecibePagos"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.chbRecibePagos)
        self.verticalLayout_4.addWidget(self.gbBox)
        self.groupBox_4 = QtGui.QGroupBox(self.stackPage3)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.cbEstilos = QtGui.QComboBox(self.groupBox_4)
        self.cbEstilos.setObjectName(_fromUtf8("cbEstilos"))
        self.gridLayout_4.addWidget(self.cbEstilos, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.tbRecargarEstilo = QtGui.QToolButton(self.groupBox_4)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbRecargarEstilo.setIcon(icon4)
        self.tbRecargarEstilo.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbRecargarEstilo.setAutoRaise(True)
        self.tbRecargarEstilo.setObjectName(_fromUtf8("tbRecargarEstilo"))
        self.gridLayout_4.addWidget(self.tbRecargarEstilo, 0, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/modulos/images/pyventa.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stack.addTab(self.stackPage3, icon5, _fromUtf8(""))
        self.stackPage2 = QtGui.QWidget()
        self.stackPage2.setObjectName(_fromUtf8("stackPage2"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.stackPage2)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.gempresa = QtGui.QGroupBox(self.stackPage2)
        self.gempresa.setAlignment(QtCore.Qt.AlignCenter)
        self.gempresa.setObjectName(_fromUtf8("gempresa"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.gempresa)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_37 = QtGui.QLabel(self.gempresa)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_37)
        self.lenombre = QtGui.QLineEdit(self.gempresa)
        self.lenombre.setObjectName(_fromUtf8("lenombre"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lenombre)
        self.label_20 = QtGui.QLabel(self.gempresa)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_20)
        self.fLine_3 = QtGui.QFrame(self.gempresa)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fLine_3.sizePolicy().hasHeightForWidth())
        self.fLine_3.setSizePolicy(sizePolicy)
        self.fLine_3.setStyleSheet(_fromUtf8(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QLineEdit{background:transparent; border:0px; padding:3px}"))
        self.fLine_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fLine_3.setFrameShadow(QtGui.QFrame.Raised)
        self.fLine_3.setObjectName(_fromUtf8("fLine_3"))
        self.horizontalLayout_54 = QtGui.QHBoxLayout(self.fLine_3)
        self.horizontalLayout_54.setSpacing(0)
        self.horizontalLayout_54.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_54.setObjectName(_fromUtf8("horizontalLayout_54"))
        self.leLogo = QtGui.QLineEdit(self.fLine_3)
        self.leLogo.setObjectName(_fromUtf8("leLogo"))
        self.horizontalLayout_54.addWidget(self.leLogo)
        self.tbLogo = QtGui.QToolButton(self.fLine_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tbLogo.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/pictures_folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbLogo.setIcon(icon6)
        self.tbLogo.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbLogo.setObjectName(_fromUtf8("tbLogo"))
        self.horizontalLayout_54.addWidget(self.tbLogo)
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.fLine_3)
        self.label_38 = QtGui.QLabel(self.gempresa)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_38)
        self.lerfc = QtGui.QLineEdit(self.gempresa)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lerfc.sizePolicy().hasHeightForWidth())
        self.lerfc.setSizePolicy(sizePolicy)
        self.lerfc.setMinimumSize(QtCore.QSize(230, 0))
        self.lerfc.setObjectName(_fromUtf8("lerfc"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lerfc)
        self.label_39 = QtGui.QLabel(self.gempresa)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_39)
        self.leslogan = QtGui.QLineEdit(self.gempresa)
        self.leslogan.setObjectName(_fromUtf8("leslogan"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.leslogan)
        self.label_40 = QtGui.QLabel(self.gempresa)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_40)
        self.ledir = QtGui.QLineEdit(self.gempresa)
        self.ledir.setObjectName(_fromUtf8("ledir"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.ledir)
        self.verticalLayout_17.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_42 = QtGui.QLabel(self.gempresa)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_42)
        self.leestado = QtGui.QLineEdit(self.gempresa)
        self.leestado.setMaximumSize(QtCore.QSize(160, 16777215))
        self.leestado.setObjectName(_fromUtf8("leestado"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.leestado)
        self.label_41 = QtGui.QLabel(self.gempresa)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_41)
        self.leciudad = QtGui.QLineEdit(self.gempresa)
        self.leciudad.setMaximumSize(QtCore.QSize(250, 16777215))
        self.leciudad.setObjectName(_fromUtf8("leciudad"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.leciudad)
        self.label_43 = QtGui.QLabel(self.gempresa)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_43)
        self.letel = QtGui.QLineEdit(self.gempresa)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letel.sizePolicy().hasHeightForWidth())
        self.letel.setSizePolicy(sizePolicy)
        self.letel.setObjectName(_fromUtf8("letel"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.letel)
        self.label_7 = QtGui.QLabel(self.gempresa)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lecp = QtGui.QLineEdit(self.gempresa)
        self.lecp.setAlignment(QtCore.Qt.AlignCenter)
        self.lecp.setObjectName(_fromUtf8("lecp"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.lecp)
        self.label_45 = QtGui.QLabel(self.gempresa)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_45)
        self.leweb = QtGui.QLineEdit(self.gempresa)
        self.leweb.setObjectName(_fromUtf8("leweb"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.FieldRole, self.leweb)
        self.label_44 = QtGui.QLabel(self.gempresa)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_44)
        self.lemail = QtGui.QLineEdit(self.gempresa)
        self.lemail.setObjectName(_fromUtf8("lemail"))
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.FieldRole, self.lemail)
        self.horizontalLayout_2.addLayout(self.formLayout_6)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_15 = QtGui.QLabel(self.gempresa)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_11.addWidget(self.label_15)
        self.scrollArea_2 = QtGui.QScrollArea(self.gempresa)
        self.scrollArea_2.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(255, 255, 255);background-color: qlineargradient(spread:pad, x1:0.995, y1:0, x2:1, y2:1, stop:0 rgba(218, 218, 218, 255), stop:0.427273 rgba(249, 249, 249, 255), stop:0.509091 rgba(251, 251, 251, 255), stop:1 rgba(226, 226, 226, 255));"))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 298, 169))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setMargin(0)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.lblLogo = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLogo.sizePolicy().hasHeightForWidth())
        self.lblLogo.setSizePolicy(sizePolicy)
        self.lblLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLogo.setObjectName(_fromUtf8("lblLogo"))
        self.verticalLayout_19.addWidget(self.lblLogo)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_11.addWidget(self.scrollArea_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_17.addLayout(self.horizontalLayout_2)
        self.brecargar = QtGui.QPushButton(self.gempresa)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brecargar.sizePolicy().hasHeightForWidth())
        self.brecargar.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/diskette.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brecargar.setIcon(icon7)
        self.brecargar.setObjectName(_fromUtf8("brecargar"))
        self.verticalLayout_17.addWidget(self.brecargar)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem1)
        self.verticalLayout_25.addWidget(self.gempresa)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/certificate-(2).png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stack.addTab(self.stackPage2, icon8, _fromUtf8(""))
        self.stackPage1 = QtGui.QWidget()
        self.stackPage1.setObjectName(_fromUtf8("stackPage1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.stackPage1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_4 = QtGui.QLabel(self.stackPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.widget = QtGui.QWidget(self.stackPage1)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.tserver = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tserver.sizePolicy().hasHeightForWidth())
        self.tserver.setSizePolicy(sizePolicy)
        self.tserver.setObjectName(_fromUtf8("tserver"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.tserver)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.tuser = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tuser.sizePolicy().hasHeightForWidth())
        self.tuser.setSizePolicy(sizePolicy)
        self.tuser.setText(_fromUtf8(""))
        self.tuser.setObjectName(_fromUtf8("tuser"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.tuser)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.tpass = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tpass.sizePolicy().hasHeightForWidth())
        self.tpass.setSizePolicy(sizePolicy)
        self.tpass.setEchoMode(QtGui.QLineEdit.Password)
        self.tpass.setObjectName(_fromUtf8("tpass"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.tpass)
        self.lbldb = QtGui.QLabel(self.widget)
        self.lbldb.setObjectName(_fromUtf8("lbldb"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbldb)
        self.tdb = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tdb.sizePolicy().hasHeightForWidth())
        self.tdb.setSizePolicy(sizePolicy)
        self.tdb.setObjectName(_fromUtf8("tdb"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.tdb)
        self.horizontalLayout_6.addLayout(self.formLayout_2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.bprobar = QtGui.QPushButton(self.widget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bprobar.setIcon(icon9)
        self.bprobar.setObjectName(_fromUtf8("bprobar"))
        self.gridLayout_6.addWidget(self.bprobar, 0, 0, 1, 1)
        self.bset = QtGui.QPushButton(self.widget)
        self.bset.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/checkmark2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bset.setIcon(icon10)
        self.bset.setObjectName(_fromUtf8("bset"))
        self.gridLayout_6.addWidget(self.bset, 1, 0, 1, 1)
        self.tbImportar = QtGui.QToolButton(self.widget)
        self.tbImportar.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbImportar.sizePolicy().hasHeightForWidth())
        self.tbImportar.setSizePolicy(sizePolicy)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/download2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbImportar.setIcon(icon11)
        self.tbImportar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbImportar.setObjectName(_fromUtf8("tbImportar"))
        self.gridLayout_6.addWidget(self.tbImportar, 0, 1, 1, 1)
        self.bcreate = QtGui.QPushButton(self.widget)
        self.bcreate.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/point.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bcreate.setIcon(icon12)
        self.bcreate.setObjectName(_fromUtf8("bcreate"))
        self.gridLayout_6.addWidget(self.bcreate, 1, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.display = QtGui.QTextBrowser(self.widget)
        self.display.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display.sizePolicy().hasHeightForWidth())
        self.display.setSizePolicy(sizePolicy)
        self.display.setObjectName(_fromUtf8("display"))
        self.verticalLayout_3.addWidget(self.display)
        self.verticalLayout_5.addWidget(self.widget)
        self.stack.addTab(self.stackPage1, icon9, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.dsbTicketTigger = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbTicketTigger.sizePolicy().hasHeightForWidth())
        self.dsbTicketTigger.setSizePolicy(sizePolicy)
        self.dsbTicketTigger.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbTicketTigger.setMaximum(9999.99)
        self.dsbTicketTigger.setObjectName(_fromUtf8("dsbTicketTigger"))
        self.gridLayout_3.addWidget(self.dsbTicketTigger, 0, 1, 1, 1)
        self.chbImprimirCopia = QtGui.QCheckBox(self.groupBox_3)
        self.chbImprimirCopia.setObjectName(_fromUtf8("chbImprimirCopia"))
        self.gridLayout_3.addWidget(self.chbImprimirCopia, 1, 0, 1, 1)
        self.dsbCopia = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbCopia.sizePolicy().hasHeightForWidth())
        self.dsbCopia.setSizePolicy(sizePolicy)
        self.dsbCopia.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbCopia.setMaximum(99999.99)
        self.dsbCopia.setObjectName(_fromUtf8("dsbCopia"))
        self.gridLayout_3.addWidget(self.dsbCopia, 1, 1, 1, 1)
        self.chbImprimirTicket = QtGui.QCheckBox(self.groupBox_3)
        self.chbImprimirTicket.setCheckable(True)
        self.chbImprimirTicket.setObjectName(_fromUtf8("chbImprimirTicket"))
        self.gridLayout_3.addWidget(self.chbImprimirTicket, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.cbpreview = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbpreview.sizePolicy().hasHeightForWidth())
        self.cbpreview.setSizePolicy(sizePolicy)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/paragraph_align_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cbpreview.setIcon(icon13)
        self.cbpreview.setObjectName(_fromUtf8("cbpreview"))
        self.verticalLayout_2.addWidget(self.cbpreview)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.ctPrinter = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctPrinter.sizePolicy().hasHeightForWidth())
        self.ctPrinter.setSizePolicy(sizePolicy)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ctPrinter.setIcon(icon14)
        self.ctPrinter.setObjectName(_fromUtf8("ctPrinter"))
        self.gridLayout.addWidget(self.ctPrinter, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 1, 0, 1, 1)
        self.cbPrinters = QtGui.QComboBox(self.groupBox_3)
        self.cbPrinters.setObjectName(_fromUtf8("cbPrinters"))
        self.gridLayout.addWidget(self.cbPrinters, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_5.addWidget(self.label_21, 0, 0, 1, 1)
        self.cbDrivers = QtGui.QComboBox(self.groupBox_3)
        self.cbDrivers.setObjectName(_fromUtf8("cbDrivers"))
        self.gridLayout_5.addWidget(self.cbDrivers, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.verticalLayout_18.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.fLine = QtGui.QFrame(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fLine.sizePolicy().hasHeightForWidth())
        self.fLine.setSizePolicy(sizePolicy)
        self.fLine.setStyleSheet(_fromUtf8(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QLineEdit{background:transparent; border:0px; padding:3px}"))
        self.fLine.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fLine.setFrameShadow(QtGui.QFrame.Raised)
        self.fLine.setObjectName(_fromUtf8("fLine"))
        self.horizontalLayout_51 = QtGui.QHBoxLayout(self.fLine)
        self.horizontalLayout_51.setSpacing(0)
        self.horizontalLayout_51.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.lbeProducto_5 = QtGui.QLabel(self.fLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbeProducto_5.setFont(font)
        self.lbeProducto_5.setText(_fromUtf8(""))
        self.lbeProducto_5.setObjectName(_fromUtf8("lbeProducto_5"))
        self.horizontalLayout_51.addWidget(self.lbeProducto_5)
        self.cbPath = QtGui.QToolButton(self.fLine)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cbPath.setFont(font)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/folder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cbPath.setIcon(icon15)
        self.cbPath.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.cbPath.setObjectName(_fromUtf8("cbPath"))
        self.horizontalLayout_51.addWidget(self.cbPath)
        self.verticalLayout_15.addWidget(self.fLine)
        self.pbfEditar = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbfEditar.sizePolicy().hasHeightForWidth())
        self.pbfEditar.setSizePolicy(sizePolicy)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/paragraph_justify.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbfEditar.setIcon(icon16)
        self.pbfEditar.setObjectName(_fromUtf8("pbfEditar"))
        self.verticalLayout_15.addWidget(self.pbfEditar)
        self.verticalLayout_18.addWidget(self.groupBox_5)
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.pbpEditar_ = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbpEditar_.sizePolicy().hasHeightForWidth())
        self.pbpEditar_.setSizePolicy(sizePolicy)
        self.pbpEditar_.setIcon(icon13)
        self.pbpEditar_.setObjectName(_fromUtf8("pbpEditar_"))
        self.verticalLayout_16.addWidget(self.pbpEditar_)
        self.verticalLayout_18.addWidget(self.groupBox_8)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.pbEditarCorte = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbEditarCorte.sizePolicy().hasHeightForWidth())
        self.pbEditarCorte.setSizePolicy(sizePolicy)
        self.pbEditarCorte.setIcon(icon13)
        self.pbEditarCorte.setObjectName(_fromUtf8("pbEditarCorte"))
        self.verticalLayout_20.addWidget(self.pbEditarCorte)
        self.verticalLayout_18.addWidget(self.groupBox)
        self.stack.addTab(self.tab, icon14, _fromUtf8(""))
        self.stackPage5 = QtGui.QWidget()
        self.stackPage5.setObjectName(_fromUtf8("stackPage5"))
        self.groupBox_2 = QtGui.QGroupBox(self.stackPage5)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 10, 601, 201))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.rlRestoreDB = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rlRestoreDB.sizePolicy().hasHeightForWidth())
        self.rlRestoreDB.setSizePolicy(sizePolicy)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/rotate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rlRestoreDB.setIcon(icon17)
        self.rlRestoreDB.setIconSize(QtCore.QSize(32, 32))
        self.rlRestoreDB.setFlat(True)
        self.rlRestoreDB.setObjectName(_fromUtf8("rlRestoreDB"))
        self.gridLayout_2.addWidget(self.rlRestoreDB, 2, 0, 1, 1)
        self.rlRestoreConf = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rlRestoreConf.sizePolicy().hasHeightForWidth())
        self.rlRestoreConf.setSizePolicy(sizePolicy)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/history.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rlRestoreConf.setIcon(icon18)
        self.rlRestoreConf.setIconSize(QtCore.QSize(32, 32))
        self.rlRestoreConf.setFlat(True)
        self.rlRestoreConf.setObjectName(_fromUtf8("rlRestoreConf"))
        self.gridLayout_2.addWidget(self.rlRestoreConf, 3, 0, 1, 1)
        self.rlBackup = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rlBackup.sizePolicy().hasHeightForWidth())
        self.rlBackup.setSizePolicy(sizePolicy)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/compress.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rlBackup.setIcon(icon19)
        self.rlBackup.setFlat(True)
        self.rlBackup.setObjectName(_fromUtf8("rlBackup"))
        self.gridLayout_2.addWidget(self.rlBackup, 0, 1, 1, 1)
        self.rlRestore = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rlRestore.sizePolicy().hasHeightForWidth())
        self.rlRestore.setSizePolicy(sizePolicy)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rlRestore.setIcon(icon20)
        self.rlRestore.setIconSize(QtCore.QSize(32, 32))
        self.rlRestore.setFlat(True)
        self.rlRestore.setObjectName(_fromUtf8("rlRestore"))
        self.gridLayout_2.addWidget(self.rlRestore, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.cpgrespaldo = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpgrespaldo.sizePolicy().hasHeightForWidth())
        self.cpgrespaldo.setSizePolicy(sizePolicy)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/upload2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cpgrespaldo.setIcon(icon21)
        self.cpgrespaldo.setFlat(True)
        self.cpgrespaldo.setObjectName(_fromUtf8("cpgrespaldo"))
        self.gridLayout_2.addWidget(self.cpgrespaldo, 1, 1, 1, 1)
        self.gbLocal = QtGui.QGroupBox(self.stackPage5)
        self.gbLocal.setGeometry(QtCore.QRect(20, 220, 611, 291))
        self.gbLocal.setObjectName(_fromUtf8("gbLocal"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.gbLocal)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.fLine_2 = QtGui.QFrame(self.gbLocal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fLine_2.sizePolicy().hasHeightForWidth())
        self.fLine_2.setSizePolicy(sizePolicy)
        self.fLine_2.setStyleSheet(_fromUtf8(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QLineEdit{background:transparent; border:0px; padding:3px}"))
        self.fLine_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fLine_2.setFrameShadow(QtGui.QFrame.Raised)
        self.fLine_2.setObjectName(_fromUtf8("fLine_2"))
        self.horizontalLayout_52 = QtGui.QHBoxLayout(self.fLine_2)
        self.horizontalLayout_52.setSpacing(0)
        self.horizontalLayout_52.setContentsMargins(0, 0, 4, 0)
        self.horizontalLayout_52.setObjectName(_fromUtf8("horizontalLayout_52"))
        self.label_16 = QtGui.QLabel(self.fLine_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_52.addWidget(self.label_16)
        self.rlPath = QtGui.QLabel(self.fLine_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rlPath.setFont(font)
        self.rlPath.setText(_fromUtf8(""))
        self.rlPath.setObjectName(_fromUtf8("rlPath"))
        self.horizontalLayout_52.addWidget(self.rlPath)
        self.clrExplorar = QtGui.QToolButton(self.fLine_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clrExplorar.setFont(font)
        self.clrExplorar.setIcon(icon15)
        self.clrExplorar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.clrExplorar.setObjectName(_fromUtf8("clrExplorar"))
        self.horizontalLayout_52.addWidget(self.clrExplorar)
        self.verticalLayout_9.addWidget(self.fLine_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_53 = QtGui.QLabel(self.gbLocal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.horizontalLayout_4.addWidget(self.label_53)
        self.rlPeriod = QtGui.QSpinBox(self.gbLocal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rlPeriod.sizePolicy().hasHeightForWidth())
        self.rlPeriod.setSizePolicy(sizePolicy)
        self.rlPeriod.setObjectName(_fromUtf8("rlPeriod"))
        self.horizontalLayout_4.addWidget(self.rlPeriod)
        self.label_17 = QtGui.QLabel(self.gbLocal)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_4.addWidget(self.label_17)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_51 = QtGui.QLabel(self.gbLocal)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_51)
        self.rsServer = QtGui.QLineEdit(self.gbLocal)
        self.rsServer.setObjectName(_fromUtf8("rsServer"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.rsServer)
        self.label_11 = QtGui.QLabel(self.gbLocal)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.rsUser = QtGui.QLineEdit(self.gbLocal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rsUser.sizePolicy().hasHeightForWidth())
        self.rsUser.setSizePolicy(sizePolicy)
        self.rsUser.setToolTip(_fromUtf8(""))
        self.rsUser.setObjectName(_fromUtf8("rsUser"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.rsUser)
        self.label_12 = QtGui.QLabel(self.gbLocal)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.rsPass = QtGui.QLineEdit(self.gbLocal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rsPass.sizePolicy().hasHeightForWidth())
        self.rsPass.setSizePolicy(sizePolicy)
        self.rsPass.setEchoMode(QtGui.QLineEdit.Password)
        self.rsPass.setObjectName(_fromUtf8("rsPass"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.rsPass)
        self.label_13 = QtGui.QLabel(self.gbLocal)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.rsPath = QtGui.QLineEdit(self.gbLocal)
        self.rsPath.setObjectName(_fromUtf8("rsPath"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.rsPath)
        self.verticalLayout_9.addLayout(self.formLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_50 = QtGui.QLabel(self.gbLocal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_3.addWidget(self.label_50)
        self.rsPeriod = QtGui.QSpinBox(self.gbLocal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rsPeriod.sizePolicy().hasHeightForWidth())
        self.rsPeriod.setSizePolicy(sizePolicy)
        self.rsPeriod.setObjectName(_fromUtf8("rsPeriod"))
        self.horizontalLayout_3.addWidget(self.rsPeriod)
        self.label_10 = QtGui.QLabel(self.gbLocal)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/redo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stack.addTab(self.stackPage5, icon22, _fromUtf8(""))
        self.verticalLayout.addWidget(self.stack)

        self.retranslateUi(Form)
        self.stack.setCurrentIndex(2)
        QtCore.QObject.connect(self.tbSalir, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Centro de configuraciones", None))
        self.titulo.setText(_translate("Form", "Centro de configuraciones.", None))
        self.tbSalir.setText(_translate("Form", "Guardar y salir", None))
        self.pbEditar.setText(_translate("Form", "Editar archivo de configuracion", None))
        self.gbBox.setTitle(_translate("Form", "Esta computadora es caja", None))
        self.tbBuscarCaja.setText(_translate("Form", "Ver cajas", None))
        self.label_8.setText(_translate("Form", "Numero de caja:", None))
        self.chbRecibePagos.setToolTip(_translate("Form", "Marque esta opcion si en este equipo se maneja el cobro de ventas.", None))
        self.chbRecibePagos.setText(_translate("Form", "Esta estacion recibe pagos", None))
        self.groupBox_4.setTitle(_translate("Form", "Apariencia", None))
        self.label_6.setText(_translate("Form", "Estilo visual:", None))
        self.tbRecargarEstilo.setText(_translate("Form", "Recargar", None))
        self.stack.setTabText(self.stack.indexOf(self.stackPage3), _translate("Form", "Estacion de trabajo", None))
        self.gempresa.setTitle(_translate("Form", "Datos de la Empresa", None))
        self.label_37.setText(_translate("Form", "Nombre", None))
        self.label_20.setText(_translate("Form", "Logo ", None))
        self.tbLogo.setText(_translate("Form", "Abrir imagen ...", None))
        self.label_38.setText(_translate("Form", "RFC", None))
        self.label_39.setText(_translate("Form", "Slogan", None))
        self.label_40.setText(_translate("Form", "Direccion", None))
        self.label_42.setText(_translate("Form", "Estado/Dep", None))
        self.label_41.setText(_translate("Form", "Ciudad", None))
        self.label_43.setText(_translate("Form", "Telefono", None))
        self.letel.setInputMask(_translate("Form", "(###) ### -####; ", None))
        self.label_7.setText(_translate("Form", "Codigo P.", None))
        self.lecp.setInputMask(_translate("Form", "#####; ", None))
        self.label_45.setText(_translate("Form", "Pagina Web", None))
        self.label_44.setText(_translate("Form", "E-mail", None))
        self.label_15.setText(_translate("Form", "Logo ", None))
        self.brecargar.setText(_translate("Form", "Guardar cambios", None))
        self.stack.setTabText(self.stack.indexOf(self.stackPage2), _translate("Form", "Empresa", None))
        self.label_4.setText(_translate("Form", "Base de datos", None))
        self.label.setText(_translate("Form", "Modifica los datos necesarios para poder conectarse a la base de datos de MySQL.", None))
        self.label_2.setText(_translate("Form", "Servidor: ", None))
        self.tserver.setText(_translate("Form", "localhost", None))
        self.label_3.setText(_translate("Form", "Usuario:  ", None))
        self.label_5.setText(_translate("Form", "Password", None))
        self.lbldb.setText(_translate("Form", "Base de datos ", None))
        self.tdb.setText(_translate("Form", "tpv", None))
        self.bprobar.setText(_translate("Form", "Conectar", None))
        self.bset.setText(_translate("Form", "Usar como\n"
"predeterminada", None))
        self.tbImportar.setText(_translate("Form", "Importar  base de datos", None))
        self.bcreate.setText(_translate("Form", "Crear nueva\n"
"base de datos", None))
        self.display.setStyleSheet(_translate("Form", "background-color: rgb(252, 252, 252);\n"
"border: 2px solid rgb(175, 175, 175);\n"
"border-radius:5px;\n"
"color:rgb(32, 158, 204);", None))
        self.stack.setTabText(self.stack.indexOf(self.stackPage1), _translate("Form", "Base datos", None))
        self.groupBox_3.setTitle(_translate("Form", "Recibo", None))
        self.dsbTicketTigger.setPrefix(_translate("Form", "$", None))
        self.chbImprimirCopia.setText(_translate("Form", "Imprimir copia de recibo con totales de venta mayores a:", None))
        self.chbImprimirTicket.setText(_translate("Form", "Imprimir recibo en ventas  con totales de venta mayores a:", None))
        self.cbpreview.setText(_translate("Form", "Editar el formato del recibo", None))
        self.label_14.setText(_translate("Form", "Seleccione la impresora para imprimir recibos:", None))
        self.ctPrinter.setText(_translate("Form", "Seleccionar impresora", None))
        self.label_18.setText(_translate("Form", "Solo para sistemas UNIX", None))
        self.label_19.setText(_translate("Form", "Driver ESC/POS para impresoras de tickets", None))
        self.label_21.setText(_translate("Form", "Seleccione el driver de su impresora :", None))
        self.groupBox_5.setTitle(_translate("Form", "Facturas", None))
        self.cbPath.setText(_translate("Form", "Cambiar carpeta ...", None))
        self.pbfEditar.setText(_translate("Form", "Configurar posiciones (Avanzado)", None))
        self.groupBox_8.setTitle(_translate("Form", "Presupuestos", None))
        self.pbpEditar_.setText(_translate("Form", "Editar plantilla de impresion", None))
        self.groupBox.setTitle(_translate("Form", "Reporte de ventas diarias", None))
        self.pbEditarCorte.setText(_translate("Form", "Editar formato de corte", None))
        self.stack.setTabText(self.stack.indexOf(self.tab), _translate("Form", "Impresion", None))
        self.groupBox_2.setTitle(_translate("Form", "Acciones principales.", None))
        self.rlRestoreDB.setText(_translate("Form", "Restaurar solo Base de Datos", None))
        self.rlRestoreConf.setText(_translate("Form", "Restaurar solo configuraciones", None))
        self.rlBackup.setText(_translate("Form", "Generar respaldo", None))
        self.rlRestore.setText(_translate("Form", "Restaurar respaldo completo", None))
        self.cpgrespaldo.setText(_translate("Form", "Generar y subir respaldo", None))
        self.gbLocal.setTitle(_translate("Form", "Configuraciones de respaldos", None))
        self.label_16.setText(_translate("Form", "Se guardan en:", None))
        self.clrExplorar.setText(_translate("Form", " ...", None))
        self.label_53.setText(_translate("Form", "Realizar respaldo automatico cada ", None))
        self.rlPeriod.setToolTip(_translate("Form", "Si de no desea utilizar esta opcion, dejela en 0", None))
        self.label_17.setText(_translate("Form", "dias", None))
        self.label_51.setText(_translate("Form", "Servidor ftp://", None))
        self.label_11.setText(_translate("Form", "Usuario", None))
        self.label_12.setText(_translate("Form", "Password", None))
        self.label_13.setText(_translate("Form", "Ruta", None))
        self.rsPath.setToolTip(_translate("Form", "Si desconoce la ruta en la que se guardaran, puede dejarlo vacio", None))
        self.label_50.setText(_translate("Form", "Realizar respaldo a internet cada ", None))
        self.rsPeriod.setToolTip(_translate("Form", "Frecuencia con la que se respaldara automaticamente, si se deja en \"0\" solo se hara respaldo cuando el administrador lo indique.", None))
        self.label_10.setText(_translate("Form", "dias", None))
        self.stack.setTabText(self.stack.indexOf(self.stackPage5), _translate("Form", "Respaldos", None))

import icons_rc
