# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui_cobro.ui'
#
# Created: Wed Mar 23 23:52:42 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(694, 567)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titulo = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo.sizePolicy().hasHeightForWidth())
        self.titulo.setSizePolicy(sizePolicy)
        self.titulo.setObjectName("titulo")
        self.verticalLayout_2.addWidget(self.titulo)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_28.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_28.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.twNotas = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twNotas.sizePolicy().hasHeightForWidth())
        self.twNotas.setSizePolicy(sizePolicy)
        self.twNotas.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.twNotas.setFont(font)
        self.twNotas.setAcceptDrops(True)
        self.twNotas.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.twNotas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.twNotas.setObjectName("twNotas")
        self.twNotas.setColumnCount(0)
        self.twNotas.setRowCount(0)
        self.twNotas.verticalHeader().setHighlightSections(False)
        self.verticalLayout_28.addWidget(self.twNotas)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.leNumero = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.leNumero.setFont(font)
        self.leNumero.setObjectName("leNumero")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leNumero)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ncactualizar = QtWidgets.QToolButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ncactualizar.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../usr/share/pyventa/images/32/Synchronize-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ncactualizar.setIcon(icon)
        self.ncactualizar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.ncactualizar.setObjectName("ncactualizar")
        self.horizontalLayout_2.addWidget(self.ncactualizar)
        self.cbTipo = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTipo.sizePolicy().hasHeightForWidth())
        self.cbTipo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbTipo.setFont(font)
        self.cbTipo.setObjectName("cbTipo")
        self.cbTipo.addItem("")
        self.cbTipo.addItem("")
        self.cbTipo.addItem("")
        self.horizontalLayout_2.addWidget(self.cbTipo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.bScliente = QtWidgets.QCommandLinkButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bScliente.sizePolicy().hasHeightForWidth())
        self.bScliente.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../usr/share/pyventa/images/32/User-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bScliente.setIcon(icon1)
        self.bScliente.setObjectName("bScliente")
        self.verticalLayout.addWidget(self.bScliente)
        self.scrollArea = QtWidgets.QScrollArea(self.layoutWidget1)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 356, 148))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ncnotas = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ncnotas.setFont(font)
        self.ncnotas.setWordWrap(True)
        self.ncnotas.setMargin(10)
        self.ncnotas.setObjectName("ncnotas")
        self.verticalLayout_6.addWidget(self.ncnotas)
        self.pbLimpiar = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbLimpiar.sizePolicy().hasHeightForWidth())
        self.pbLimpiar.setSizePolicy(sizePolicy)
        self.pbLimpiar.setObjectName("pbLimpiar")
        self.verticalLayout_6.addWidget(self.pbLimpiar)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.nctotal = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nctotal.sizePolicy().hasHeightForWidth())
        self.nctotal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.nctotal.setFont(font)
        self.nctotal.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.nctotal.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nctotal.setWordWrap(True)
        self.nctotal.setMargin(10)
        self.nctotal.setObjectName("nctotal")
        self.verticalLayout.addWidget(self.nctotal)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rbEfectivo = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rbEfectivo.setChecked(True)
        self.rbEfectivo.setObjectName("rbEfectivo")
        self.verticalLayout_3.addWidget(self.rbEfectivo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbCredito = QtWidgets.QRadioButton(self.layoutWidget1)
        self.rbCredito.setEnabled(False)
        self.rbCredito.setObjectName("rbCredito")
        self.horizontalLayout.addWidget(self.rbCredito)
        self.BClientSelect = QtWidgets.QCommandLinkButton(self.layoutWidget1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../usr/share/pyventa/images/16/user_16.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BClientSelect.setIcon(icon2)
        self.BClientSelect.setObjectName("BClientSelect")
        self.horizontalLayout.addWidget(self.BClientSelect)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 8, -1, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_48 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_17.addWidget(self.label_48)
        self.ncrecibo = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ncrecibo.sizePolicy().hasHeightForWidth())
        self.ncrecibo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setWeight(75)
        font.setBold(True)
        self.ncrecibo.setFont(font)
        self.ncrecibo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ncrecibo.setDragEnabled(True)
        self.ncrecibo.setObjectName("ncrecibo")
        self.horizontalLayout_17.addWidget(self.ncrecibo)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.nccobrar = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nccobrar.sizePolicy().hasHeightForWidth())
        self.nccobrar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.nccobrar.setFont(font)
        self.nccobrar.setStyleSheet("padding:9;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../usr/share/pyventa/images/png/Money-64.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.nccobrar.setIcon(icon3)
        self.nccobrar.setObjectName("nccobrar")
        self.verticalLayout.addWidget(self.nccobrar)
        self.verticalLayout_2.addWidget(self.splitter)

        self.retranslateUi(Form)
        self.cbTipo.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.leNumero, self.nccobrar)
        Form.setTabOrder(self.nccobrar, self.twNotas)
        Form.setTabOrder(self.twNotas, self.scrollArea)
        Form.setTabOrder(self.scrollArea, self.rbEfectivo)
        Form.setTabOrder(self.rbEfectivo, self.rbCredito)
        Form.setTabOrder(self.rbCredito, self.BClientSelect)
        Form.setTabOrder(self.BClientSelect, self.ncrecibo)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtCore.QCoreApplication.translate("Form", "Form"))
        self.titulo.setText(QtCore.QCoreApplication.translate("Form", "Modulo de cobro de ventas."))
        self.twNotas.setSortingEnabled(True)
        self.label_2.setText(QtCore.QCoreApplication.translate("Form", "Nota:"))
        self.ncactualizar.setText(QtCore.QCoreApplication.translate("Form", "Actualizar listado"))
        self.cbTipo.setToolTip(QtCore.QCoreApplication.translate("Form", "Muestra la tabla de notas y/o facturas sin pagar del dia en curso."))
        self.cbTipo.setItemText(0, QtCore.QCoreApplication.translate("Form", "Todas las ventas"))
        self.cbTipo.setItemText(1, QtCore.QCoreApplication.translate("Form", "Notas"))
        self.cbTipo.setItemText(2, QtCore.QCoreApplication.translate("Form", "Facturas"))
        self.bScliente.setToolTip(QtWidgets.QApplication.translate("Form", "Selecciona un cliente para mostrar el historial de \n"
"ventas en credito de ese cliente en particular.", None, QtWidgets.QApplication.UnicodeUTF8))
        self.bScliente.setText(QtCore.QCoreApplication.translate("Form", "Seleccionar ventas pendientes por cliente"))
        self.ncnotas.setText(QtCore.QCoreApplication.translate("Form", "Notas:"))
        self.pbLimpiar.setText(QtCore.QCoreApplication.translate("Form", "Limpiar"))
        self.nctotal.setText(QtCore.QCoreApplication.translate("Form", "Total:"))
        self.label.setText(QtCore.QCoreApplication.translate("Form", "Modo de pago"))
        self.rbEfectivo.setText(QtCore.QCoreApplication.translate("Form", "Efectivo"))
        self.rbCredito.setText(QtCore.QCoreApplication.translate("Form", "Credito cliente"))
        self.BClientSelect.setText(QtCore.QCoreApplication.translate("Form", "Seleccionar cliente"))
        self.label_48.setText(QtCore.QCoreApplication.translate("Form", "Recibo:"))
        self.nccobrar.setText(QtCore.QCoreApplication.translate("Form", "Cobrar"))

