# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/modulos/ui_caja.ui'
#
# Created: Mon May 13 18:59:14 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(652, 516)
        self.verticalLayout_8 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setStyleSheet(_fromUtf8("QToolButton, QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));\n"
"border-radius:4px;border:1px solid #777; padding:2 9 2 9;color:#333;\n"
"}\n"
"QPushButton::pressed,QToolButton::pressed{\n"
"color:#fff;\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 66, 255, 255), stop:1 rgba(0, 107, 227, 255));\n"
"\n"
"}"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.titulo = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo.sizePolicy().hasHeightForWidth())
        self.titulo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setMargin(5)
        self.titulo.setObjectName(_fromUtf8("titulo"))
        self.verticalLayout_2.addWidget(self.titulo)
        self.top = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top.sizePolicy().hasHeightForWidth())
        self.top.setSizePolicy(sizePolicy)
        self.top.setObjectName(_fromUtf8("top"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.top)
        self.verticalLayout_3.setContentsMargins(5, 0, -1, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2.addWidget(self.top)
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.leNumero = QtGui.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.leNumero.setFont(font)
        self.leNumero.setObjectName(_fromUtf8("leNumero"))
        self.gridLayout.addWidget(self.leNumero, 0, 1, 1, 1)
        self.cbTipo = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTipo.sizePolicy().hasHeightForWidth())
        self.cbTipo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbTipo.setFont(font)
        self.cbTipo.setStyleSheet(_fromUtf8(""))
        self.cbTipo.setObjectName(_fromUtf8("cbTipo"))
        self.cbTipo.addItem(_fromUtf8(""))
        self.cbTipo.addItem(_fromUtf8(""))
        self.cbTipo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbTipo, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.tbScliente = QtGui.QToolButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbScliente.sizePolicy().hasHeightForWidth())
        self.tbScliente.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/user_woman.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbScliente.setIcon(icon)
        self.tbScliente.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbScliente.setObjectName(_fromUtf8("tbScliente"))
        self.gridLayout.addWidget(self.tbScliente, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ncactualizar = QtGui.QToolButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ncactualizar.setFont(font)
        self.ncactualizar.setStyleSheet(_fromUtf8("QPushButton{background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(137, 137, 137, 255), stop:0.0545455 rgba(156, 156, 156, 255), stop:1 rgba(191, 191, 191, 255));border:1.3px solid #999; border-radius:12px; color:#555;padding:5;}\n"
"QPushButton::hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(216, 216, 216, 255), stop:0.495455 rgba(229, 229, 229, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ncactualizar.setIcon(icon1)
        self.ncactualizar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.ncactualizar.setObjectName(_fromUtf8("ncactualizar"))
        self.horizontalLayout.addWidget(self.ncactualizar)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.widget1 = QtGui.QWidget(self.widget)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.widget1)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tbDepositar = QtGui.QToolButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbDepositar.sizePolicy().hasHeightForWidth())
        self.tbDepositar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbDepositar.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbDepositar.setIcon(icon2)
        self.tbDepositar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbDepositar.setObjectName(_fromUtf8("tbDepositar"))
        self.verticalLayout_5.addWidget(self.tbDepositar)
        self.tbInicial = QtGui.QToolButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbInicial.sizePolicy().hasHeightForWidth())
        self.tbInicial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tbInicial.setFont(font)
        self.tbInicial.setIcon(icon2)
        self.tbInicial.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbInicial.setObjectName(_fromUtf8("tbInicial"))
        self.verticalLayout_5.addWidget(self.tbInicial)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.widget1)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tbRetirar = QtGui.QToolButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbRetirar.sizePolicy().hasHeightForWidth())
        self.tbRetirar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbRetirar.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbRetirar.setIcon(icon3)
        self.tbRetirar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbRetirar.setObjectName(_fromUtf8("tbRetirar"))
        self.verticalLayout_4.addWidget(self.tbRetirar)
        self.tbGastar = QtGui.QToolButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbGastar.sizePolicy().hasHeightForWidth())
        self.tbGastar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbGastar.setFont(font)
        self.tbGastar.setIcon(icon3)
        self.tbGastar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbGastar.setObjectName(_fromUtf8("tbGastar"))
        self.verticalLayout_4.addWidget(self.tbGastar)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.widget1)
        self.widget2 = QtGui.QWidget(self.splitter)
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_4 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_7.addWidget(self.label_4)
        self.tvCuentas = QtGui.QTableView(self.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvCuentas.sizePolicy().hasHeightForWidth())
        self.tvCuentas.setSizePolicy(sizePolicy)
        self.tvCuentas.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tvCuentas.setFont(font)
        self.tvCuentas.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tvCuentas.setAlternatingRowColors(True)
        self.tvCuentas.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvCuentas.setSortingEnabled(True)
        self.tvCuentas.setObjectName(_fromUtf8("tvCuentas"))
        self.tvCuentas.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.tvCuentas)
        self.verticalLayout_8.addWidget(self.splitter)

        self.retranslateUi(Form)
        self.cbTipo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.leNumero, self.tbScliente)
        Form.setTabOrder(self.tbScliente, self.cbTipo)
        Form.setTabOrder(self.cbTipo, self.ncactualizar)
        Form.setTabOrder(self.ncactualizar, self.tbDepositar)
        Form.setTabOrder(self.tbDepositar, self.tbInicial)
        Form.setTabOrder(self.tbInicial, self.tbRetirar)
        Form.setTabOrder(self.tbRetirar, self.tbGastar)
        Form.setTabOrder(self.tbGastar, self.tvCuentas)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.titulo.setText(QtGui.QApplication.translate("Form", "Caja", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Cuentas por cobrar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Venta:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTipo.setToolTip(QtGui.QApplication.translate("Form", "Muestra la tabla de notas y/o facturas sin pagar del dia en curso.", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTipo.setItemText(0, QtGui.QApplication.translate("Form", "Todas las ventas", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTipo.setItemText(1, QtGui.QApplication.translate("Form", "Notas", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTipo.setItemText(2, QtGui.QApplication.translate("Form", "Facturas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Cliente:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Formato:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbScliente.setToolTip(QtGui.QApplication.translate("Form", "Selecciona un cliente para mostrar el historial de \n"
"ventas en credito de ese cliente en particular.", None, QtGui.QApplication.UnicodeUTF8))
        self.tbScliente.setText(QtGui.QApplication.translate("Form", "Seleccione cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.ncactualizar.setText(QtGui.QApplication.translate("Form", "Actualizar listado", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Registro de entradas", None, QtGui.QApplication.UnicodeUTF8))
        self.tbDepositar.setText(QtGui.QApplication.translate("Form", "Deposito", None, QtGui.QApplication.UnicodeUTF8))
        self.tbInicial.setText(QtGui.QApplication.translate("Form", "Efectivo inicial", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Registro de salidas", None, QtGui.QApplication.UnicodeUTF8))
        self.tbRetirar.setText(QtGui.QApplication.translate("Form", "Retiro", None, QtGui.QApplication.UnicodeUTF8))
        self.tbGastar.setText(QtGui.QApplication.translate("Form", "Gasto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Ventas por cobrar", None, QtGui.QApplication.UnicodeUTF8))
        self.tvCuentas.setToolTip(QtGui.QApplication.translate("Form", "Tabla de cuentas sin pagar", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
