# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui_calculo_precio.ui'
#
# Created: Fri Oct 14 01:15:09 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Calculo(object):
    def setupUi(self, Calculo):
        Calculo.setObjectName("Calculo")
        Calculo.resize(348, 190)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/pyventa/images/32/calculator-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Calculo.setWindowIcon(icon)
        Calculo.setStyleSheet("QWidget{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(180, 180, 180, 255), stop:0.02 rgba(158, 158, 158, 255), stop:1 rgba(124, 124, 124, 255));color:#fff;border:0;}\n"
"QLabel{ border:0px; background:none}\n"
"QAbstractButton{ color:#fff;padding:5px; border-radius:5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(158, 158, 158, 255), stop:0.43 rgba(163, 163, 163, 255), stop:1 rgba(124, 124, 124, 255));\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Calculo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Calculo)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setMargin(5)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame_2 = QtWidgets.QFrame(Calculo)
        self.frame_2.setStyleSheet("QWidget{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(41, 41, 41, 255), stop:0.05 #FDFDEE, stop:1 #FDFDEE);border-radius:5px; border:0;}\n"
"QLineEdit, QDoubleSpinBox,QLabel{background:#FDFDEE;color:#555;}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dsbPrecio = QtWidgets.QDoubleSpinBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.dsbPrecio.setFont(font)
        self.dsbPrecio.setFrame(False)
        self.dsbPrecio.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsbPrecio.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dsbPrecio.setMaximum(99999.99)
        self.dsbPrecio.setObjectName("dsbPrecio")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dsbPrecio)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.dsbPrecioDesc = QtWidgets.QDoubleSpinBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.dsbPrecioDesc.setFont(font)
        self.dsbPrecioDesc.setFrame(False)
        self.dsbPrecioDesc.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsbPrecioDesc.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dsbPrecioDesc.setMaximum(100000.0)
        self.dsbPrecioDesc.setSingleStep(0.5)
        self.dsbPrecioDesc.setObjectName("dsbPrecioDesc")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dsbPrecioDesc)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.dsbDescuento = QtWidgets.QDoubleSpinBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.dsbDescuento.setFont(font)
        self.dsbDescuento.setFrame(False)
        self.dsbDescuento.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsbDescuento.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dsbDescuento.setMaximum(100000.0)
        self.dsbDescuento.setObjectName("dsbDescuento")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dsbDescuento)
        self.verticalLayout.addWidget(self.frame_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Calculo)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Calculo)
        QtCore.QMetaObject.connectSlotsByName(Calculo)

    def retranslateUi(self, Calculo):
        Calculo.setWindowTitle(QtCore.QCoreApplication.translate("Calculo", "Calculadora de precios"))
        self.label.setText(QtCore.QCoreApplication.translate("Calculo", "Calculo de precios."))
        self.label_3.setText(QtCore.QCoreApplication.translate("Calculo", "Precio publico"))
        self.dsbPrecio.setPrefix(QtCore.QCoreApplication.translate("Calculo", "$"))
        self.label_4.setText(QtCore.QCoreApplication.translate("Calculo", "Precio con descuento"))
        self.dsbPrecioDesc.setPrefix(QtCore.QCoreApplication.translate("Calculo", "$"))
        self.label_5.setText(QtCore.QCoreApplication.translate("Calculo", "Descuento aplicado"))
        self.dsbDescuento.setSuffix(QtCore.QCoreApplication.translate("Calculo", "%"))

