# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/dave/Dropbox/Pyventa/pyventa-2.3/qt/ui_config.ui'
#
# Created: Wed Mar 27 07:18:10 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(679, 616)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/gear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titulo = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo.sizePolicy().hasHeightForWidth())
        self.titulo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.verticalLayout.addWidget(self.titulo)
        self.stack = QtWidgets.QTabWidget(Form)
        self.stack.setMinimumSize(QtCore.QSize(0, 0))
        self.stack.setObjectName("stack")
        self.stackPage3 = QtWidgets.QWidget()
        self.stackPage3.setObjectName("stackPage3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.stackPage3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbEditar = QtWidgets.QPushButton(self.stackPage3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbEditar.sizePolicy().hasHeightForWidth())
        self.pbEditar.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/pencil.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbEditar.setIcon(icon1)
        self.pbEditar.setObjectName("pbEditar")
        self.horizontalLayout.addWidget(self.pbEditar)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gbBox = QtWidgets.QGroupBox(self.stackPage3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbBox.sizePolicy().hasHeightForWidth())
        self.gbBox.setSizePolicy(sizePolicy)
        self.gbBox.setCheckable(True)
        self.gbBox.setChecked(True)
        self.gbBox.setObjectName("gbBox")
        self.formLayout_5 = QtWidgets.QFormLayout(self.gbBox)
        self.formLayout_5.setObjectName("formLayout_5")
        self.fLine_4 = QtWidgets.QFrame(self.gbBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fLine_4.sizePolicy().hasHeightForWidth())
        self.fLine_4.setSizePolicy(sizePolicy)
        self.fLine_4.setStyleSheet(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QDoubleSpinBox{background:transparent; border:0px; padding:3px}")
        self.fLine_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fLine_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fLine_4.setObjectName("fLine_4")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout(self.fLine_4)
        self.horizontalLayout_55.setSpacing(0)
        self.horizontalLayout_55.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.sbCaja = QtWidgets.QSpinBox(self.fLine_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCaja.sizePolicy().hasHeightForWidth())
        self.sbCaja.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sbCaja.setFont(font)
        self.sbCaja.setFrame(False)
        self.sbCaja.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.sbCaja.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.sbCaja.setObjectName("sbCaja")
        self.horizontalLayout_55.addWidget(self.sbCaja)
        self.tbBuscarCaja = QtWidgets.QToolButton(self.fLine_4)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/zoom.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbBuscarCaja.setIcon(icon2)
        self.tbBuscarCaja.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbBuscarCaja.setObjectName("tbBuscarCaja")
        self.horizontalLayout_55.addWidget(self.tbBuscarCaja)
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fLine_4)
        self.label_8 = QtWidgets.QLabel(self.gbBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.chbRecibePagos = QtWidgets.QCheckBox(self.gbBox)
        self.chbRecibePagos.setObjectName("chbRecibePagos")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.chbRecibePagos)
        self.verticalLayout_4.addWidget(self.gbBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.stackPage3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cbEstilos = QtWidgets.QComboBox(self.groupBox_4)
        self.cbEstilos.setObjectName("cbEstilos")
        self.gridLayout_4.addWidget(self.cbEstilos, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.tbRecargarEstilo = QtWidgets.QToolButton(self.groupBox_4)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/reload.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbRecargarEstilo.setIcon(icon3)
        self.tbRecargarEstilo.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbRecargarEstilo.setAutoRaise(True)
        self.tbRecargarEstilo.setObjectName("tbRecargarEstilo")
        self.gridLayout_4.addWidget(self.tbRecargarEstilo, 0, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/modulos/images/pyventa.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.stack.addTab(self.stackPage3, icon4, "")
        self.stackPage2 = QtWidgets.QWidget()
        self.stackPage2.setObjectName("stackPage2")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.stackPage2)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.gempresa = QtWidgets.QGroupBox(self.stackPage2)
        self.gempresa.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gempresa.setObjectName("gempresa")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.gempresa)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_37 = QtWidgets.QLabel(self.gempresa)
        self.label_37.setObjectName("label_37")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.lenombre = QtWidgets.QLineEdit(self.gempresa)
        self.lenombre.setObjectName("lenombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lenombre)
        self.label_20 = QtWidgets.QLabel(self.gempresa)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.fLine_3 = QtWidgets.QFrame(self.gempresa)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fLine_3.sizePolicy().hasHeightForWidth())
        self.fLine_3.setSizePolicy(sizePolicy)
        self.fLine_3.setStyleSheet(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QLineEdit{background:transparent; border:0px; padding:3px}")
        self.fLine_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fLine_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fLine_3.setObjectName("fLine_3")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout(self.fLine_3)
        self.horizontalLayout_54.setSpacing(0)
        self.horizontalLayout_54.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.leLogo = QtWidgets.QLineEdit(self.fLine_3)
        self.leLogo.setObjectName("leLogo")
        self.horizontalLayout_54.addWidget(self.leLogo)
        self.tbLogo = QtWidgets.QToolButton(self.fLine_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tbLogo.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/pictures_folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbLogo.setIcon(icon5)
        self.tbLogo.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbLogo.setObjectName("tbLogo")
        self.horizontalLayout_54.addWidget(self.tbLogo)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fLine_3)
        self.label_38 = QtWidgets.QLabel(self.gempresa)
        self.label_38.setObjectName("label_38")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.lerfc = QtWidgets.QLineEdit(self.gempresa)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lerfc.sizePolicy().hasHeightForWidth())
        self.lerfc.setSizePolicy(sizePolicy)
        self.lerfc.setMinimumSize(QtCore.QSize(230, 0))
        self.lerfc.setObjectName("lerfc")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lerfc)
        self.label_39 = QtWidgets.QLabel(self.gempresa)
        self.label_39.setObjectName("label_39")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.leslogan = QtWidgets.QLineEdit(self.gempresa)
        self.leslogan.setObjectName("leslogan")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.leslogan)
        self.label_40 = QtWidgets.QLabel(self.gempresa)
        self.label_40.setObjectName("label_40")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.ledir = QtWidgets.QLineEdit(self.gempresa)
        self.ledir.setObjectName("ledir")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ledir)
        self.verticalLayout_17.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_42 = QtWidgets.QLabel(self.gempresa)
        self.label_42.setObjectName("label_42")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.leestado = QtWidgets.QLineEdit(self.gempresa)
        self.leestado.setMaximumSize(QtCore.QSize(160, 16777215))
        self.leestado.setObjectName("leestado")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leestado)
        self.label_41 = QtWidgets.QLabel(self.gempresa)
        self.label_41.setObjectName("label_41")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.leciudad = QtWidgets.QLineEdit(self.gempresa)
        self.leciudad.setMaximumSize(QtCore.QSize(250, 16777215))
        self.leciudad.setObjectName("leciudad")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leciudad)
        self.label_43 = QtWidgets.QLabel(self.gempresa)
        self.label_43.setObjectName("label_43")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.letel = QtWidgets.QLineEdit(self.gempresa)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.letel.sizePolicy().hasHeightForWidth())
        self.letel.setSizePolicy(sizePolicy)
        self.letel.setObjectName("letel")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.letel)
        self.label_7 = QtWidgets.QLabel(self.gempresa)
        self.label_7.setObjectName("label_7")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lecp = QtWidgets.QLineEdit(self.gempresa)
        self.lecp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lecp.setObjectName("lecp")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lecp)
        self.label_45 = QtWidgets.QLabel(self.gempresa)
        self.label_45.setObjectName("label_45")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.leweb = QtWidgets.QLineEdit(self.gempresa)
        self.leweb.setObjectName("leweb")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.leweb)
        self.label_44 = QtWidgets.QLabel(self.gempresa)
        self.label_44.setObjectName("label_44")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.lemail = QtWidgets.QLineEdit(self.gempresa)
        self.lemail.setObjectName("lemail")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lemail)
        self.horizontalLayout_2.addLayout(self.formLayout_6)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_15 = QtWidgets.QLabel(self.gempresa)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_11.addWidget(self.label_15)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.gempresa)
        self.scrollArea_2.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);background-color: qlineargradient(spread:pad, x1:0.995, y1:0, x2:1, y2:1, stop:0 rgba(218, 218, 218, 255), stop:0.427273 rgba(249, 249, 249, 255), stop:0.509091 rgba(251, 251, 251, 255), stop:1 rgba(226, 226, 226, 255));")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 298, 167))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.lblLogo = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLogo.sizePolicy().hasHeightForWidth())
        self.lblLogo.setSizePolicy(sizePolicy)
        self.lblLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.verticalLayout_19.addWidget(self.lblLogo)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_11.addWidget(self.scrollArea_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_17.addLayout(self.horizontalLayout_2)
        self.brecargar = QtWidgets.QPushButton(self.gempresa)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brecargar.sizePolicy().hasHeightForWidth())
        self.brecargar.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/diskette.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.brecargar.setIcon(icon6)
        self.brecargar.setObjectName("brecargar")
        self.verticalLayout_17.addWidget(self.brecargar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_17.addItem(spacerItem1)
        self.verticalLayout_25.addWidget(self.gempresa)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/certificate-(2).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.stack.addTab(self.stackPage2, icon7, "")
        self.stackPage1 = QtWidgets.QWidget()
        self.stackPage1.setObjectName("stackPage1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.stackPage1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.stackPage1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.widget = QtWidgets.QWidget(self.stackPage1)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.tserver = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tserver.sizePolicy().hasHeightForWidth())
        self.tserver.setSizePolicy(sizePolicy)
        self.tserver.setObjectName("tserver")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tserver)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.tuser = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tuser.sizePolicy().hasHeightForWidth())
        self.tuser.setSizePolicy(sizePolicy)
        self.tuser.setText("")
        self.tuser.setObjectName("tuser")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tuser)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.tpass = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tpass.sizePolicy().hasHeightForWidth())
        self.tpass.setSizePolicy(sizePolicy)
        self.tpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.tpass.setObjectName("tpass")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tpass)
        self.lbldb = QtWidgets.QLabel(self.widget)
        self.lbldb.setObjectName("lbldb")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbldb)
        self.tdb = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tdb.sizePolicy().hasHeightForWidth())
        self.tdb.setSizePolicy(sizePolicy)
        self.tdb.setObjectName("tdb")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tdb)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.splitter_3 = QtWidgets.QSplitter(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.bset = QtWidgets.QPushButton(self.splitter_3)
        self.bset.setEnabled(False)
        self.bset.setObjectName("bset")
        self.bprobar = QtWidgets.QPushButton(self.splitter_3)
        self.bprobar.setObjectName("bprobar")
        self.bclose = QtWidgets.QPushButton(self.splitter_3)
        self.bclose.setObjectName("bclose")
        self.bcreate = QtWidgets.QPushButton(self.splitter_3)
        self.bcreate.setEnabled(False)
        self.bcreate.setObjectName("bcreate")
        self.verticalLayout_3.addWidget(self.splitter_3)
        self.display = QtWidgets.QTextBrowser(self.widget)
        self.display.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display.sizePolicy().hasHeightForWidth())
        self.display.setSizePolicy(sizePolicy)
        self.display.setObjectName("display")
        self.verticalLayout_3.addWidget(self.display)
        self.verticalLayout_5.addWidget(self.widget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/connect.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.stack.addTab(self.stackPage1, icon8, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dsbTicketTigger = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbTicketTigger.sizePolicy().hasHeightForWidth())
        self.dsbTicketTigger.setSizePolicy(sizePolicy)
        self.dsbTicketTigger.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsbTicketTigger.setMaximum(9999.99)
        self.dsbTicketTigger.setObjectName("dsbTicketTigger")
        self.gridLayout_3.addWidget(self.dsbTicketTigger, 0, 1, 1, 1)
        self.chbImprimirCopia = QtWidgets.QCheckBox(self.groupBox_3)
        self.chbImprimirCopia.setObjectName("chbImprimirCopia")
        self.gridLayout_3.addWidget(self.chbImprimirCopia, 1, 0, 1, 1)
        self.dsbCopia = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbCopia.sizePolicy().hasHeightForWidth())
        self.dsbCopia.setSizePolicy(sizePolicy)
        self.dsbCopia.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsbCopia.setMaximum(99999.99)
        self.dsbCopia.setObjectName("dsbCopia")
        self.gridLayout_3.addWidget(self.dsbCopia, 1, 1, 1, 1)
        self.chbImprimirTicket = QtWidgets.QCheckBox(self.groupBox_3)
        self.chbImprimirTicket.setCheckable(True)
        self.chbImprimirTicket.setObjectName("chbImprimirTicket")
        self.gridLayout_3.addWidget(self.chbImprimirTicket, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.cbpreview = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbpreview.sizePolicy().hasHeightForWidth())
        self.cbpreview.setSizePolicy(sizePolicy)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/paragraph_align_left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cbpreview.setIcon(icon9)
        self.cbpreview.setObjectName("cbpreview")
        self.verticalLayout_2.addWidget(self.cbpreview)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.ctPrinter = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctPrinter.sizePolicy().hasHeightForWidth())
        self.ctPrinter.setSizePolicy(sizePolicy)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/print.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ctPrinter.setIcon(icon10)
        self.ctPrinter.setObjectName("ctPrinter")
        self.gridLayout.addWidget(self.ctPrinter, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 0, 1, 1)
        self.cbPrinters = QtWidgets.QComboBox(self.groupBox_3)
        self.cbPrinters.setObjectName("cbPrinters")
        self.gridLayout.addWidget(self.cbPrinters, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 0, 0, 1, 1)
        self.cbDrivers = QtWidgets.QComboBox(self.groupBox_3)
        self.cbDrivers.setObjectName("cbDrivers")
        self.gridLayout_5.addWidget(self.cbDrivers, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.verticalLayout_18.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.fLine = QtWidgets.QFrame(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fLine.sizePolicy().hasHeightForWidth())
        self.fLine.setSizePolicy(sizePolicy)
        self.fLine.setStyleSheet(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QLineEdit{background:transparent; border:0px; padding:3px}")
        self.fLine.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fLine.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fLine.setObjectName("fLine")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.fLine)
        self.horizontalLayout_51.setSpacing(0)
        self.horizontalLayout_51.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.lbeProducto_5 = QtWidgets.QLabel(self.fLine)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbeProducto_5.setFont(font)
        self.lbeProducto_5.setText("")
        self.lbeProducto_5.setObjectName("lbeProducto_5")
        self.horizontalLayout_51.addWidget(self.lbeProducto_5)
        self.cbPath = QtWidgets.QToolButton(self.fLine)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cbPath.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/folder.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cbPath.setIcon(icon11)
        self.cbPath.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.cbPath.setObjectName("cbPath")
        self.horizontalLayout_51.addWidget(self.cbPath)
        self.verticalLayout_15.addWidget(self.fLine)
        self.pbfEditar = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbfEditar.sizePolicy().hasHeightForWidth())
        self.pbfEditar.setSizePolicy(sizePolicy)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/paragraph_justify.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbfEditar.setIcon(icon12)
        self.pbfEditar.setObjectName("pbfEditar")
        self.verticalLayout_15.addWidget(self.pbfEditar)
        self.verticalLayout_18.addWidget(self.groupBox_5)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.pbpEditar_ = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbpEditar_.sizePolicy().hasHeightForWidth())
        self.pbpEditar_.setSizePolicy(sizePolicy)
        self.pbpEditar_.setIcon(icon9)
        self.pbpEditar_.setObjectName("pbpEditar_")
        self.verticalLayout_16.addWidget(self.pbpEditar_)
        self.verticalLayout_18.addWidget(self.groupBox_8)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.pbEditarCorte = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbEditarCorte.sizePolicy().hasHeightForWidth())
        self.pbEditarCorte.setSizePolicy(sizePolicy)
        self.pbEditarCorte.setIcon(icon9)
        self.pbEditarCorte.setObjectName("pbEditarCorte")
        self.verticalLayout_20.addWidget(self.pbEditarCorte)
        self.verticalLayout_18.addWidget(self.groupBox)
        self.stack.addTab(self.tab, icon10, "")
        self.stackPage5 = QtWidgets.QWidget()
        self.stackPage5.setObjectName("stackPage5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.stackPage5)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 10, 601, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rlRestoreDB = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rlRestoreDB.sizePolicy().hasHeightForWidth())
        self.rlRestoreDB.setSizePolicy(sizePolicy)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/rotate.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rlRestoreDB.setIcon(icon13)
        self.rlRestoreDB.setIconSize(QtCore.QSize(32, 32))
        self.rlRestoreDB.setFlat(True)
        self.rlRestoreDB.setObjectName("rlRestoreDB")
        self.gridLayout_2.addWidget(self.rlRestoreDB, 2, 0, 1, 1)
        self.rlRestoreConf = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rlRestoreConf.sizePolicy().hasHeightForWidth())
        self.rlRestoreConf.setSizePolicy(sizePolicy)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/history.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rlRestoreConf.setIcon(icon14)
        self.rlRestoreConf.setIconSize(QtCore.QSize(32, 32))
        self.rlRestoreConf.setFlat(True)
        self.rlRestoreConf.setObjectName("rlRestoreConf")
        self.gridLayout_2.addWidget(self.rlRestoreConf, 3, 0, 1, 1)
        self.rlBackup = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rlBackup.sizePolicy().hasHeightForWidth())
        self.rlBackup.setSizePolicy(sizePolicy)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/compress.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rlBackup.setIcon(icon15)
        self.rlBackup.setFlat(True)
        self.rlBackup.setObjectName("rlBackup")
        self.gridLayout_2.addWidget(self.rlBackup, 0, 1, 1, 1)
        self.rlRestore = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rlRestore.sizePolicy().hasHeightForWidth())
        self.rlRestore.setSizePolicy(sizePolicy)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/undo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rlRestore.setIcon(icon16)
        self.rlRestore.setIconSize(QtCore.QSize(32, 32))
        self.rlRestore.setFlat(True)
        self.rlRestore.setObjectName("rlRestore")
        self.gridLayout_2.addWidget(self.rlRestore, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.cpgrespaldo = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpgrespaldo.sizePolicy().hasHeightForWidth())
        self.cpgrespaldo.setSizePolicy(sizePolicy)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/upload2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cpgrespaldo.setIcon(icon17)
        self.cpgrespaldo.setFlat(True)
        self.cpgrespaldo.setObjectName("cpgrespaldo")
        self.gridLayout_2.addWidget(self.cpgrespaldo, 1, 1, 1, 1)
        self.gbLocal = QtWidgets.QGroupBox(self.stackPage5)
        self.gbLocal.setGeometry(QtCore.QRect(20, 220, 611, 291))
        self.gbLocal.setObjectName("gbLocal")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.gbLocal)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.fLine_2 = QtWidgets.QFrame(self.gbLocal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fLine_2.sizePolicy().hasHeightForWidth())
        self.fLine_2.setSizePolicy(sizePolicy)
        self.fLine_2.setStyleSheet(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QLineEdit{background:transparent; border:0px; padding:3px}")
        self.fLine_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fLine_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fLine_2.setObjectName("fLine_2")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.fLine_2)
        self.horizontalLayout_52.setSpacing(0)
        self.horizontalLayout_52.setContentsMargins(0, 0, 4, 0)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_16 = QtWidgets.QLabel(self.fLine_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_52.addWidget(self.label_16)
        self.rlPath = QtWidgets.QLabel(self.fLine_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rlPath.setFont(font)
        self.rlPath.setText("")
        self.rlPath.setObjectName("rlPath")
        self.horizontalLayout_52.addWidget(self.rlPath)
        self.clrExplorar = QtWidgets.QToolButton(self.fLine_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clrExplorar.setFont(font)
        self.clrExplorar.setIcon(icon11)
        self.clrExplorar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.clrExplorar.setObjectName("clrExplorar")
        self.horizontalLayout_52.addWidget(self.clrExplorar)
        self.verticalLayout_9.addWidget(self.fLine_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_53 = QtWidgets.QLabel(self.gbLocal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_4.addWidget(self.label_53)
        self.rlPeriod = QtWidgets.QSpinBox(self.gbLocal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rlPeriod.sizePolicy().hasHeightForWidth())
        self.rlPeriod.setSizePolicy(sizePolicy)
        self.rlPeriod.setObjectName("rlPeriod")
        self.horizontalLayout_4.addWidget(self.rlPeriod)
        self.label_17 = QtWidgets.QLabel(self.gbLocal)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_51 = QtWidgets.QLabel(self.gbLocal)
        self.label_51.setObjectName("label_51")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.rsServer = QtWidgets.QLineEdit(self.gbLocal)
        self.rsServer.setObjectName("rsServer")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rsServer)
        self.label_11 = QtWidgets.QLabel(self.gbLocal)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.rsUser = QtWidgets.QLineEdit(self.gbLocal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rsUser.sizePolicy().hasHeightForWidth())
        self.rsUser.setSizePolicy(sizePolicy)
        self.rsUser.setToolTip("")
        self.rsUser.setObjectName("rsUser")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rsUser)
        self.label_12 = QtWidgets.QLabel(self.gbLocal)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.rsPass = QtWidgets.QLineEdit(self.gbLocal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rsPass.sizePolicy().hasHeightForWidth())
        self.rsPass.setSizePolicy(sizePolicy)
        self.rsPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.rsPass.setObjectName("rsPass")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rsPass)
        self.label_13 = QtWidgets.QLabel(self.gbLocal)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.rsPath = QtWidgets.QLineEdit(self.gbLocal)
        self.rsPath.setObjectName("rsPath")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rsPath)
        self.verticalLayout_9.addLayout(self.formLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_50 = QtWidgets.QLabel(self.gbLocal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_3.addWidget(self.label_50)
        self.rsPeriod = QtWidgets.QSpinBox(self.gbLocal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rsPeriod.sizePolicy().hasHeightForWidth())
        self.rsPeriod.setSizePolicy(sizePolicy)
        self.rsPeriod.setObjectName("rsPeriod")
        self.horizontalLayout_3.addWidget(self.rsPeriod)
        self.label_10 = QtWidgets.QLabel(self.gbLocal)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/redo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.stack.addTab(self.stackPage5, icon18, "")
        self.verticalLayout.addWidget(self.stack)

        self.retranslateUi(Form)
        self.stack.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtCore.QCoreApplication.translate("Form", "Centro de configuraciones"))
        self.titulo.setText(QtCore.QCoreApplication.translate("Form", "Centro de configuraciones."))
        self.pbEditar.setText(QtCore.QCoreApplication.translate("Form", "Editar archivo de configuracion"))
        self.gbBox.setTitle(QtCore.QCoreApplication.translate("Form", "Esta computadora es caja"))
        self.tbBuscarCaja.setText(QtCore.QCoreApplication.translate("Form", "Ver cajas"))
        self.label_8.setText(QtCore.QCoreApplication.translate("Form", "Numero de caja:"))
        self.chbRecibePagos.setToolTip(QtCore.QCoreApplication.translate("Form", "Marque esta opcion si en este equipo se maneja el cobro de ventas."))
        self.chbRecibePagos.setText(QtCore.QCoreApplication.translate("Form", "Esta estacion recibe pagos"))
        self.groupBox_4.setTitle(QtCore.QCoreApplication.translate("Form", "Apariencia"))
        self.label_6.setText(QtCore.QCoreApplication.translate("Form", "Estilo visual:"))
        self.tbRecargarEstilo.setText(QtCore.QCoreApplication.translate("Form", "Recargar"))
        self.stack.setTabText(self.stack.indexOf(self.stackPage3), QtCore.QCoreApplication.translate("Form", "Estacion de trabajo"))
        self.gempresa.setTitle(QtCore.QCoreApplication.translate("Form", "Datos de la Empresa"))
        self.label_37.setText(QtCore.QCoreApplication.translate("Form", "Nombre"))
        self.label_20.setText(QtCore.QCoreApplication.translate("Form", "Logo "))
        self.tbLogo.setText(QtCore.QCoreApplication.translate("Form", "Abrir imagen ..."))
        self.label_38.setText(QtCore.QCoreApplication.translate("Form", "RFC"))
        self.label_39.setText(QtCore.QCoreApplication.translate("Form", "Slogan"))
        self.label_40.setText(QtCore.QCoreApplication.translate("Form", "Direccion"))
        self.label_42.setText(QtCore.QCoreApplication.translate("Form", "Estado/Dep"))
        self.label_41.setText(QtCore.QCoreApplication.translate("Form", "Ciudad"))
        self.label_43.setText(QtCore.QCoreApplication.translate("Form", "Telefono"))
        self.letel.setInputMask(QtCore.QCoreApplication.translate("Form", "(###) ### -####; "))
        self.label_7.setText(QtCore.QCoreApplication.translate("Form", "Codigo P."))
        self.lecp.setInputMask(QtCore.QCoreApplication.translate("Form", "#####; "))
        self.label_45.setText(QtCore.QCoreApplication.translate("Form", "Pagina Web"))
        self.label_44.setText(QtCore.QCoreApplication.translate("Form", "E-mail"))
        self.label_15.setText(QtCore.QCoreApplication.translate("Form", "Logo "))
        self.brecargar.setText(QtCore.QCoreApplication.translate("Form", "Guardar cambios"))
        self.stack.setTabText(self.stack.indexOf(self.stackPage2), QtCore.QCoreApplication.translate("Form", "Empresa"))
        self.label_4.setText(QtCore.QCoreApplication.translate("Form", "Base de datos"))
        self.label.setText(QtCore.QCoreApplication.translate("Form", "Modifica los datos necesarios para poder conectarse a la base de datos de MySQL."))
        self.label_2.setText(QtCore.QCoreApplication.translate("Form", "Servidor: "))
        self.tserver.setText(QtCore.QCoreApplication.translate("Form", "localhost"))
        self.label_3.setText(QtCore.QCoreApplication.translate("Form", "Usuario:  "))
        self.label_5.setText(QtCore.QCoreApplication.translate("Form", "Password"))
        self.lbldb.setText(QtCore.QCoreApplication.translate("Form", "Base de datos "))
        self.tdb.setText(QtCore.QCoreApplication.translate("Form", "tpv"))
        self.bset.setText(QtCore.QCoreApplication.translate("Form", "Establecer"))
        self.bprobar.setText(QtCore.QCoreApplication.translate("Form", "Aplicar"))
        self.bclose.setText(QtCore.QCoreApplication.translate("Form", "Cerrar"))
        self.bcreate.setText(QtCore.QCoreApplication.translate("Form", "Crear database"))
        self.display.setStyleSheet(QtWidgets.QApplication.translate("Form", "background-color: rgb(252, 252, 252);\n"
"border: 2px solid rgb(175, 175, 175);\n"
"border-radius:5px;\n"
"color:rgb(32, 158, 204);", None, QtWidgets.QApplication.UnicodeUTF8))
        self.stack.setTabText(self.stack.indexOf(self.stackPage1), QtCore.QCoreApplication.translate("Form", "Base datos"))
        self.groupBox_3.setTitle(QtCore.QCoreApplication.translate("Form", "Recibo"))
        self.dsbTicketTigger.setPrefix(QtCore.QCoreApplication.translate("Form", "$"))
        self.chbImprimirCopia.setText(QtCore.QCoreApplication.translate("Form", "Imprimir copia de recibo con totales de venta mayores a:"))
        self.chbImprimirTicket.setText(QtCore.QCoreApplication.translate("Form", "Imprimir recibo en ventas  con totales de venta mayores a:"))
        self.cbpreview.setText(QtCore.QCoreApplication.translate("Form", "Editar el formato del recibo"))
        self.label_14.setText(QtCore.QCoreApplication.translate("Form", "Seleccione la impresora para imprimir recibos:"))
        self.ctPrinter.setText(QtCore.QCoreApplication.translate("Form", "Seleccionar impresora"))
        self.label_18.setText(QtCore.QCoreApplication.translate("Form", "Solo para sistemas UNIX"))
        self.label_19.setText(QtCore.QCoreApplication.translate("Form", "Driver ESC/POS para impresoras de tickets"))
        self.label_21.setText(QtCore.QCoreApplication.translate("Form", "Seleccione el driver de su impresora :"))
        self.groupBox_5.setTitle(QtCore.QCoreApplication.translate("Form", "Facturas"))
        self.cbPath.setText(QtCore.QCoreApplication.translate("Form", "Cambiar carpeta ..."))
        self.pbfEditar.setText(QtCore.QCoreApplication.translate("Form", "Configurar posiciones (Avanzado)"))
        self.groupBox_8.setTitle(QtCore.QCoreApplication.translate("Form", "Presupuestos"))
        self.pbpEditar_.setText(QtCore.QCoreApplication.translate("Form", "Editar plantilla de impresion"))
        self.groupBox.setTitle(QtCore.QCoreApplication.translate("Form", "Reporte de ventas diarias"))
        self.pbEditarCorte.setText(QtCore.QCoreApplication.translate("Form", "Editar formato de corte"))
        self.stack.setTabText(self.stack.indexOf(self.tab), QtCore.QCoreApplication.translate("Form", "Impresion"))
        self.groupBox_2.setTitle(QtCore.QCoreApplication.translate("Form", "Acciones principales."))
        self.rlRestoreDB.setText(QtCore.QCoreApplication.translate("Form", "Restaurar solo Base de Datos"))
        self.rlRestoreConf.setText(QtCore.QCoreApplication.translate("Form", "Restaurar solo configuraciones"))
        self.rlBackup.setText(QtCore.QCoreApplication.translate("Form", "Generar respaldo"))
        self.rlRestore.setText(QtCore.QCoreApplication.translate("Form", "Restaurar respaldo completo"))
        self.cpgrespaldo.setText(QtCore.QCoreApplication.translate("Form", "Generar y subir respaldo"))
        self.gbLocal.setTitle(QtCore.QCoreApplication.translate("Form", "Configuraciones de respaldos"))
        self.label_16.setText(QtCore.QCoreApplication.translate("Form", "Se guardan en:"))
        self.clrExplorar.setText(QtCore.QCoreApplication.translate("Form", " ..."))
        self.label_53.setText(QtCore.QCoreApplication.translate("Form", "Realizar respaldo automatico cada "))
        self.rlPeriod.setToolTip(QtCore.QCoreApplication.translate("Form", "Si de no desea utilizar esta opcion, dejela en 0"))
        self.label_17.setText(QtCore.QCoreApplication.translate("Form", "dias"))
        self.label_51.setText(QtCore.QCoreApplication.translate("Form", "Servidor ftp://"))
        self.label_11.setText(QtCore.QCoreApplication.translate("Form", "Usuario"))
        self.label_12.setText(QtCore.QCoreApplication.translate("Form", "Password"))
        self.label_13.setText(QtCore.QCoreApplication.translate("Form", "Ruta"))
        self.rsPath.setToolTip(QtCore.QCoreApplication.translate("Form", "Si desconoce la ruta en la que se guardaran, puede dejarlo vacio"))
        self.label_50.setText(QtCore.QCoreApplication.translate("Form", "Realizar respaldo a internet cada "))
        self.rsPeriod.setToolTip(QtCore.QCoreApplication.translate("Form", "Frecuencia con la que se respaldara automaticamente, si se deja en \"0\" solo se hara respaldo cuando el administrador lo indique."))
        self.label_10.setText(QtCore.QCoreApplication.translate("Form", "dias"))
        self.stack.setTabText(self.stack.indexOf(self.stackPage5), QtCore.QCoreApplication.translate("Form", "Respaldos"))
# 
import icons_rc
  # TODO: regenerate with pyrcc6