# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/dialogos/ui_cambia_precios.ui'
#
# Created: Thu Apr 11 03:55:34 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        Form.resize(522, 454)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topModule = QtWidgets.QWidget(Form)
        self.topModule.setStyleSheet("QToolButton, QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));\n"
"border-radius:4px;border:1px solid #777; padding:2 9 2 9;color:#333;\n"
"}\n"
"QPushButton::pressed{\n"
"color:#fff;\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 66, 255, 255), stop:1 rgba(0, 107, 227, 255));\n"
"\n"
"}")
        self.topModule.setObjectName("topModule")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.topModule)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.chbGanancia = QtWidgets.QCheckBox(self.topModule)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbGanancia.setFont(font)
        self.chbGanancia.setObjectName("chbGanancia")
        self.gridLayout.addWidget(self.chbGanancia, 3, 0, 1, 1)
        self.dsbIncremento = QtWidgets.QDoubleSpinBox(self.topModule)
        self.dsbIncremento.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dsbIncremento.setFont(font)
        self.dsbIncremento.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsbIncremento.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dsbIncremento.setPrefix("")
        self.dsbIncremento.setDecimals(3)
        self.dsbIncremento.setMinimum(-999.99)
        self.dsbIncremento.setMaximum(999.99)
        self.dsbIncremento.setObjectName("dsbIncremento")
        self.gridLayout.addWidget(self.dsbIncremento, 5, 1, 1, 1)
        self.dsbCosto = QtWidgets.QDoubleSpinBox(self.topModule)
        self.dsbCosto.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dsbCosto.setFont(font)
        self.dsbCosto.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsbCosto.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dsbCosto.setMaximum(99999.99)
        self.dsbCosto.setObjectName("dsbCosto")
        self.gridLayout.addWidget(self.dsbCosto, 2, 1, 1, 1)
        self.dsbGanancia = QtWidgets.QDoubleSpinBox(self.topModule)
        self.dsbGanancia.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dsbGanancia.setFont(font)
        self.dsbGanancia.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsbGanancia.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dsbGanancia.setPrefix("")
        self.dsbGanancia.setMaximum(99999.99)
        self.dsbGanancia.setObjectName("dsbGanancia")
        self.gridLayout.addWidget(self.dsbGanancia, 3, 1, 1, 1)
        self.dsbPreciop = QtWidgets.QDoubleSpinBox(self.topModule)
        self.dsbPreciop.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dsbPreciop.setFont(font)
        self.dsbPreciop.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsbPreciop.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dsbPreciop.setMaximum(99999.99)
        self.dsbPreciop.setObjectName("dsbPreciop")
        self.gridLayout.addWidget(self.dsbPreciop, 4, 1, 1, 1)
        self.chbPrecio = QtWidgets.QCheckBox(self.topModule)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbPrecio.setFont(font)
        self.chbPrecio.setObjectName("chbPrecio")
        self.gridLayout.addWidget(self.chbPrecio, 4, 0, 1, 1)
        self.chbCosto = QtWidgets.QCheckBox(self.topModule)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.chbCosto.setFont(font)
        self.chbCosto.setObjectName("chbCosto")
        self.gridLayout.addWidget(self.chbCosto, 2, 0, 1, 1)
        self.chbIncremento = QtWidgets.QCheckBox(self.topModule)
        self.chbIncremento.setObjectName("chbIncremento")
        self.gridLayout.addWidget(self.chbIncremento, 5, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, 9, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pbProbar = QtWidgets.QPushButton(self.topModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbProbar.sizePolicy().hasHeightForWidth())
        self.pbProbar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(10)
        self.pbProbar.setFont(font)
        self.pbProbar.setStyleSheet("")
        self.pbProbar.setObjectName("pbProbar")
        self.gridLayout_2.addWidget(self.pbProbar, 0, 1, 1, 1)
        self.pbRestaurar = QtWidgets.QPushButton(self.topModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbRestaurar.sizePolicy().hasHeightForWidth())
        self.pbRestaurar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(10)
        self.pbRestaurar.setFont(font)
        self.pbRestaurar.setObjectName("pbRestaurar")
        self.gridLayout_2.addWidget(self.pbRestaurar, 1, 1, 1, 1)
        self.pbGuardar = QtWidgets.QPushButton(self.topModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbGuardar.sizePolicy().hasHeightForWidth())
        self.pbGuardar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pbGuardar.setFont(font)
        self.pbGuardar.setStyleSheet("QToolButton, QAbstractButton{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(10, 125, 159, 255), stop:1 rgba(0, 188, 255, 255));color:#fff;\n"
"border-radius:4px;border:1px solid #777; padding:2 9 2 9;\n"
"}\n"
"QAbstractButton::pressed{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 66, 255, 255), stop:1 rgba(0, 107, 227, 255));\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/actions/sticker/key.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbGuardar.setIcon(icon)
        self.pbGuardar.setDefault(True)
        self.pbGuardar.setObjectName("pbGuardar")
        self.gridLayout_2.addWidget(self.pbGuardar, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.topModule)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tvProductos = QtWidgets.QTableView(Form)
        self.tvProductos.setAlternatingRowColors(True)
        self.tvProductos.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.tvProductos.setObjectName("tvProductos")
        self.tvProductos.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tvProductos)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        self.chbCosto.toggled.connect(self.dsbCosto.setEnabled)
        self.chbGanancia.toggled.connect(self.dsbGanancia.setEnabled)
        self.chbPrecio.toggled.connect(self.dsbPreciop.setEnabled)
        self.chbIncremento.toggled.connect(self.dsbIncremento.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtCore.QCoreApplication.translate("Form", "Cambio de precios por lote"))
        self.chbGanancia.setText(QtCore.QCoreApplication.translate("Form", "Ganancia"))
        self.dsbIncremento.setToolTip(QtCore.QCoreApplication.translate("Form", "Un incremento sube o baja el costo en una tasa porcentual"))
        self.dsbIncremento.setSuffix(QtCore.QCoreApplication.translate("Form", "%"))
        self.dsbCosto.setPrefix(QtCore.QCoreApplication.translate("Form", "$ "))
        self.dsbGanancia.setSuffix(QtCore.QCoreApplication.translate("Form", "%"))
        self.dsbPreciop.setPrefix(QtCore.QCoreApplication.translate("Form", "$ "))
        self.chbPrecio.setText(QtCore.QCoreApplication.translate("Form", "Precio publico"))
        self.chbCosto.setText(QtCore.QCoreApplication.translate("Form", "Costo"))
        self.chbIncremento.setText(QtCore.QCoreApplication.translate("Form", "Incremento"))
        self.pbProbar.setToolTip(QtCore.QCoreApplication.translate("Form", "Hace una simulacion del cambio y lo muestra en la tabla, no aplica los cambios en la base de datos"))
        self.pbProbar.setText(QtCore.QCoreApplication.translate("Form", "Aplicar"))
        self.pbRestaurar.setToolTip(QtCore.QCoreApplication.translate("Form", "<html><head/><body><p>Descarta todos los cambios y regresa los productos al estado inicial.</p></body></html>"))
        self.pbRestaurar.setText(QtCore.QCoreApplication.translate("Form", "Restaurar"))
        self.pbGuardar.setToolTip(QtCore.QCoreApplication.translate("Form", "Aplica los cambios en la base de  datos."))
        self.pbGuardar.setText(QtCore.QCoreApplication.translate("Form", "Guardar"))
# 
import icons_rc
  # TODO: regenerate with pyrcc6