# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/modulos/ui_control1.ui'
#
# Created: Wed Apr 17 14:34:00 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Masul(object):
    def setupUi(self, Masul):
        Masul.setObjectName("Masul")
        Masul.resize(698, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/window.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Masul.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Masul)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topModule = QtWidgets.QWidget(Masul)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topModule.sizePolicy().hasHeightForWidth())
        self.topModule.setSizePolicy(sizePolicy)
        self.topModule.setStyleSheet("#topModule{padding:10px}")
        self.topModule.setObjectName("topModule")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.topModule)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self._2 = QtWidgets.QHBoxLayout()
        self._2.setObjectName("_2")
        self.fBuscar_6 = QtWidgets.QFrame(self.topModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fBuscar_6.sizePolicy().hasHeightForWidth())
        self.fBuscar_6.setSizePolicy(sizePolicy)
        self.fBuscar_6.setStyleSheet(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QLineEdit{background:transparent; border:0px; padding:3px}")
        self.fBuscar_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fBuscar_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fBuscar_6.setObjectName("fBuscar_6")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.fBuscar_6)
        self.horizontalLayout_51.setSpacing(0)
        self.horizontalLayout_51.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.tbHome = QtWidgets.QToolButton(self.fBuscar_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbHome.sizePolicy().hasHeightForWidth())
        self.tbHome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tbHome.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbHome.setIcon(icon1)
        self.tbHome.setIconSize(QtCore.QSize(18, 18))
        self.tbHome.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbHome.setObjectName("tbHome")
        self.horizontalLayout_51.addWidget(self.tbHome)
        self.leTitulo = QtWidgets.QLabel(self.fBuscar_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.leTitulo.setFont(font)
        self.leTitulo.setText("")
        self.leTitulo.setObjectName("leTitulo")
        self.horizontalLayout_51.addWidget(self.leTitulo)
        self.lineEdit = QtWidgets.QLineEdit(self.fBuscar_6)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_51.addWidget(self.lineEdit)
        self._2.addWidget(self.fBuscar_6)
        self.verticalLayout_9.addLayout(self._2)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setSpacing(3)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.tbLimpiar = QtWidgets.QToolButton(self.topModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbLimpiar.sizePolicy().hasHeightForWidth())
        self.tbLimpiar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbLimpiar.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbLimpiar.setIcon(icon2)
        self.tbLimpiar.setIconSize(QtCore.QSize(18, 18))
        self.tbLimpiar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbLimpiar.setAutoRaise(True)
        self.tbLimpiar.setObjectName("tbLimpiar")
        self.horizontalLayout_52.addWidget(self.tbLimpiar)
        self.tbModif = QtWidgets.QToolButton(self.topModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbModif.sizePolicy().hasHeightForWidth())
        self.tbModif.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbModif.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/diskette.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbModif.setIcon(icon3)
        self.tbModif.setIconSize(QtCore.QSize(18, 18))
        self.tbModif.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbModif.setAutoRaise(True)
        self.tbModif.setObjectName("tbModif")
        self.horizontalLayout_52.addWidget(self.tbModif)
        self.tbAgregar = QtWidgets.QToolButton(self.topModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbAgregar.sizePolicy().hasHeightForWidth())
        self.tbAgregar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbAgregar.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/copy.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbAgregar.setIcon(icon4)
        self.tbAgregar.setIconSize(QtCore.QSize(18, 18))
        self.tbAgregar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbAgregar.setAutoRaise(True)
        self.tbAgregar.setObjectName("tbAgregar")
        self.horizontalLayout_52.addWidget(self.tbAgregar)
        self.tbEliminar = QtWidgets.QToolButton(self.topModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbEliminar.sizePolicy().hasHeightForWidth())
        self.tbEliminar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbEliminar.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbEliminar.setIcon(icon5)
        self.tbEliminar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbEliminar.setAutoRaise(True)
        self.tbEliminar.setObjectName("tbEliminar")
        self.horizontalLayout_52.addWidget(self.tbEliminar)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem)
        self.verticalLayout_9.addLayout(self.horizontalLayout_52)
        self.verticalLayout_3.addWidget(self.topModule)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tvTabla = QtWidgets.QTableView(Masul)
        self.tvTabla.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tvTabla.setAlternatingRowColors(True)
        self.tvTabla.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tvTabla.setGridStyle(QtCore.Qt.PenStyle.DashLine)
        self.tvTabla.setSortingEnabled(True)
        self.tvTabla.setObjectName("tvTabla")
        self.tvTabla.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tvTabla)
        self.splitter = QtWidgets.QSplitter(Masul)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.fDatos = QtWidgets.QFrame(self.splitter)
        self.fDatos.setObjectName("fDatos")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fDatos)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblDatos = QtWidgets.QLabel(self.fDatos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDatos.sizePolicy().hasHeightForWidth())
        self.lblDatos.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblDatos.setFont(font)
        self.lblDatos.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblDatos.setWordWrap(True)
        self.lblDatos.setMargin(4)
        self.lblDatos.setObjectName("lblDatos")
        self.verticalLayout_2.addWidget(self.lblDatos)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblInfo = QtWidgets.QLabel(self.fDatos)
        self.lblInfo.setWordWrap(True)
        self.lblInfo.setMargin(3)
        self.lblInfo.setObjectName("lblInfo")
        self.horizontalLayout_3.addWidget(self.lblInfo)
        self.lblLogo = QtWidgets.QLabel(self.fDatos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLogo.sizePolicy().hasHeightForWidth())
        self.lblLogo.setSizePolicy(sizePolicy)
        self.lblLogo.setMaximumSize(QtCore.QSize(16777215, 64))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("../../../../../../../Users/usr/share/pyventa/images/png/64-box_open.png"))
        self.lblLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.horizontalLayout_3.addWidget(self.lblLogo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.frame = QtWidgets.QFrame(self.fDatos)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.inDatos = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inDatos.sizePolicy().hasHeightForWidth())
        self.inDatos.setSizePolicy(sizePolicy)
        self.inDatos.setObjectName("inDatos")
        self.formLay = QtWidgets.QFormLayout(self.inDatos)
        self.formLay.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLay.setObjectName("formLay")
        self.verticalLayout_4.addWidget(self.inDatos)
        self.verticalLayout_2.addWidget(self.frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.splitter)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Masul)
        QtCore.QMetaObject.connectSlotsByName(Masul)

    def retranslateUi(self, Masul):
        Masul.setWindowTitle(QtCore.QCoreApplication.translate("Masul", "Control administrativo"))
        self.tbHome.setText(QtCore.QCoreApplication.translate("Masul", "Tienda"))
        self.tbHome.setShortcut(QtCore.QCoreApplication.translate("Masul", "Home"))
        self.tbLimpiar.setToolTip(QtCore.QCoreApplication.translate("Masul", "Nuevo producto"))
        self.tbLimpiar.setText(QtCore.QCoreApplication.translate("Masul", "&Nuevo"))
        self.tbLimpiar.setShortcut(QtCore.QCoreApplication.translate("Masul", "Ctrl+N"))
        self.tbModif.setToolTip(QtCore.QCoreApplication.translate("Masul", "Guardar"))
        self.tbModif.setText(QtCore.QCoreApplication.translate("Masul", "Guardar"))
        self.tbModif.setShortcut(QtCore.QCoreApplication.translate("Masul", "Ctrl+G"))
        self.tbAgregar.setToolTip(QtCore.QCoreApplication.translate("Masul", "Restaurar"))
        self.tbAgregar.setText(QtCore.QCoreApplication.translate("Masul", "Duplicar"))
        self.tbEliminar.setText(QtCore.QCoreApplication.translate("Masul", "Eliminar"))
        self.lblDatos.setText(QtCore.QCoreApplication.translate("Masul", "Detalle de elemento"))
        self.lblInfo.setText(QtCore.QCoreApplication.translate("Masul", "Titulo del objeto"))
# 
import icons_rc
  # TODO: regenerate with pyrcc6