# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogos/ui_editor_clientes.ui'
#
# Created: Fri Jul  2 20:35:57 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(467, 284)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/pyventa/images/png/64-user_group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_53 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_53)
        self.tnombre = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tnombre.sizePolicy().hasHeightForWidth())
        self.tnombre.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tnombre.setFont(font)
        self.tnombre.setObjectName("tnombre")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.tnombre)
        self.label_54 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_54)
        self.trfc = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trfc.sizePolicy().hasHeightForWidth())
        self.trfc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.trfc.setFont(font)
        self.trfc.setObjectName("trfc")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.trfc)
        self.label_65 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_65)
        self.tdireccion = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tdireccion.sizePolicy().hasHeightForWidth())
        self.tdireccion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tdireccion.setFont(font)
        self.tdireccion.setObjectName("tdireccion")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.tdireccion)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_67 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_67)
        self.tpoblacion = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tpoblacion.sizePolicy().hasHeightForWidth())
        self.tpoblacion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tpoblacion.setFont(font)
        self.tpoblacion.setObjectName("tpoblacion")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.tpoblacion)
        self.label_69 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_69)
        self.tcorreo = QtGui.QLineEdit(Dialog)
        self.tcorreo.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tcorreo.setFont(font)
        self.tcorreo.setObjectName("tcorreo")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.tcorreo)
        self.label_70 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_70)
        self.tdesc = QtGui.QCheckBox(Dialog)
        self.tdesc.setObjectName("tdesc")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.tdesc)
        self.horizontalLayout_40.addLayout(self.formLayout_3)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.testado = QtGui.QLineEdit(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testado.sizePolicy().hasHeightForWidth())
        self.testado.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.testado.setFont(font)
        self.testado.setObjectName("testado")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.testado)
        self.label_68 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_68)
        self.ttelefono = QtGui.QLineEdit(Dialog)
        self.ttelefono.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ttelefono.setFont(font)
        self.ttelefono.setObjectName("ttelefono")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.ttelefono)
        self.label_66 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_66)
        self.label_71 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_71)
        self.tcredito = QtGui.QLineEdit(Dialog)
        self.tcredito.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tcredito.setFont(font)
        self.tcredito.setObjectName("tcredito")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.tcredito)
        self.horizontalLayout_40.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_40)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Editor de clientes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("Dialog", "Nombre o Razon Social", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("Dialog", "RFC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("Dialog", "Direccion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("Dialog", "Poblacion", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("Dialog", "Codigo Postal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("Dialog", "Descuento", None, QtGui.QApplication.UnicodeUTF8))
        self.tdesc.setText(QtGui.QApplication.translate("Dialog", "Aplica mayoreo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("Dialog", "Telefono", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("Dialog", "Estado", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("Dialog", "Credito", None, QtGui.QApplication.UnicodeUTF8))

