# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/dialogos/ui_editor_oferta.ui'
#
# Created: Tue Apr 30 03:13:17 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(797, 503)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../usr/share/pyventa/images/32/box.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Editor.setWindowIcon(icon)
        Editor.setStyleSheet("#Editor{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));}\n"
"QLabel{background:transparent;}\n"
"QLineEdit{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:4px; border-radius:4px;border:1px solid #999\n"
" }\n"
"QTableView,#tabla{background-color: rgb(240, 240, 255);\n"
"border:1px solid rgb(170, 181, 186)}\n"
"")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Editor)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_2 = QtWidgets.QWidget(Editor)
        self.widget_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.titulo = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo.sizePolicy().hasHeightForWidth())
        self.titulo.setSizePolicy(sizePolicy)
        self.titulo.setObjectName("titulo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.titulo)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2.addWidget(self.titulo)
        self.label_19 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.leNombre = QtWidgets.QLineEdit(self.widget_2)
        self.leNombre.setText("")
        self.leNombre.setObjectName("leNombre")
        self.verticalLayout_2.addWidget(self.leNombre)
        self.datos = QtWidgets.QFrame(self.widget_2)
        self.datos.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.datos.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.datos.setObjectName("datos")
        self.gridLayout = QtWidgets.QGridLayout(self.datos)
        self.gridLayout.setObjectName("gridLayout")
        self.label_15 = QtWidgets.QLabel(self.datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.datos)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.deFin = QtWidgets.QDateEdit(self.datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deFin.sizePolicy().hasHeightForWidth())
        self.deFin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deFin.setFont(font)
        self.deFin.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.deFin.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.deFin.setAccelerated(True)
        self.deFin.setCalendarPopup(True)
        self.deFin.setObjectName("deFin")
        self.gridLayout.addWidget(self.deFin, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.datos)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.sbMaximo = QtWidgets.QDoubleSpinBox(self.datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbMaximo.sizePolicy().hasHeightForWidth())
        self.sbMaximo.setSizePolicy(sizePolicy)
        self.sbMaximo.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.sbMaximo.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.sbMaximo.setMaximum(99999.99)
        self.sbMaximo.setSingleStep(0.5)
        self.sbMaximo.setObjectName("sbMaximo")
        self.gridLayout.addWidget(self.sbMaximo, 2, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.sbMinimo = QtWidgets.QDoubleSpinBox(self.datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbMinimo.sizePolicy().hasHeightForWidth())
        self.sbMinimo.setSizePolicy(sizePolicy)
        self.sbMinimo.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.sbMinimo.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.sbMinimo.setMaximum(99999.99)
        self.sbMinimo.setSingleStep(0.5)
        self.sbMinimo.setObjectName("sbMinimo")
        self.gridLayout.addWidget(self.sbMinimo, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.datos)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.deInicio = QtWidgets.QDateEdit(self.datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deInicio.sizePolicy().hasHeightForWidth())
        self.deInicio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deInicio.setFont(font)
        self.deInicio.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.deInicio.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.deInicio.setAccelerated(True)
        self.deInicio.setCalendarPopup(True)
        self.deInicio.setObjectName("deInicio")
        self.gridLayout.addWidget(self.deInicio, 3, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dsDescuento = QtWidgets.QDoubleSpinBox(self.datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsDescuento.sizePolicy().hasHeightForWidth())
        self.dsDescuento.setSizePolicy(sizePolicy)
        self.dsDescuento.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dsDescuento.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.dsDescuento.setAccelerated(True)
        self.dsDescuento.setObjectName("dsDescuento")
        self.horizontalLayout_3.addWidget(self.dsDescuento)
        self.tbCalcDes = QtWidgets.QToolButton(self.datos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbCalcDes.sizePolicy().hasHeightForWidth())
        self.tbCalcDes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tbCalcDes.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/calculator.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbCalcDes.setIcon(icon1)
        self.tbCalcDes.setIconSize(QtCore.QSize(18, 18))
        self.tbCalcDes.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbCalcDes.setObjectName("tbCalcDes")
        self.horizontalLayout_3.addWidget(self.tbCalcDes)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.datos)
        self.tools = QtWidgets.QWidget(self.widget_2)
        self.tools.setObjectName("tools")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tools)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.extraTool = QtWidgets.QVBoxLayout()
        self.extraTool.setObjectName("extraTool")
        self.verticalLayout_5.addLayout(self.extraTool)
        self.verticalLayout_2.addWidget(self.tools)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tbPublicar = QtWidgets.QToolButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbPublicar.sizePolicy().hasHeightForWidth())
        self.tbPublicar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tbPublicar.setFont(font)
        self.tbPublicar.setStyleSheet("QToolButton, QAbstractButton{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(10, 125, 159, 255), stop:1 rgba(0, 188, 255, 255));color:#fff;\n"
"border-radius:4px;border:1px solid #777; padding:2 9 2 9;\n"
"}\n"
"QAbstractButton::pressed{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 66, 255, 255), stop:1 rgba(0, 107, 227, 255));\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/checkmark2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbPublicar.setIcon(icon2)
        self.tbPublicar.setIconSize(QtCore.QSize(16, 16))
        self.tbPublicar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbPublicar.setObjectName("tbPublicar")
        self.horizontalLayout_2.addWidget(self.tbPublicar)
        self.tbCerrar = QtWidgets.QToolButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbCerrar.sizePolicy().hasHeightForWidth())
        self.tbCerrar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tbCerrar.setFont(font)
        self.tbCerrar.setStyleSheet("QToolButton, QAbstractButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));\n"
"border-radius:4px;border:1px solid #777; padding:2 9 2 9;color:#333;\n"
"}\n"
"QAbstractButton::pressed{\n"
"color:#fff;\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 66, 255, 255), stop:1 rgba(0, 107, 227, 255));\n"
"\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbCerrar.setIcon(icon3)
        self.tbCerrar.setIconSize(QtCore.QSize(12, 16))
        self.tbCerrar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbCerrar.setObjectName("tbCerrar")
        self.horizontalLayout_2.addWidget(self.tbCerrar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(Editor)
        self.widget.setStyleSheet("background:none")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabla = QtWidgets.QTableView(self.widget)
        self.tabla.setAlternatingRowColors(True)
        self.tabla.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tabla.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tabla.setSortingEnabled(True)
        self.tabla.setObjectName("tabla")
        self.verticalLayout.addWidget(self.tabla)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.masomenos = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.masomenos.sizePolicy().hasHeightForWidth())
        self.masomenos.setSizePolicy(sizePolicy)
        self.masomenos.setMaximumSize(QtCore.QSize(16777215, 22))
        self.masomenos.setStyleSheet("#masomenos{border-radius:0px;padding:2;\n"
"border: 1.2px solid #999;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));}\n"
"QToolButton::hover{\n"
"    background-color:rgba(133, 217, 255, 100);\n"
"}\n"
"QToolButton::pressed{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(239, 239, 239, 27), stop:1 rgba(68, 68, 68, 205));\n"
"}\n"
" \n"
"")
        self.masomenos.setObjectName("masomenos")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.masomenos)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tbMenos = QtWidgets.QToolButton(self.masomenos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbMenos.sizePolicy().hasHeightForWidth())
        self.tbMenos.setSizePolicy(sizePolicy)
        self.tbMenos.setStyleSheet(" border:0px; padding:5 5 5 7;border-right:1px solid #999;border-radius:0;\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbMenos.setIcon(icon4)
        self.tbMenos.setIconSize(QtCore.QSize(18, 18))
        self.tbMenos.setObjectName("tbMenos")
        self.horizontalLayout_13.addWidget(self.tbMenos)
        self.tbMas = QtWidgets.QToolButton(self.masomenos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbMas.sizePolicy().hasHeightForWidth())
        self.tbMas.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tbMas.setFont(font)
        self.tbMas.setStyleSheet(" border:0px;\n"
"padding:5 5 5 7;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbMas.setIcon(icon5)
        self.tbMas.setIconSize(QtCore.QSize(18, 18))
        self.tbMas.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbMas.setObjectName("tbMas")
        self.horizontalLayout_13.addWidget(self.tbMas)
        self.horizontalLayout.addWidget(self.masomenos)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addWidget(self.widget)

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)
        Editor.setTabOrder(self.leNombre, self.dsDescuento)
        Editor.setTabOrder(self.dsDescuento, self.sbMinimo)
        Editor.setTabOrder(self.sbMinimo, self.sbMaximo)
        Editor.setTabOrder(self.sbMaximo, self.deInicio)
        Editor.setTabOrder(self.deInicio, self.deFin)
        Editor.setTabOrder(self.deFin, self.tbMas)
        Editor.setTabOrder(self.tbMas, self.tabla)
        Editor.setTabOrder(self.tabla, self.tbMenos)
        Editor.setTabOrder(self.tbMenos, self.tbPublicar)
        Editor.setTabOrder(self.tbPublicar, self.tbCerrar)
        Editor.setTabOrder(self.tbCerrar, self.tbCalcDes)

    def retranslateUi(self, Editor):
        Editor.setWindowTitle(QtCore.QCoreApplication.translate("Editor", "Editor de ofertas"))
        self.label.setText(QtCore.QCoreApplication.translate("Editor", "Editor de Oferta"))
        self.label_19.setText(QtCore.QCoreApplication.translate("Editor", "Nombre: "))
        self.label_15.setText(QtCore.QCoreApplication.translate("Editor", "Inicia:"))
        self.label_4.setText(QtCore.QCoreApplication.translate("Editor", "Cantidad maxima:"))
        self.deFin.setToolTip(QtCore.QCoreApplication.translate("Editor", "Fecha en que caduca la oferta"))
        self.deFin.setDisplayFormat(QtCore.QCoreApplication.translate("Editor", "dd MMM yy    "))
        self.label_5.setText(QtCore.QCoreApplication.translate("Editor", "Descuento:"))
        self.label_16.setText(QtCore.QCoreApplication.translate("Editor", "Vence:"))
        self.label_3.setText(QtCore.QCoreApplication.translate("Editor", "Cantidad minima:"))
        self.deInicio.setToolTip(QtCore.QCoreApplication.translate("Editor", "Fecha en que comenzara a aplicarse la oferta"))
        self.deInicio.setDisplayFormat(QtCore.QCoreApplication.translate("Editor", "dd MMM yy    "))
        self.dsDescuento.setSuffix(QtCore.QCoreApplication.translate("Editor", "%"))
        self.tbCalcDes.setToolTip(QtCore.QCoreApplication.translate("Editor", "Calcular porcentaje de descuento."))
        self.tbCalcDes.setText(QtCore.QCoreApplication.translate("Editor", "Calcular"))
        self.tbPublicar.setText(QtCore.QCoreApplication.translate("Editor", "Publicar"))
        self.tbCerrar.setText(QtCore.QCoreApplication.translate("Editor", "Cerrar"))
        self.tbMenos.setToolTip(QtCore.QCoreApplication.translate("Editor", "Quitar de la lista"))
        self.tbMenos.setText(QtCore.QCoreApplication.translate("Editor", "Quitar"))
        self.tbMas.setToolTip(QtCore.QCoreApplication.translate("Editor", "Incluir articulos a la oferta"))
        self.tbMas.setText(QtCore.QCoreApplication.translate("Editor", "Agregar"))
# 
import icons_rc
  # TODO: regenerate with pyrcc6