# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/dialogos/ui_editor_oferta.ui'
#
# Created: Tue Apr  2 13:06:47 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName(_fromUtf8("Editor"))
        Editor.resize(715, 515)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/32/box.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Editor.setWindowIcon(icon)
        Editor.setStyleSheet(_fromUtf8("#Editor{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));}\n"
"QLabel{background:transparent;}\n"
"QLineEdit{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:4px; border-radius:4px;border:1px solid #999\n"
" }\n"
"QTableView,#tabla{background-color: rgb(240, 240, 255);\n"
"border:1px solid rgb(170, 181, 186)}\n"
""))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(Editor)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.widget_2 = QtGui.QWidget(Editor)
        self.widget_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.titulo = QtGui.QWidget(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo.sizePolicy().hasHeightForWidth())
        self.titulo.setSizePolicy(sizePolicy)
        self.titulo.setObjectName(_fromUtf8("titulo"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.titulo)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3.addWidget(self.titulo)
        self.label_19 = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_3.addWidget(self.label_19)
        self.leNombre = QtGui.QLineEdit(self.widget_2)
        self.leNombre.setText(_fromUtf8(""))
        self.leNombre.setObjectName(_fromUtf8("leNombre"))
        self.verticalLayout_3.addWidget(self.leNombre)
        self.datos = QtGui.QFrame(self.widget_2)
        self.datos.setFrameShape(QtGui.QFrame.StyledPanel)
        self.datos.setFrameShadow(QtGui.QFrame.Raised)
        self.datos.setObjectName(_fromUtf8("datos"))
        self.gridLayout = QtGui.QGridLayout(self.datos)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_15 = QtGui.QLabel(self.datos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.datos)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.deFin = QtGui.QDateEdit(self.datos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deFin.sizePolicy().hasHeightForWidth())
        self.deFin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deFin.setFont(font)
        self.deFin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.deFin.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.deFin.setAccelerated(True)
        self.deFin.setCalendarPopup(True)
        self.deFin.setObjectName(_fromUtf8("deFin"))
        self.gridLayout.addWidget(self.deFin, 4, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.datos)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.sbMaximo = QtGui.QDoubleSpinBox(self.datos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbMaximo.sizePolicy().hasHeightForWidth())
        self.sbMaximo.setSizePolicy(sizePolicy)
        self.sbMaximo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbMaximo.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.sbMaximo.setMaximum(99999.99)
        self.sbMaximo.setSingleStep(0.5)
        self.sbMaximo.setObjectName(_fromUtf8("sbMaximo"))
        self.gridLayout.addWidget(self.sbMaximo, 2, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.datos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.sbMinimo = QtGui.QDoubleSpinBox(self.datos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbMinimo.sizePolicy().hasHeightForWidth())
        self.sbMinimo.setSizePolicy(sizePolicy)
        self.sbMinimo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbMinimo.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.sbMinimo.setMaximum(99999.99)
        self.sbMinimo.setSingleStep(0.5)
        self.sbMinimo.setObjectName(_fromUtf8("sbMinimo"))
        self.gridLayout.addWidget(self.sbMinimo, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.datos)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.deInicio = QtGui.QDateEdit(self.datos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deInicio.sizePolicy().hasHeightForWidth())
        self.deInicio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deInicio.setFont(font)
        self.deInicio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.deInicio.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.deInicio.setAccelerated(True)
        self.deInicio.setCalendarPopup(True)
        self.deInicio.setObjectName(_fromUtf8("deInicio"))
        self.gridLayout.addWidget(self.deInicio, 3, 2, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.dsDescuento = QtGui.QDoubleSpinBox(self.datos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsDescuento.sizePolicy().hasHeightForWidth())
        self.dsDescuento.setSizePolicy(sizePolicy)
        self.dsDescuento.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsDescuento.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dsDescuento.setAccelerated(True)
        self.dsDescuento.setObjectName(_fromUtf8("dsDescuento"))
        self.horizontalLayout_3.addWidget(self.dsDescuento)
        self.tbCalcDes = QtGui.QToolButton(self.datos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbCalcDes.sizePolicy().hasHeightForWidth())
        self.tbCalcDes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tbCalcDes.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/calculator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbCalcDes.setIcon(icon1)
        self.tbCalcDes.setIconSize(QtCore.QSize(18, 18))
        self.tbCalcDes.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbCalcDes.setObjectName(_fromUtf8("tbCalcDes"))
        self.horizontalLayout_3.addWidget(self.tbCalcDes)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.datos)
        self.tools = QtGui.QWidget(self.widget_2)
        self.tools.setObjectName(_fromUtf8("tools"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tools)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.extraTool = QtGui.QVBoxLayout()
        self.extraTool.setObjectName(_fromUtf8("extraTool"))
        self.verticalLayout_5.addLayout(self.extraTool)
        self.verticalLayout_3.addWidget(self.tools)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Dual_3 = QtGui.QSplitter(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dual_3.sizePolicy().hasHeightForWidth())
        self.Dual_3.setSizePolicy(sizePolicy)
        self.Dual_3.setStyleSheet(_fromUtf8("QSplitter{border-radius:4px;\n"
"border: 1.2px solid #999;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));}\n"
"QToolButton::hover{\n"
"    background-color:rgba(133, 217, 255, 100);\n"
"}\n"
"QToolButton::pressed{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(239, 239, 239, 27), stop:1 rgba(68, 68, 68, 205));\n"
"}\n"
"QToolButton{padding:4px}\n"
" \n"
""))
        self.Dual_3.setLineWidth(0)
        self.Dual_3.setMidLineWidth(1)
        self.Dual_3.setOrientation(QtCore.Qt.Horizontal)
        self.Dual_3.setHandleWidth(1)
        self.Dual_3.setObjectName(_fromUtf8("Dual_3"))
        self.tbCerrar = QtGui.QToolButton(self.Dual_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbCerrar.sizePolicy().hasHeightForWidth())
        self.tbCerrar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tbCerrar.setFont(font)
        self.tbCerrar.setStyleSheet(_fromUtf8(" border:0px;border-right:1px solid #999;border-radius:0;\n"
""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbCerrar.setIcon(icon2)
        self.tbCerrar.setIconSize(QtCore.QSize(12, 16))
        self.tbCerrar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbCerrar.setObjectName(_fromUtf8("tbCerrar"))
        self.tbPublicar = QtGui.QToolButton(self.Dual_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbPublicar.sizePolicy().hasHeightForWidth())
        self.tbPublicar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tbPublicar.setFont(font)
        self.tbPublicar.setStyleSheet(_fromUtf8(" border:0px;\n"
""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/checkmark2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPublicar.setIcon(icon3)
        self.tbPublicar.setIconSize(QtCore.QSize(16, 16))
        self.tbPublicar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbPublicar.setObjectName(_fromUtf8("tbPublicar"))
        self.horizontalLayout_2.addWidget(self.Dual_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addWidget(self.widget_2)
        self.widget = QtGui.QWidget(Editor)
        self.widget.setStyleSheet(_fromUtf8("background:none"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabla = QtGui.QTableView(self.widget)
        self.tabla.setAlternatingRowColors(True)
        self.tabla.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tabla.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabla.setSortingEnabled(True)
        self.tabla.setObjectName(_fromUtf8("tabla"))
        self.verticalLayout.addWidget(self.tabla)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.masomenos = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.masomenos.sizePolicy().hasHeightForWidth())
        self.masomenos.setSizePolicy(sizePolicy)
        self.masomenos.setMaximumSize(QtCore.QSize(16777215, 22))
        self.masomenos.setStyleSheet(_fromUtf8("#masomenos{border-radius:0px;padding:2;\n"
"border: 1.2px solid #999;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));}\n"
"QToolButton::hover{\n"
"    background-color:rgba(133, 217, 255, 100);\n"
"}\n"
"QToolButton::pressed{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(239, 239, 239, 27), stop:1 rgba(68, 68, 68, 205));\n"
"}\n"
" \n"
""))
        self.masomenos.setObjectName(_fromUtf8("masomenos"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.masomenos)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.tbMenos = QtGui.QToolButton(self.masomenos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbMenos.sizePolicy().hasHeightForWidth())
        self.tbMenos.setSizePolicy(sizePolicy)
        self.tbMenos.setStyleSheet(_fromUtf8(" border:0px; padding:5 5 5 7;border-right:1px solid #999;border-radius:0;\n"
""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbMenos.setIcon(icon4)
        self.tbMenos.setIconSize(QtCore.QSize(18, 18))
        self.tbMenos.setObjectName(_fromUtf8("tbMenos"))
        self.horizontalLayout_13.addWidget(self.tbMenos)
        self.tbMas = QtGui.QToolButton(self.masomenos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbMas.sizePolicy().hasHeightForWidth())
        self.tbMas.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tbMas.setFont(font)
        self.tbMas.setStyleSheet(_fromUtf8(" border:0px;\n"
"padding:5 5 5 7;"))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbMas.setIcon(icon5)
        self.tbMas.setIconSize(QtCore.QSize(18, 18))
        self.tbMas.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbMas.setObjectName(_fromUtf8("tbMas"))
        self.horizontalLayout_13.addWidget(self.tbMas)
        self.horizontalLayout.addWidget(self.masomenos)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addWidget(self.widget)

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)

    def retranslateUi(self, Editor):
        Editor.setWindowTitle(QtGui.QApplication.translate("Editor", "Editor de ofertas", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Editor", "Editor de Oferta", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Editor", "Nombre: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Editor", "Inicia:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Editor", "Cantidad maxima:", None, QtGui.QApplication.UnicodeUTF8))
        self.deFin.setToolTip(QtGui.QApplication.translate("Editor", "Fecha en que caduca la oferta", None, QtGui.QApplication.UnicodeUTF8))
        self.deFin.setDisplayFormat(QtGui.QApplication.translate("Editor", "dd MMM yy    ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Editor", "Descuento:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Editor", "Vence:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Editor", "Cantidad minima:", None, QtGui.QApplication.UnicodeUTF8))
        self.deInicio.setToolTip(QtGui.QApplication.translate("Editor", "Fecha en que comenzara a aplicarse la oferta", None, QtGui.QApplication.UnicodeUTF8))
        self.deInicio.setDisplayFormat(QtGui.QApplication.translate("Editor", "dd MMM yy    ", None, QtGui.QApplication.UnicodeUTF8))
        self.dsDescuento.setSuffix(QtGui.QApplication.translate("Editor", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCalcDes.setToolTip(QtGui.QApplication.translate("Editor", "Calcular porcentaje de descuento.", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCalcDes.setText(QtGui.QApplication.translate("Editor", "Calcular", None, QtGui.QApplication.UnicodeUTF8))
        self.tbCerrar.setText(QtGui.QApplication.translate("Editor", "Cerrar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPublicar.setText(QtGui.QApplication.translate("Editor", "Publicar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMenos.setToolTip(QtGui.QApplication.translate("Editor", "Quitar de la lista", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMenos.setText(QtGui.QApplication.translate("Editor", "Quitar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMas.setToolTip(QtGui.QApplication.translate("Editor", "Incluir articulos a la oferta", None, QtGui.QApplication.UnicodeUTF8))
        self.tbMas.setText(QtGui.QApplication.translate("Editor", "Agregar", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
