# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui_nueva_lista.ui'
#
# Created: Tue Aug 16 04:18:43 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(605, 566)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_17 = QtWidgets.QWidget(Form)
        self.widget_17.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_17.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_17.setStyleSheet("*{background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(13, 13, 13, 255), stop:0.504545 rgba(0, 0, 0, 255), stop:0.507692 rgba(27, 27, 27, 255), stop:1 rgba(69, 69, 69, 255));color: rgb(255, 255, 255);font-weight:700;}\n"
"QLabel{background:rgba(0,0,0,0)}")
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_66.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.lblLogo = QtWidgets.QLabel(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLogo.sizePolicy().hasHeightForWidth())
        self.lblLogo.setSizePolicy(sizePolicy)
        self.lblLogo.setMaximumSize(QtCore.QSize(32, 32))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("../../../../../../../usr/share/pyventa/images/png/Basket-64.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setObjectName("lblLogo")
        self.horizontalLayout_66.addWidget(self.lblLogo)
        self.lbTitulo = QtWidgets.QLabel(self.widget_17)
        font = QtGui.QFont()
        font.setWeight(87)
        font.setBold(True)
        self.lbTitulo.setFont(font)
        self.lbTitulo.setObjectName("lbTitulo")
        self.horizontalLayout_66.addWidget(self.lbTitulo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_66.addItem(spacerItem)
        self.widget_18 = QtWidgets.QWidget(self.widget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(87)
        font.setBold(True)
        self.widget_18.setFont(font)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_67.setSpacing(2)
        self.horizontalLayout_67.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.tbCancelar = QtWidgets.QToolButton(self.widget_18)
        font = QtGui.QFont()
        font.setWeight(87)
        font.setBold(True)
        self.tbCancelar.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../usr/share/pyventa/images/32/silver/cancelar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbCancelar.setIcon(icon)
        self.tbCancelar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbCancelar.setObjectName("tbCancelar")
        self.horizontalLayout_67.addWidget(self.tbCancelar)
        self.label_129 = QtWidgets.QLabel(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_129.sizePolicy().hasHeightForWidth())
        self.label_129.setSizePolicy(sizePolicy)
        self.label_129.setMaximumSize(QtCore.QSize(20, 60))
        self.label_129.setText("")
        self.label_129.setPixmap(QtGui.QPixmap("../../../../../usr/share/pyventa/images/fx/separation.png"))
        self.label_129.setScaledContents(True)
        self.label_129.setObjectName("label_129")
        self.horizontalLayout_67.addWidget(self.label_129)
        self.tbGuardar = QtWidgets.QToolButton(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbGuardar.sizePolicy().hasHeightForWidth())
        self.tbGuardar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(87)
        font.setBold(True)
        self.tbGuardar.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../usr/share/pyventa/images/32/Check-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbGuardar.setIcon(icon1)
        self.tbGuardar.setIconSize(QtCore.QSize(24, 24))
        self.tbGuardar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbGuardar.setObjectName("tbGuardar")
        self.horizontalLayout_67.addWidget(self.tbGuardar)
        self.toolButton_14 = QtWidgets.QToolButton(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_14.sizePolicy().hasHeightForWidth())
        self.toolButton_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(87)
        font.setBold(True)
        self.toolButton_14.setFont(font)
        self.toolButton_14.setText("")
        self.toolButton_14.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_14.setObjectName("toolButton_14")
        self.horizontalLayout_67.addWidget(self.toolButton_14)
        self.horizontalLayout_66.addWidget(self.widget_18)
        self.verticalLayout.addWidget(self.widget_17)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("#frame {background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(158, 158, 158, 255), stop:0.43 rgba(163, 163, 163, 255), stop:1 rgba(124, 124, 124, 255));}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.leCodigo = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.leCodigo.setFont(font)
        self.leCodigo.setStyleSheet("border:1px solid #999; border-radius:7px; padding:5px; \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(41, 41, 41, 255), stop:0.05 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.leCodigo.setObjectName("leCodigo")
        self.gridLayout.addWidget(self.leCodigo, 1, 1, 1, 1)
        self.pbAgregar = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbAgregar.sizePolicy().hasHeightForWidth())
        self.pbAgregar.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../../usr/share/pyventa/images/32/Add-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbAgregar.setIcon(icon2)
        self.pbAgregar.setIconSize(QtCore.QSize(32, 32))
        self.pbAgregar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.pbAgregar.setAutoRaise(True)
        self.pbAgregar.setObjectName("pbAgregar")
        self.gridLayout.addWidget(self.pbAgregar, 1, 6, 1, 1)
        self.tbCambiar = QtWidgets.QToolButton(self.frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../../usr/share/pyventa/images/32/Synchronize-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbCambiar.setIcon(icon3)
        self.tbCambiar.setIconSize(QtCore.QSize(32, 32))
        self.tbCambiar.setAutoRaise(True)
        self.tbCambiar.setObjectName("tbCambiar")
        self.gridLayout.addWidget(self.tbCambiar, 1, 7, 1, 1)
        self.leCantidad = QtWidgets.QLineEdit(self.frame)
        self.leCantidad.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.leCantidad.setFont(font)
        self.leCantidad.setStyleSheet("border:1px solid #999; border-radius:7px; padding:5px; \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(41, 41, 41, 255), stop:0.05 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.leCantidad.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.leCantidad.setObjectName("leCantidad")
        self.gridLayout.addWidget(self.leCantidad, 1, 5, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.frame)
        self.label_60.setObjectName("label_60")
        self.gridLayout.addWidget(self.label_60, 0, 5, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.frame)
        self.label_58.setObjectName("label_58")
        self.gridLayout.addWidget(self.label_58, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.tabla = QtWidgets.QTableView(Form)
        self.tabla.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.677455, cy:0.659, radius:1.377, fx:0.149545, fy:0.244, stop:0.00454545 rgba(201, 215, 215, 255), stop:0.672727 rgba(255, 255, 255, 255), stop:1 rgba(181, 199, 223, 255));")
        self.tabla.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tabla.setAlternatingRowColors(True)
        self.tabla.setObjectName("tabla")
        self.tabla.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.tabla)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.leCodigo, self.leCantidad)
        Form.setTabOrder(self.leCantidad, self.pbAgregar)
        Form.setTabOrder(self.pbAgregar, self.tbCambiar)
        Form.setTabOrder(self.tbCambiar, self.tabla)
        Form.setTabOrder(self.tabla, self.tbCancelar)
        Form.setTabOrder(self.tbCancelar, self.toolButton_14)
        Form.setTabOrder(self.toolButton_14, self.tbGuardar)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtCore.QCoreApplication.translate("Form", "Form"))
        self.lbTitulo.setStyleSheet(QtCore.QCoreApplication.translate("Form", "background:none"))
        self.lbTitulo.setText(QtCore.QCoreApplication.translate("Form", "Nueva compra"))
        self.widget_18.setStyleSheet(QtWidgets.QApplication.translate("Form", "border-radius:9px;\n"
"border: 2px solid #000;", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tbCancelar.setStyleSheet(QtCore.QCoreApplication.translate("Form", " border:0px; background:none"))
        self.tbCancelar.setText(QtCore.QCoreApplication.translate("Form", "Cancelar"))
        self.label_129.setStyleSheet(QtCore.QCoreApplication.translate("Form", "background:none;border:0px"))
        self.tbGuardar.setStyleSheet(QtCore.QCoreApplication.translate("Form", " border:0px; background:none"))
        self.tbGuardar.setText(QtCore.QCoreApplication.translate("Form", "Guardar"))
        self.toolButton_14.setStyleSheet(QtCore.QCoreApplication.translate("Form", " border:0px; background:none"))
        self.pbAgregar.setToolTip(QtCore.QCoreApplication.translate("Form", "Agregar a la compra"))
        self.pbAgregar.setText(QtCore.QCoreApplication.translate("Form", "Agregar"))
        self.pbAgregar.setShortcut(QtCore.QCoreApplication.translate("Form", "Ins"))
        self.tbCambiar.setToolTip(QtCore.QCoreApplication.translate("Form", "Cambiar precio y agregar"))
        self.tbCambiar.setText(QtCore.QCoreApplication.translate("Form", "Calcular"))
        self.leCantidad.setText(QtCore.QCoreApplication.translate("Form", "1.00"))
        self.label_60.setText(QtCore.QCoreApplication.translate("Form", "Cantidad"))
        self.label_58.setText(QtCore.QCoreApplication.translate("Form", "Producto"))

