# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/modulos/ui_pendientes.ui'
#
# Created: Sat Mar 30 22:31:51 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(652, 516)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.top = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top.sizePolicy().hasHeightForWidth())
        self.top.setSizePolicy(sizePolicy)
        self.top.setObjectName(_fromUtf8("top"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.top)
        self.horizontalLayout_2.setContentsMargins(5, 0, -1, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.titulo = QtGui.QLabel(self.top)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo.sizePolicy().hasHeightForWidth())
        self.titulo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setMargin(5)
        self.titulo.setObjectName(_fromUtf8("titulo"))
        self.horizontalLayout_2.addWidget(self.titulo)
        self.verticalLayout_3.addWidget(self.top)
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget1 = QtGui.QWidget(self.widget)
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bScliente = QtGui.QToolButton(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bScliente.sizePolicy().hasHeightForWidth())
        self.bScliente.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/user_woman.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bScliente.setIcon(icon)
        self.bScliente.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bScliente.setObjectName(_fromUtf8("bScliente"))
        self.gridLayout.addWidget(self.bScliente, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.leNumero = QtGui.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.leNumero.setFont(font)
        self.leNumero.setObjectName(_fromUtf8("leNumero"))
        self.gridLayout.addWidget(self.leNumero, 0, 1, 1, 1)
        self.cbTipo = QtGui.QComboBox(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTipo.sizePolicy().hasHeightForWidth())
        self.cbTipo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbTipo.setFont(font)
        self.cbTipo.setStyleSheet(_fromUtf8(""))
        self.cbTipo.setObjectName(_fromUtf8("cbTipo"))
        self.cbTipo.addItem(_fromUtf8(""))
        self.cbTipo.addItem(_fromUtf8(""))
        self.cbTipo.addItem(_fromUtf8(""))
        self.cbTipo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbTipo, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.widget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.toolButton = QtGui.QToolButton(self.widget1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/group.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout.addWidget(self.toolButton, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pbLimpiar = QtGui.QPushButton(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbLimpiar.sizePolicy().hasHeightForWidth())
        self.pbLimpiar.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbLimpiar.setIcon(icon2)
        self.pbLimpiar.setObjectName(_fromUtf8("pbLimpiar"))
        self.horizontalLayout.addWidget(self.pbLimpiar)
        self.ncactualizar = QtGui.QToolButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ncactualizar.setFont(font)
        self.ncactualizar.setStyleSheet(_fromUtf8("QPushButton{background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(137, 137, 137, 255), stop:0.0545455 rgba(156, 156, 156, 255), stop:1 rgba(191, 191, 191, 255));border:1.3px solid #999; border-radius:12px; color:#555;padding:5;}\n"
"QPushButton::hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(216, 216, 216, 255), stop:0.495455 rgba(229, 229, 229, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ncactualizar.setIcon(icon3)
        self.ncactualizar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.ncactualizar.setObjectName(_fromUtf8("ncactualizar"))
        self.horizontalLayout.addWidget(self.ncactualizar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.widget1)
        self.nctotal = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nctotal.sizePolicy().hasHeightForWidth())
        self.nctotal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nctotal.setFont(font)
        self.nctotal.setTextFormat(QtCore.Qt.PlainText)
        self.nctotal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nctotal.setWordWrap(True)
        self.nctotal.setMargin(3)
        self.nctotal.setObjectName(_fromUtf8("nctotal"))
        self.verticalLayout_2.addWidget(self.nctotal)
        self.teResultados = QtGui.QTextEdit(self.widget)
        self.teResultados.setReadOnly(True)
        self.teResultados.setObjectName(_fromUtf8("teResultados"))
        self.verticalLayout_2.addWidget(self.teResultados)
        self.tvCuentas = QtGui.QTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvCuentas.sizePolicy().hasHeightForWidth())
        self.tvCuentas.setSizePolicy(sizePolicy)
        self.tvCuentas.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tvCuentas.setFont(font)
        self.tvCuentas.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tvCuentas.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tvCuentas.setSortingEnabled(True)
        self.tvCuentas.setObjectName(_fromUtf8("tvCuentas"))
        self.tvCuentas.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(Form)
        self.cbTipo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.titulo.setText(QtGui.QApplication.translate("Form", "Cuentas pendientes", None, QtGui.QApplication.UnicodeUTF8))
        self.bScliente.setToolTip(QtGui.QApplication.translate("Form", "Selecciona un cliente para mostrar el historial de \n"
"ventas en credito de ese cliente en particular.", None, QtGui.QApplication.UnicodeUTF8))
        self.bScliente.setText(QtGui.QApplication.translate("Form", "Seleccione cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Venta:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTipo.setToolTip(QtGui.QApplication.translate("Form", "Muestra la tabla de notas y/o facturas sin pagar del dia en curso.", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTipo.setItemText(0, QtGui.QApplication.translate("Form", "Todas las ventas", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTipo.setItemText(1, QtGui.QApplication.translate("Form", "Notas", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTipo.setItemText(2, QtGui.QApplication.translate("Form", "Facturas", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTipo.setItemText(3, QtGui.QApplication.translate("Form", "Compras", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Cliente:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Formato:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("Form", "Todos los clientes", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLimpiar.setText(QtGui.QApplication.translate("Form", "Limpiar", None, QtGui.QApplication.UnicodeUTF8))
        self.ncactualizar.setText(QtGui.QApplication.translate("Form", "Actualizar listado", None, QtGui.QApplication.UnicodeUTF8))
        self.nctotal.setText(QtGui.QApplication.translate("Form", "Total:", None, QtGui.QApplication.UnicodeUTF8))
        self.tvCuentas.setToolTip(QtGui.QApplication.translate("Form", "Tabla de cuentas sin pagar", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
