# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/modulos/ui_pendientes.ui'
#
# Created: Sat Mar 30 22:31:51 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(652, 516)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top.sizePolicy().hasHeightForWidth())
        self.top.setSizePolicy(sizePolicy)
        self.top.setObjectName("top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout_2.setContentsMargins(5, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.titulo = QtWidgets.QLabel(self.top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo.sizePolicy().hasHeightForWidth())
        self.titulo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setMargin(5)
        self.titulo.setObjectName("titulo")
        self.horizontalLayout_2.addWidget(self.titulo)
        self.verticalLayout_3.addWidget(self.top)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bScliente = QtWidgets.QToolButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bScliente.sizePolicy().hasHeightForWidth())
        self.bScliente.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/user_woman.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bScliente.setIcon(icon)
        self.bScliente.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bScliente.setObjectName("bScliente")
        self.gridLayout.addWidget(self.bScliente, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.leNumero = QtWidgets.QLineEdit(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.leNumero.setFont(font)
        self.leNumero.setObjectName("leNumero")
        self.gridLayout.addWidget(self.leNumero, 0, 1, 1, 1)
        self.cbTipo = QtWidgets.QComboBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTipo.sizePolicy().hasHeightForWidth())
        self.cbTipo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbTipo.setFont(font)
        self.cbTipo.setStyleSheet("")
        self.cbTipo.setObjectName("cbTipo")
        self.cbTipo.addItem("")
        self.cbTipo.addItem("")
        self.cbTipo.addItem("")
        self.cbTipo.addItem("")
        self.gridLayout.addWidget(self.cbTipo, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.widget1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/group.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbLimpiar = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbLimpiar.sizePolicy().hasHeightForWidth())
        self.pbLimpiar.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/cancel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbLimpiar.setIcon(icon2)
        self.pbLimpiar.setObjectName("pbLimpiar")
        self.horizontalLayout.addWidget(self.pbLimpiar)
        self.ncactualizar = QtWidgets.QToolButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ncactualizar.setFont(font)
        self.ncactualizar.setStyleSheet("QPushButton{background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(137, 137, 137, 255), stop:0.0545455 rgba(156, 156, 156, 255), stop:1 rgba(191, 191, 191, 255));border:1.3px solid #999; border-radius:12px; color:#555;padding:5;}\n"
"QPushButton::hover{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(216, 216, 216, 255), stop:0.495455 rgba(229, 229, 229, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/reload.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ncactualizar.setIcon(icon3)
        self.ncactualizar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.ncactualizar.setObjectName("ncactualizar")
        self.horizontalLayout.addWidget(self.ncactualizar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.widget1)
        self.nctotal = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nctotal.sizePolicy().hasHeightForWidth())
        self.nctotal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nctotal.setFont(font)
        self.nctotal.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.nctotal.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.nctotal.setWordWrap(True)
        self.nctotal.setMargin(3)
        self.nctotal.setObjectName("nctotal")
        self.verticalLayout_2.addWidget(self.nctotal)
        self.teResultados = QtWidgets.QTextEdit(self.widget)
        self.teResultados.setReadOnly(True)
        self.teResultados.setObjectName("teResultados")
        self.verticalLayout_2.addWidget(self.teResultados)
        self.tvCuentas = QtWidgets.QTableView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvCuentas.sizePolicy().hasHeightForWidth())
        self.tvCuentas.setSizePolicy(sizePolicy)
        self.tvCuentas.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tvCuentas.setFont(font)
        self.tvCuentas.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tvCuentas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tvCuentas.setSortingEnabled(True)
        self.tvCuentas.setObjectName("tvCuentas")
        self.tvCuentas.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(Form)
        self.cbTipo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtCore.QCoreApplication.translate("Form", "Form"))
        self.titulo.setText(QtCore.QCoreApplication.translate("Form", "Cuentas pendientes"))
        self.bScliente.setToolTip(QtWidgets.QApplication.translate("Form", "Selecciona un cliente para mostrar el historial de \n"
"ventas en credito de ese cliente en particular.", None, QtWidgets.QApplication.UnicodeUTF8))
        self.bScliente.setText(QtCore.QCoreApplication.translate("Form", "Seleccione cliente"))
        self.label_2.setText(QtCore.QCoreApplication.translate("Form", "Venta:"))
        self.cbTipo.setToolTip(QtCore.QCoreApplication.translate("Form", "Muestra la tabla de notas y/o facturas sin pagar del dia en curso."))
        self.cbTipo.setItemText(0, QtCore.QCoreApplication.translate("Form", "Todas las ventas"))
        self.cbTipo.setItemText(1, QtCore.QCoreApplication.translate("Form", "Notas"))
        self.cbTipo.setItemText(2, QtCore.QCoreApplication.translate("Form", "Facturas"))
        self.cbTipo.setItemText(3, QtCore.QCoreApplication.translate("Form", "Compras"))
        self.label_3.setText(QtCore.QCoreApplication.translate("Form", "Cliente:"))
        self.label.setText(QtCore.QCoreApplication.translate("Form", "Formato:"))
        self.toolButton.setText(QtCore.QCoreApplication.translate("Form", "Todos los clientes"))
        self.pbLimpiar.setText(QtCore.QCoreApplication.translate("Form", "Limpiar"))
        self.ncactualizar.setText(QtCore.QCoreApplication.translate("Form", "Actualizar listado"))
        self.nctotal.setText(QtCore.QCoreApplication.translate("Form", "Total:"))
        self.tvCuentas.setToolTip(QtCore.QCoreApplication.translate("Form", "Tabla de cuentas sin pagar"))
# 
import icons_rc
  # TODO: regenerate with pyrcc6