# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/ui_pyventa.ui'
#
# Created: Mon May 13 19:35:04 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Principal(object):
    def setupUi(self, Principal):
        Principal.setObjectName(_fromUtf8("Principal"))
        Principal.resize(938, 612)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/modulos/images/pyventa.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Principal.setWindowIcon(icon)
        Principal.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(Principal)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.head = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.head.sizePolicy().hasHeightForWidth())
        self.head.setSizePolicy(sizePolicy)
        self.head.setObjectName(_fromUtf8("head"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.head)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lpinfo = QtGui.QWidget(self.head)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lpinfo.sizePolicy().hasHeightForWidth())
        self.lpinfo.setSizePolicy(sizePolicy)
        self.lpinfo.setObjectName(_fromUtf8("lpinfo"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.lpinfo)
        self.verticalLayout_4.setContentsMargins(3, 0, 3, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.fLine = QtGui.QFrame(self.lpinfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fLine.sizePolicy().hasHeightForWidth())
        self.fLine.setSizePolicy(sizePolicy)
        self.fLine.setStyleSheet(_fromUtf8(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QLineEdit,QDoubleSpinBox{background:transparent; border:0px; padding:3px}"))
        self.fLine.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fLine.setFrameShadow(QtGui.QFrame.Raised)
        self.fLine.setObjectName(_fromUtf8("fLine"))
        self.horizontalLayout_51 = QtGui.QHBoxLayout(self.fLine)
        self.horizontalLayout_51.setSpacing(0)
        self.horizontalLayout_51.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_51.setMargin(0)
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.codigo = QtGui.QLineEdit(self.fLine)
        self.codigo.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.codigo.setFont(font)
        self.codigo.setObjectName(_fromUtf8("codigo"))
        self.horizontalLayout_51.addWidget(self.codigo)
        self.dsbPrecio = QtGui.QDoubleSpinBox(self.fLine)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.dsbPrecio.setFont(font)
        self.dsbPrecio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbPrecio.setReadOnly(True)
        self.dsbPrecio.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dsbPrecio.setMaximum(99999.99)
        self.dsbPrecio.setObjectName(_fromUtf8("dsbPrecio"))
        self.horizontalLayout_51.addWidget(self.dsbPrecio)
        self.horizontalLayout_2.addWidget(self.fLine)
        self.fLine_2 = QtGui.QFrame(self.lpinfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fLine_2.sizePolicy().hasHeightForWidth())
        self.fLine_2.setSizePolicy(sizePolicy)
        self.fLine_2.setStyleSheet(_fromUtf8(".QFrame{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(150, 150, 150, 255), stop:0.084833 rgba(255, 255, 255, 255), stop:1 rgba(250, 250, 250, 255));padding:0px; border-radius:4px;border:1px solid #999}\n"
"QToolButton, QLineEdit{background:transparent; border:0px; padding:3px}"))
        self.fLine_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fLine_2.setFrameShadow(QtGui.QFrame.Raised)
        self.fLine_2.setObjectName(_fromUtf8("fLine_2"))
        self.horizontalLayout_52 = QtGui.QHBoxLayout(self.fLine_2)
        self.horizontalLayout_52.setSpacing(0)
        self.horizontalLayout_52.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_52.setObjectName(_fromUtf8("horizontalLayout_52"))
        self.cant = QtGui.QLineEdit(self.fLine_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cant.sizePolicy().hasHeightForWidth())
        self.cant.setSizePolicy(sizePolicy)
        self.cant.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cant.setFont(font)
        self.cant.setStyleSheet(_fromUtf8(""))
        self.cant.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cant.setObjectName(_fromUtf8("cant"))
        self.horizontalLayout_52.addWidget(self.cant)
        self.horizontalLayout_2.addWidget(self.fLine_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addWidget(self.lpinfo)
        spacerItem = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.hlm = QtGui.QHBoxLayout()
        self.hlm.setSpacing(1)
        self.hlm.setObjectName(_fromUtf8("hlm"))
        self.bventa = QtGui.QToolButton(self.head)
        self.bventa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/modulos/images/png/elegant/ventas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bventa.setIcon(icon1)
        self.bventa.setIconSize(QtCore.QSize(36, 36))
        self.bventa.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bventa.setAutoRaise(True)
        self.bventa.setObjectName(_fromUtf8("bventa"))
        self.hlm.addWidget(self.bventa)
        self.horizontalLayout_3.addLayout(self.hlm)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tbFull = QtGui.QToolButton(self.head)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/resize2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbFull.setIcon(icon2)
        self.tbFull.setIconSize(QtCore.QSize(18, 18))
        self.tbFull.setAutoRaise(True)
        self.tbFull.setObjectName(_fromUtf8("tbFull"))
        self.verticalLayout_7.addWidget(self.tbFull)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_10.addWidget(self.head)
        self.stack = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stack.sizePolicy().hasHeightForWidth())
        self.stack.setSizePolicy(sizePolicy)
        self.stack.setObjectName(_fromUtf8("stack"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frTablas = QtGui.QFrame(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frTablas.sizePolicy().hasHeightForWidth())
        self.frTablas.setSizePolicy(sizePolicy)
        self.frTablas.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frTablas.setFrameShadow(QtGui.QFrame.Raised)
        self.frTablas.setObjectName(_fromUtf8("frTablas"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frTablas)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.splitter = QtGui.QSplitter(self.frTablas)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(1)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lista2 = QtGui.QTableView(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lista2.setFont(font)
        self.lista2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lista2.setLineWidth(0)
        self.lista2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lista2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lista2.setAlternatingRowColors(True)
        self.lista2.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lista2.setShowGrid(False)
        self.lista2.setObjectName(_fromUtf8("lista2"))
        self.lista2.horizontalHeader().setVisible(False)
        self.lista2.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.lista2)
        self.gcanasta = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gcanasta.sizePolicy().hasHeightForWidth())
        self.gcanasta.setSizePolicy(sizePolicy)
        self.gcanasta.setObjectName(_fromUtf8("gcanasta"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.gcanasta)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gingreso = QtGui.QFrame(self.gcanasta)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.gingreso.sizePolicy().hasHeightForWidth())
        self.gingreso.setSizePolicy(sizePolicy)
        self.gingreso.setObjectName(_fromUtf8("gingreso"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.gingreso)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.widget_2 = QtGui.QWidget(self.gingreso)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.logo = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.logo.setFont(font)
        self.logo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.logo.setObjectName(_fromUtf8("logo"))
        self.verticalLayout_6.addWidget(self.logo)
        self.csCliente = QtGui.QToolButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csCliente.sizePolicy().hasHeightForWidth())
        self.csCliente.setSizePolicy(sizePolicy)
        self.csCliente.setMaximumSize(QtCore.QSize(190, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/administrator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.csCliente.setIcon(icon3)
        self.csCliente.setIconSize(QtCore.QSize(18, 18))
        self.csCliente.setAutoRepeat(True)
        self.csCliente.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.csCliente.setObjectName(_fromUtf8("csCliente"))
        self.verticalLayout_6.addWidget(self.csCliente)
        self.horizontalLayout_9.addWidget(self.widget_2)
        self.wLetreros = QtGui.QWidget(self.gingreso)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wLetreros.sizePolicy().hasHeightForWidth())
        self.wLetreros.setSizePolicy(sizePolicy)
        self.wLetreros.setObjectName(_fromUtf8("wLetreros"))
        self.verticalLayout = QtGui.QVBoxLayout(self.wLetreros)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(12, 2, 12, 2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lfecha = QtGui.QLabel(self.wLetreros)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lfecha.sizePolicy().hasHeightForWidth())
        self.lfecha.setSizePolicy(sizePolicy)
        self.lfecha.setTextFormat(QtCore.Qt.RichText)
        self.lfecha.setObjectName(_fromUtf8("lfecha"))
        self.verticalLayout.addWidget(self.lfecha)
        self.lnota = QtGui.QLabel(self.wLetreros)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnota.sizePolicy().hasHeightForWidth())
        self.lnota.setSizePolicy(sizePolicy)
        self.lnota.setTextFormat(QtCore.Qt.RichText)
        self.lnota.setObjectName(_fromUtf8("lnota"))
        self.verticalLayout.addWidget(self.lnota)
        self.lblModo = QtGui.QLabel(self.wLetreros)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblModo.sizePolicy().hasHeightForWidth())
        self.lblModo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblModo.setFont(font)
        self.lblModo.setObjectName(_fromUtf8("lblModo"))
        self.verticalLayout.addWidget(self.lblModo)
        self.horizontalLayout_9.addWidget(self.wLetreros)
        self.widget_5 = QtGui.QWidget(self.gingreso)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setContentsMargins(-1, -1, -1, 3)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.resumen = QtGui.QLabel(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resumen.sizePolicy().hasHeightForWidth())
        self.resumen.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resumen.setFont(font)
        self.resumen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.resumen.setObjectName(_fromUtf8("resumen"))
        self.verticalLayout_15.addWidget(self.resumen)
        self.ltotal = QtGui.QLabel(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ltotal.sizePolicy().hasHeightForWidth())
        self.ltotal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.ltotal.setFont(font)
        self.ltotal.setScaledContents(True)
        self.ltotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ltotal.setMargin(5)
        self.ltotal.setObjectName(_fromUtf8("ltotal"))
        self.verticalLayout_15.addWidget(self.ltotal)
        self.horizontalLayout_9.addWidget(self.widget_5)
        self.verticalLayout_5.addWidget(self.gingreso)
        self.wResumen = QtGui.QWidget(self.gcanasta)
        self.wResumen.setMinimumSize(QtCore.QSize(0, 20))
        self.wResumen.setObjectName(_fromUtf8("wResumen"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.wResumen)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.widget = QtGui.QWidget(self.wResumen)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.chbImprimirTicket = QtGui.QCheckBox(self.widget)
        self.chbImprimirTicket.setChecked(True)
        self.chbImprimirTicket.setObjectName(_fromUtf8("chbImprimirTicket"))
        self.verticalLayout_11.addWidget(self.chbImprimirTicket)
        self.horizontalLayout_5.addWidget(self.widget)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.wResumen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dsbRecibido = QtGui.QDoubleSpinBox(self.wResumen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbRecibido.sizePolicy().hasHeightForWidth())
        self.dsbRecibido.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.dsbRecibido.setFont(font)
        self.dsbRecibido.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbRecibido.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dsbRecibido.setMaximum(99999.99)
        self.dsbRecibido.setObjectName(_fromUtf8("dsbRecibido"))
        self.gridLayout.addWidget(self.dsbRecibido, 0, 1, 1, 1)
        self.lblCambio = QtGui.QLabel(self.wResumen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCambio.sizePolicy().hasHeightForWidth())
        self.lblCambio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lblCambio.setFont(font)
        self.lblCambio.setObjectName(_fromUtf8("lblCambio"))
        self.gridLayout.addWidget(self.lblCambio, 1, 0, 1, 1)
        self.dsbCambio = QtGui.QDoubleSpinBox(self.wResumen)
        self.dsbCambio.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dsbCambio.sizePolicy().hasHeightForWidth())
        self.dsbCambio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.dsbCambio.setFont(font)
        self.dsbCambio.setFrame(True)
        self.dsbCambio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbCambio.setReadOnly(True)
        self.dsbCambio.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dsbCambio.setMaximum(99999.99)
        self.dsbCambio.setObjectName(_fromUtf8("dsbCambio"))
        self.gridLayout.addWidget(self.dsbCambio, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.wResumen)
        self.footer = QtGui.QWidget(self.gcanasta)
        self.footer.setObjectName(_fromUtf8("footer"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.footer)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.Promo = QtGui.QLabel(self.footer)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Promo.setFont(font)
        self.Promo.setStyleSheet(_fromUtf8(""))
        self.Promo.setText(_fromUtf8(""))
        self.Promo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Promo.setWordWrap(True)
        self.Promo.setMargin(5)
        self.Promo.setObjectName(_fromUtf8("Promo"))
        self.horizontalLayout_4.addWidget(self.Promo)
        self.verticalLayout_5.addWidget(self.footer)
        self.tabla = QtGui.QTableView(self.gcanasta)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabla.setFont(font)
        self.tabla.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tabla.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabla.setAlternatingRowColors(True)
        self.tabla.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tabla.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabla.setShowGrid(False)
        self.tabla.setSortingEnabled(True)
        self.tabla.setObjectName(_fromUtf8("tabla"))
        self.tabla.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.tabla)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addWidget(self.splitter)
        self.verticalLayout_2.addWidget(self.frTablas)
        self.stack.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.layoutWidget1 = QtGui.QWidget(self.page_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(470, 230, 213, 31))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.tbTrash = QtGui.QToolButton(self.layoutWidget1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/trash_can.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbTrash.setIcon(icon4)
        self.tbTrash.setIconSize(QtCore.QSize(18, 18))
        self.tbTrash.setAutoRaise(True)
        self.tbTrash.setObjectName(_fromUtf8("tbTrash"))
        self.horizontalLayout.addWidget(self.tbTrash)
        self.tbOpen = QtGui.QToolButton(self.layoutWidget1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbOpen.setIcon(icon5)
        self.tbOpen.setIconSize(QtCore.QSize(18, 18))
        self.tbOpen.setAutoRaise(True)
        self.tbOpen.setObjectName(_fromUtf8("tbOpen"))
        self.horizontalLayout.addWidget(self.tbOpen)
        self.tbSave = QtGui.QToolButton(self.layoutWidget1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/diskette.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSave.setIcon(icon6)
        self.tbSave.setIconSize(QtCore.QSize(18, 18))
        self.tbSave.setAutoRaise(True)
        self.tbSave.setObjectName(_fromUtf8("tbSave"))
        self.horizontalLayout.addWidget(self.tbSave)
        self.tbExport = QtGui.QToolButton(self.layoutWidget1)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/clip.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbExport.setIcon(icon7)
        self.tbExport.setIconSize(QtCore.QSize(18, 18))
        self.tbExport.setAutoRaise(True)
        self.tbExport.setObjectName(_fromUtf8("tbExport"))
        self.horizontalLayout.addWidget(self.tbExport)
        self.tbRegist = QtGui.QToolButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tbRegist.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/color_18/thunder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbRegist.setIcon(icon8)
        self.tbRegist.setIconSize(QtCore.QSize(18, 18))
        self.tbRegist.setAutoRaise(True)
        self.tbRegist.setObjectName(_fromUtf8("tbRegist"))
        self.horizontalLayout.addWidget(self.tbRegist)
        self.stack.addWidget(self.page_2)
        self.verticalLayout_10.addWidget(self.stack)
        Principal.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Principal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 938, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuModulos = QtGui.QMenu(self.menubar)
        self.menuModulos.setObjectName(_fromUtf8("menuModulos"))
        self.menuEdicion = QtGui.QMenu(self.menubar)
        self.menuEdicion.setObjectName(_fromUtf8("menuEdicion"))
        self.menuSesion = QtGui.QMenu(self.menubar)
        self.menuSesion.setObjectName(_fromUtf8("menuSesion"))
        self.menuHerramientas = QtGui.QMenu(self.menubar)
        self.menuHerramientas.setObjectName(_fromUtf8("menuHerramientas"))
        self.menuPyventa = QtGui.QMenu(self.menubar)
        self.menuPyventa.setObjectName(_fromUtf8("menuPyventa"))
        self.menuMostrar = QtGui.QMenu(self.menuPyventa)
        self.menuMostrar.setObjectName(_fromUtf8("menuMostrar"))
        Principal.setMenuBar(self.menubar)
        self.actionNueva = QtGui.QAction(Principal)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNueva.setIcon(icon9)
        self.actionNueva.setIconVisibleInMenu(True)
        self.actionNueva.setObjectName(_fromUtf8("actionNueva"))
        self.actionImprimir = QtGui.QAction(Principal)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImprimir.setIcon(icon10)
        self.actionImprimir.setIconVisibleInMenu(True)
        self.actionImprimir.setObjectName(_fromUtf8("actionImprimir"))
        self.actionEliminar = QtGui.QAction(Principal)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../.designer/backup/images/icons/elimina.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEliminar.setIcon(icon11)
        self.actionEliminar.setObjectName(_fromUtf8("actionEliminar"))
        self.actionBuscador = QtGui.QAction(Principal)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/search_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBuscador.setIcon(icon12)
        self.actionBuscador.setObjectName(_fromUtf8("actionBuscador"))
        self.actionAdministrador = QtGui.QAction(Principal)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../.designer/backup/images/icons/16/plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdministrador.setIcon(icon13)
        self.actionAdministrador.setObjectName(_fromUtf8("actionAdministrador"))
        self.actionVentas_del_dia = QtGui.QAction(Principal)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/statistics_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVentas_del_dia.setIcon(icon14)
        self.actionVentas_del_dia.setObjectName(_fromUtf8("actionVentas_del_dia"))
        self.aGuardar = QtGui.QAction(Principal)
        self.aGuardar.setIcon(icon6)
        self.aGuardar.setIconVisibleInMenu(True)
        self.aGuardar.setObjectName(_fromUtf8("aGuardar"))
        self.actionOpen = QtGui.QAction(Principal)
        self.actionOpen.setIcon(icon5)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionAgregar_clientes = QtGui.QAction(Principal)
        self.actionAgregar_clientes.setObjectName(_fromUtf8("actionAgregar_clientes"))
        self.actionCartera_de_clientes = QtGui.QAction(Principal)
        self.actionCartera_de_clientes.setObjectName(_fromUtf8("actionCartera_de_clientes"))
        self.action_Cambiar_cliente_actual = QtGui.QAction(Principal)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../.designer/backup/images/icons/camuser.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Cambiar_cliente_actual.setIcon(icon15)
        self.action_Cambiar_cliente_actual.setObjectName(_fromUtf8("action_Cambiar_cliente_actual"))
        self.actionBase_de_datos = QtGui.QAction(Principal)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/database-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBase_de_datos.setIcon(icon16)
        self.actionBase_de_datos.setObjectName(_fromUtf8("actionBase_de_datos"))
        self.actionRespaldar = QtGui.QAction(Principal)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/warning_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRespaldar.setIcon(icon17)
        self.actionRespaldar.setObjectName(_fromUtf8("actionRespaldar"))
        self.actionUpdate = QtGui.QAction(Principal)
        self.actionUpdate.setObjectName(_fromUtf8("actionUpdate"))
        self.actionCompleta = QtGui.QAction(Principal)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/32/monitor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompleta.setIcon(icon18)
        self.actionCompleta.setIconVisibleInMenu(True)
        self.actionCompleta.setObjectName(_fromUtf8("actionCompleta"))
        self.actionNormal = QtGui.QAction(Principal)
        self.actionNormal.setIconVisibleInMenu(True)
        self.actionNormal.setObjectName(_fromUtf8("actionNormal"))
        self.actionMini = QtGui.QAction(Principal)
        self.actionMini.setIconVisibleInMenu(True)
        self.actionMini.setObjectName(_fromUtf8("actionMini"))
        self.actionPlantilla_de_presupuesto = QtGui.QAction(Principal)
        self.actionPlantilla_de_presupuesto.setObjectName(_fromUtf8("actionPlantilla_de_presupuesto"))
        self.actionNota_de_venta = QtGui.QAction(Principal)
        self.actionNota_de_venta.setObjectName(_fromUtf8("actionNota_de_venta"))
        self.actionA_Pyventa = QtGui.QAction(Principal)
        self.actionA_Pyventa.setIconVisibleInMenu(True)
        self.actionA_Pyventa.setObjectName(_fromUtf8("actionA_Pyventa"))
        self.actionVersion = QtGui.QAction(Principal)
        self.actionVersion.setObjectName(_fromUtf8("actionVersion"))
        self.actionGuardar = QtGui.QAction(Principal)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/hard_disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardar.setIcon(icon19)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionCerrar = QtGui.QAction(Principal)
        self.actionCerrar.setObjectName(_fromUtf8("actionCerrar"))
        self.actionReimprimir = QtGui.QAction(Principal)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/gray_18/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReimprimir.setIcon(icon20)
        self.actionReimprimir.setObjectName(_fromUtf8("actionReimprimir"))
        self.actionFactura = QtGui.QAction(Principal)
        self.actionFactura.setObjectName(_fromUtf8("actionFactura"))
        self.actionCancelar_nota = QtGui.QAction(Principal)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCancelar_nota.setIcon(icon21)
        self.actionCancelar_nota.setIconVisibleInMenu(True)
        self.actionCancelar_nota.setObjectName(_fromUtf8("actionCancelar_nota"))
        self.actionEditar_ticket = QtGui.QAction(Principal)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/pencil_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditar_ticket.setIcon(icon22)
        self.actionEditar_ticket.setObjectName(_fromUtf8("actionEditar_ticket"))
        self.actionQuitar_prod = QtGui.QAction(Principal)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuitar_prod.setIcon(icon23)
        self.actionQuitar_prod.setIconVisibleInMenu(True)
        self.actionQuitar_prod.setObjectName(_fromUtf8("actionQuitar_prod"))
        self.actionRecibos = QtGui.QAction(Principal)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/globe_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecibos.setIcon(icon24)
        self.actionRecibos.setObjectName(_fromUtf8("actionRecibos"))
        self.actionCopiar_nota = QtGui.QAction(Principal)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/clipboard_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopiar_nota.setIcon(icon25)
        self.actionCopiar_nota.setObjectName(_fromUtf8("actionCopiar_nota"))
        self.actionCerrar_nota = QtGui.QAction(Principal)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/checkmark2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCerrar_nota.setIcon(icon26)
        self.actionCerrar_nota.setIconVisibleInMenu(True)
        self.actionCerrar_nota.setObjectName(_fromUtf8("actionCerrar_nota"))
        self.actionVer_barra = QtGui.QAction(Principal)
        self.actionVer_barra.setCheckable(False)
        self.actionVer_barra.setChecked(False)
        self.actionVer_barra.setObjectName(_fromUtf8("actionVer_barra"))
        self.actionCobrar_notas = QtGui.QAction(Principal)
        self.actionCobrar_notas.setObjectName(_fromUtf8("actionCobrar_notas"))
        self.aAbrir = QtGui.QAction(Principal)
        self.aAbrir.setIcon(icon5)
        self.aAbrir.setIconVisibleInMenu(True)
        self.aAbrir.setObjectName(_fromUtf8("aAbrir"))
        self.actionPreferencias = QtGui.QAction(Principal)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/16/gear_16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferencias.setIcon(icon27)
        self.actionPreferencias.setObjectName(_fromUtf8("actionPreferencias"))
        self.actionPunto_de_venta = QtGui.QAction(Principal)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/icono.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPunto_de_venta.setIcon(icon28)
        self.actionPunto_de_venta.setIconVisibleInMenu(True)
        self.actionPunto_de_venta.setObjectName(_fromUtf8("actionPunto_de_venta"))
        self.actionIngresar = QtGui.QAction(Principal)
        self.actionIngresar.setIcon(icon9)
        self.actionIngresar.setIconVisibleInMenu(True)
        self.actionIngresar.setObjectName(_fromUtf8("actionIngresar"))
        self.actionFacturar = QtGui.QAction(Principal)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFacturar.setIcon(icon29)
        self.actionFacturar.setIconVisibleInMenu(True)
        self.actionFacturar.setObjectName(_fromUtf8("actionFacturar"))
        self.actionProductos = QtGui.QAction(Principal)
        self.actionProductos.setObjectName(_fromUtf8("actionProductos"))
        self.actionCambiar_estilo = QtGui.QAction(Principal)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../usr/share/pyventa/images/32/paint.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCambiar_estilo.setIcon(icon30)
        self.actionCambiar_estilo.setObjectName(_fromUtf8("actionCambiar_estilo"))
        self.actionModo_rapido = QtGui.QAction(Principal)
        self.actionModo_rapido.setCheckable(True)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/fast_forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModo_rapido.setIcon(icon31)
        self.actionModo_rapido.setObjectName(_fromUtf8("actionModo_rapido"))
        self.actionPresupuesto = QtGui.QAction(Principal)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/document.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPresupuesto.setIcon(icon32)
        self.actionPresupuesto.setIconVisibleInMenu(True)
        self.actionPresupuesto.setObjectName(_fromUtf8("actionPresupuesto"))
        self.actionAutorizar_descuento = QtGui.QAction(Principal)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/key.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAutorizar_descuento.setIcon(icon33)
        self.actionAutorizar_descuento.setObjectName(_fromUtf8("actionAutorizar_descuento"))
        self.actionAbrir_cajon = QtGui.QAction(Principal)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/bell.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbrir_cajon.setIcon(icon34)
        self.actionAbrir_cajon.setIconVisibleInMenu(True)
        self.actionAbrir_cajon.setObjectName(_fromUtf8("actionAbrir_cajon"))
        self.actionCambiar_usuario = QtGui.QAction(Principal)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/group.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCambiar_usuario.setIcon(icon35)
        self.actionCambiar_usuario.setIconVisibleInMenu(True)
        self.actionCambiar_usuario.setObjectName(_fromUtf8("actionCambiar_usuario"))
        self.actionNueva_sesion = QtGui.QAction(Principal)
        self.actionNueva_sesion.setIcon(icon3)
        self.actionNueva_sesion.setIconVisibleInMenu(True)
        self.actionNueva_sesion.setObjectName(_fromUtf8("actionNueva_sesion"))
        self.actionCerrar_sesion = QtGui.QAction(Principal)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/disconnect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCerrar_sesion.setIcon(icon36)
        self.actionCerrar_sesion.setIconVisibleInMenu(True)
        self.actionCerrar_sesion.setObjectName(_fromUtf8("actionCerrar_sesion"))
        self.aConfigBd = QtGui.QAction(Principal)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/spreadsheet.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aConfigBd.setIcon(icon37)
        self.aConfigBd.setObjectName(_fromUtf8("aConfigBd"))
        self.actionGuardarcompra = QtGui.QAction(Principal)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/download2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardarcompra.setIcon(icon38)
        self.actionGuardarcompra.setIconVisibleInMenu(True)
        self.actionGuardarcompra.setObjectName(_fromUtf8("actionGuardarcompra"))
        self.actionAbrir_compra = QtGui.QAction(Principal)
        self.actionAbrir_compra.setIcon(icon5)
        self.actionAbrir_compra.setObjectName(_fromUtf8("actionAbrir_compra"))
        self.actionNueva_compra = QtGui.QAction(Principal)
        self.actionNueva_compra.setIcon(icon9)
        self.actionNueva_compra.setObjectName(_fromUtf8("actionNueva_compra"))
        self.actionSwap = QtGui.QAction(Principal)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(_fromUtf8(":/actions/images/actions/black_18/arrow_bidirectional.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSwap.setIcon(icon39)
        self.actionSwap.setIconVisibleInMenu(True)
        self.actionSwap.setObjectName(_fromUtf8("actionSwap"))
        self.action = QtGui.QAction(Principal)
        self.action.setObjectName(_fromUtf8("action"))
        self.actionAbrir_venta_extemporanea = QtGui.QAction(Principal)
        self.actionAbrir_venta_extemporanea.setIcon(icon5)
        self.actionAbrir_venta_extemporanea.setObjectName(_fromUtf8("actionAbrir_venta_extemporanea"))
        self.actionReimprimir_archivada = QtGui.QAction(Principal)
        self.actionReimprimir_archivada.setIcon(icon10)
        self.actionReimprimir_archivada.setObjectName(_fromUtf8("actionReimprimir_archivada"))
        self.menuArchivo.addAction(self.actionOpen)
        self.menuArchivo.addAction(self.aAbrir)
        self.menuArchivo.addAction(self.actionAbrir_venta_extemporanea)
        self.menuArchivo.addAction(self.actionAbrir_compra)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.aGuardar)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardarcompra)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionNueva)
        self.menuArchivo.addAction(self.actionNueva_compra)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionFacturar)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionImprimir)
        self.menuArchivo.addAction(self.actionReimprimir)
        self.menuArchivo.addAction(self.actionReimprimir_archivada)
        self.menuArchivo.addAction(self.actionPresupuesto)
        self.menuArchivo.addSeparator()
        self.menuModulos.addAction(self.actionPunto_de_venta)
        self.menuModulos.addSeparator()
        self.menuModulos.addAction(self.actionVer_barra)
        self.menuEdicion.addAction(self.actionCerrar_nota)
        self.menuEdicion.addAction(self.actionCancelar_nota)
        self.menuEdicion.addSeparator()
        self.menuEdicion.addAction(self.actionIngresar)
        self.menuEdicion.addAction(self.actionQuitar_prod)
        self.menuEdicion.addAction(self.actionModo_rapido)
        self.menuEdicion.addAction(self.actionAutorizar_descuento)
        self.menuEdicion.addAction(self.actionAbrir_cajon)
        self.menuSesion.addAction(self.actionNueva_sesion)
        self.menuSesion.addAction(self.actionCambiar_usuario)
        self.menuSesion.addAction(self.actionCerrar_sesion)
        self.menuHerramientas.addAction(self.actionSwap)
        self.menuHerramientas.addAction(self.aConfigBd)
        self.menuMostrar.addAction(self.actionMini)
        self.menuMostrar.addAction(self.actionNormal)
        self.menuMostrar.addAction(self.actionCompleta)
        self.menuPyventa.addAction(self.actionA_Pyventa)
        self.menuPyventa.addAction(self.menuMostrar.menuAction())
        self.menuPyventa.addAction(self.actionCerrar)
        self.menubar.addAction(self.menuPyventa.menuAction())
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEdicion.menuAction())
        self.menubar.addAction(self.menuModulos.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())
        self.menubar.addAction(self.menuSesion.menuAction())

        self.retranslateUi(Principal)
        self.stack.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionNormal, QtCore.SIGNAL(_fromUtf8("triggered()")), Principal.showMaximized)
        QtCore.QObject.connect(self.actionCompleta, QtCore.SIGNAL(_fromUtf8("triggered()")), Principal.showFullScreen)
        QtCore.QObject.connect(self.actionCerrar, QtCore.SIGNAL(_fromUtf8("triggered()")), Principal.close)
        QtCore.QMetaObject.connectSlotsByName(Principal)
        Principal.setTabOrder(self.codigo, self.lista2)
        Principal.setTabOrder(self.lista2, self.bventa)
        Principal.setTabOrder(self.bventa, self.tbFull)
        Principal.setTabOrder(self.tbFull, self.tabla)
        Principal.setTabOrder(self.tabla, self.tbTrash)
        Principal.setTabOrder(self.tbTrash, self.tbOpen)
        Principal.setTabOrder(self.tbOpen, self.tbSave)
        Principal.setTabOrder(self.tbSave, self.tbExport)
        Principal.setTabOrder(self.tbExport, self.tbRegist)
        Principal.setTabOrder(self.tbRegist, self.dsbRecibido)
        Principal.setTabOrder(self.dsbRecibido, self.dsbCambio)
        Principal.setTabOrder(self.dsbCambio, self.chbImprimirTicket)
        Principal.setTabOrder(self.chbImprimirTicket, self.dsbPrecio)

    def retranslateUi(self, Principal):
        Principal.setWindowTitle(QtGui.QApplication.translate("Principal", "Pyventa - Punto de venta", None, QtGui.QApplication.UnicodeUTF8))
        self.codigo.setToolTip(QtGui.QApplication.translate("Principal", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Puede regresar a este punto de registro de productos, presionando la tecla <span style=\" font-weight:600;\">Inser</span> o <span style=\" font-weight:600;\">Insertar</span> desde cualquier lugar del punto de venta.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.dsbPrecio.setToolTip(QtGui.QApplication.translate("Principal", "Precio", None, QtGui.QApplication.UnicodeUTF8))
        self.dsbPrecio.setPrefix(QtGui.QApplication.translate("Principal", "$", None, QtGui.QApplication.UnicodeUTF8))
        self.cant.setToolTip(QtGui.QApplication.translate("Principal", "Cantidad", None, QtGui.QApplication.UnicodeUTF8))
        self.cant.setText(QtGui.QApplication.translate("Principal", "1.00", None, QtGui.QApplication.UnicodeUTF8))
        self.bventa.setToolTip(QtGui.QApplication.translate("Principal", "<h1>Insert</h1>Ir a la venta", None, QtGui.QApplication.UnicodeUTF8))
        self.bventa.setText(QtGui.QApplication.translate("Principal", "Punto", None, QtGui.QApplication.UnicodeUTF8))
        self.tbFull.setText(QtGui.QApplication.translate("Principal", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.logo.setText(QtGui.QApplication.translate("Principal", "Nota de Venta", None, QtGui.QApplication.UnicodeUTF8))
        self.csCliente.setToolTip(QtGui.QApplication.translate("Principal", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Para seleccionar un cliente de manera rapida solo presione las teclas \"<span style=\" font-weight:600;\">Control</span>\" y \"<span style=\" font-weight:600;\">K</span>\"</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.csCliente.setText(QtGui.QApplication.translate("Principal", "Seleccionar un cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.csCliente.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+K", None, QtGui.QApplication.UnicodeUTF8))
        self.lfecha.setText(QtGui.QApplication.translate("Principal", "<b>Fecha:</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.lnota.setText(QtGui.QApplication.translate("Principal", "Nota:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblModo.setText(QtGui.QApplication.translate("Principal", "Ingreso manual", None, QtGui.QApplication.UnicodeUTF8))
        self.resumen.setText(QtGui.QApplication.translate("Principal", "Gran Total", None, QtGui.QApplication.UnicodeUTF8))
        self.ltotal.setText(QtGui.QApplication.translate("Principal", "$000.00", None, QtGui.QApplication.UnicodeUTF8))
        self.chbImprimirTicket.setText(QtGui.QApplication.translate("Principal", "Imprimir ticket", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Principal", "Recibido:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsbRecibido.setPrefix(QtGui.QApplication.translate("Principal", "$", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCambio.setText(QtGui.QApplication.translate("Principal", "Cambio", None, QtGui.QApplication.UnicodeUTF8))
        self.dsbCambio.setPrefix(QtGui.QApplication.translate("Principal", "$", None, QtGui.QApplication.UnicodeUTF8))
        self.tbTrash.setToolTip(QtGui.QApplication.translate("Principal", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbTrash.setText(QtGui.QApplication.translate("Principal", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbOpen.setToolTip(QtGui.QApplication.translate("Principal", "Abrir venta", None, QtGui.QApplication.UnicodeUTF8))
        self.tbOpen.setText(QtGui.QApplication.translate("Principal", "Abrir", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSave.setToolTip(QtGui.QApplication.translate("Principal", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSave.setText(QtGui.QApplication.translate("Principal", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbExport.setToolTip(QtGui.QApplication.translate("Principal", "Exportar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbExport.setText(QtGui.QApplication.translate("Principal", "Exportar", None, QtGui.QApplication.UnicodeUTF8))
        self.tbRegist.setToolTip(QtGui.QApplication.translate("Principal", "Finalizar venta F5", None, QtGui.QApplication.UnicodeUTF8))
        self.tbRegist.setText(QtGui.QApplication.translate("Principal", "Completar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArchivo.setTitle(QtGui.QApplication.translate("Principal", "Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuModulos.setTitle(QtGui.QApplication.translate("Principal", "Modulos", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdicion.setTitle(QtGui.QApplication.translate("Principal", "Edicion", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSesion.setTitle(QtGui.QApplication.translate("Principal", "Sesion", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHerramientas.setTitle(QtGui.QApplication.translate("Principal", "Herramientas", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPyventa.setTitle(QtGui.QApplication.translate("Principal", "Pyventa", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMostrar.setTitle(QtGui.QApplication.translate("Principal", "Modo de ventana", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNueva.setText(QtGui.QApplication.translate("Principal", "&Nueva nota", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNueva.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImprimir.setText(QtGui.QApplication.translate("Principal", "Im&primir ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImprimir.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEliminar.setText(QtGui.QApplication.translate("Principal", "Eliminar nota", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuscador.setText(QtGui.QApplication.translate("Principal", "Buscador", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuscador.setShortcut(QtGui.QApplication.translate("Principal", "F3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdministrador.setText(QtGui.QApplication.translate("Principal", "Administrador", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVentas_del_dia.setText(QtGui.QApplication.translate("Principal", "Reporte de ventas", None, QtGui.QApplication.UnicodeUTF8))
        self.aGuardar.setText(QtGui.QApplication.translate("Principal", "&Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.aGuardar.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("Principal", "&Abrir archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAgregar_clientes.setText(QtGui.QApplication.translate("Principal", "Alta de clientes.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCartera_de_clientes.setText(QtGui.QApplication.translate("Principal", "Cartera de clientes.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Cambiar_cliente_actual.setText(QtGui.QApplication.translate("Principal", " Cambiar cliente actual", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBase_de_datos.setText(QtGui.QApplication.translate("Principal", "Base de datos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRespaldar.setText(QtGui.QApplication.translate("Principal", "Generar Respaldo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate.setText(QtGui.QApplication.translate("Principal", "Actualizacion", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompleta.setText(QtGui.QApplication.translate("Principal", "Pantalla Completa", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompleta.setShortcut(QtGui.QApplication.translate("Principal", "F11", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNormal.setText(QtGui.QApplication.translate("Principal", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNormal.setShortcut(QtGui.QApplication.translate("Principal", "F10", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMini.setText(QtGui.QApplication.translate("Principal", "Compacta", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlantilla_de_presupuesto.setText(QtGui.QApplication.translate("Principal", "Plantilla de presupuesto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNota_de_venta.setText(QtGui.QApplication.translate("Principal", "Nota de venta", None, QtGui.QApplication.UnicodeUTF8))
        self.actionA_Pyventa.setText(QtGui.QApplication.translate("Principal", "Acerca de Pyventa", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVersion.setText(QtGui.QApplication.translate("Principal", "Acerca de Ottarw", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardar.setText(QtGui.QApplication.translate("Principal", "&Guardar como...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardar.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCerrar.setText(QtGui.QApplication.translate("Principal", "Cerrar Pyventa", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCerrar.setToolTip(QtGui.QApplication.translate("Principal", "Cierra el programa.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCerrar.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReimprimir.setText(QtGui.QApplication.translate("Principal", "&Reimprimir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFactura.setText(QtGui.QApplication.translate("Principal", "Factura", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCancelar_nota.setText(QtGui.QApplication.translate("Principal", "Cancelar venta", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditar_ticket.setText(QtGui.QApplication.translate("Principal", "Editar ticket", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitar_prod.setText(QtGui.QApplication.translate("Principal", "Quitar producto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitar_prod.setShortcut(QtGui.QApplication.translate("Principal", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecibos.setText(QtGui.QApplication.translate("Principal", "Recibos telmex", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecibos.setShortcut(QtGui.QApplication.translate("Principal", "F4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopiar_nota.setText(QtGui.QApplication.translate("Principal", "Copiar venta", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopiar_nota.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCerrar_nota.setText(QtGui.QApplication.translate("Principal", "Finalizar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCerrar_nota.setShortcut(QtGui.QApplication.translate("Principal", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVer_barra.setText(QtGui.QApplication.translate("Principal", "Ver Barra de modulos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCobrar_notas.setText(QtGui.QApplication.translate("Principal", "Cobrar Notas", None, QtGui.QApplication.UnicodeUTF8))
        self.aAbrir.setText(QtGui.QApplication.translate("Principal", "Abrir venta", None, QtGui.QApplication.UnicodeUTF8))
        self.aAbrir.setStatusTip(QtGui.QApplication.translate("Principal", "Cancela la nota enterior y copia sus valores a la nota actual", None, QtGui.QApplication.UnicodeUTF8))
        self.aAbrir.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferencias.setText(QtGui.QApplication.translate("Principal", "Preferencias", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPunto_de_venta.setText(QtGui.QApplication.translate("Principal", "Punto de venta", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIngresar.setText(QtGui.QApplication.translate("Principal", "Ingresar producto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIngresar.setShortcut(QtGui.QApplication.translate("Principal", "Ins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFacturar.setText(QtGui.QApplication.translate("Principal", "&Facturar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFacturar.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProductos.setText(QtGui.QApplication.translate("Principal", "Productos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCambiar_estilo.setText(QtGui.QApplication.translate("Principal", "Cambiar estilo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModo_rapido.setText(QtGui.QApplication.translate("Principal", "Modo  rapido", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModo_rapido.setShortcut(QtGui.QApplication.translate("Principal", "F7", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPresupuesto.setText(QtGui.QApplication.translate("Principal", "Imprimir como presupuesto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutorizar_descuento.setText(QtGui.QApplication.translate("Principal", "Autorizar descuento", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutorizar_descuento.setShortcut(QtGui.QApplication.translate("Principal", "F2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir_cajon.setText(QtGui.QApplication.translate("Principal", "Abrir cajon", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir_cajon.setShortcut(QtGui.QApplication.translate("Principal", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCambiar_usuario.setText(QtGui.QApplication.translate("Principal", "Cambiar usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNueva_sesion.setText(QtGui.QApplication.translate("Principal", "Iniciar sesion", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCerrar_sesion.setText(QtGui.QApplication.translate("Principal", "Cerrar sesion", None, QtGui.QApplication.UnicodeUTF8))
        self.aConfigBd.setText(QtGui.QApplication.translate("Principal", "Configurador de BD", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardarcompra.setText(QtGui.QApplication.translate("Principal", "Guardar como compra", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardarcompra.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir_compra.setText(QtGui.QApplication.translate("Principal", "Abrir compra", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir_compra.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+Shift+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNueva_compra.setText(QtGui.QApplication.translate("Principal", "Nueva compra", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNueva_compra.setShortcut(QtGui.QApplication.translate("Principal", "Ctrl+Shift+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwap.setText(QtGui.QApplication.translate("Principal", "Intecambiar productos", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("Principal", "Respaldos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir_venta_extemporanea.setText(QtGui.QApplication.translate("Principal", "Abrir venta archivada", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReimprimir_archivada.setText(QtGui.QApplication.translate("Principal", "Reimprimir archivada", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
