# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/modulos/ui_reportes.ui'
#
# Created: Sun May 12 00:35:41 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(793, 544)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.topReportes = QtWidgets.QWidget(Form)
        self.topReportes.setObjectName("topReportes")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.topReportes)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.topReportes)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titulo = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo.sizePolicy().hasHeightForWidth())
        self.titulo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setMargin(7)
        self.titulo.setIndent(8)
        self.titulo.setObjectName("titulo")
        self.verticalLayout_3.addWidget(self.titulo)
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_17 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.deFrom = QtWidgets.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deFrom.setFont(font)
        self.deFrom.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.deFrom.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.deFrom.setAccelerated(True)
        self.deFrom.setCalendarPopup(True)
        self.deFrom.setObjectName("deFrom")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deFrom)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.deTo = QtWidgets.QDateEdit(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deTo.setFont(font)
        self.deTo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.deTo.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.deTo.setAccelerated(True)
        self.deTo.setCalendarPopup(True)
        self.deTo.setObjectName("deTo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.deTo)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cbListas = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbListas.setFont(font)
        self.cbListas.setObjectName("cbListas")
        self.cbListas.addItem("")
        self.cbListas.addItem("")
        self.cbListas.addItem("")
        self.cbListas.addItem("")
        self.cbListas.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cbListas)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cbCaja = QtWidgets.QComboBox(self.widget)
        self.cbCaja.setObjectName("cbCaja")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cbCaja)
        self.pbListaVentas = QtWidgets.QToolButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pbListaVentas.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/reload.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbListaVentas.setIcon(icon)
        self.pbListaVentas.setIconSize(QtCore.QSize(18, 18))
        self.pbListaVentas.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pbListaVentas.setObjectName("pbListaVentas")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pbListaVentas)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.verticalLayout_3.addWidget(self.widget)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet(".QFrame{\n"
"border: 1.2px solid #999;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));}\n"
"QToolButton::hover{\n"
"    background-color:rgba(133, 217, 255, 100);\n"
"}\n"
"QToolButton::pressed{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(239, 239, 239, 27), stop:1 rgba(68, 68, 68, 205));\n"
"}\n"
"QToolButton, QLabel{padding:2 4 2 4; color:#555;border:0;}\n"
" \n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tbListar = QtWidgets.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbListar.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/list.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbListar.setIcon(icon1)
        self.tbListar.setIconSize(QtCore.QSize(18, 18))
        self.tbListar.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.tbListar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbListar.setAutoRaise(True)
        self.tbListar.setObjectName("tbListar")
        self.horizontalLayout_3.addWidget(self.tbListar)
        self.tbDetallar = QtWidgets.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tbDetallar.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/clipboard.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbDetallar.setIcon(icon2)
        self.tbDetallar.setIconSize(QtCore.QSize(18, 18))
        self.tbDetallar.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.tbDetallar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbDetallar.setAutoRaise(True)
        self.tbDetallar.setObjectName("tbDetallar")
        self.horizontalLayout_3.addWidget(self.tbDetallar)
        self.tbGraficas = QtWidgets.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbGraficas.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/stats_bars.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbGraficas.setIcon(icon3)
        self.tbGraficas.setIconSize(QtCore.QSize(18, 18))
        self.tbGraficas.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbGraficas.setAutoRaise(True)
        self.tbGraficas.setObjectName("tbGraficas")
        self.horizontalLayout_3.addWidget(self.tbGraficas)
        self.bCorteT = QtWidgets.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bCorteT.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/scissors.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bCorteT.setIcon(icon4)
        self.bCorteT.setIconSize(QtCore.QSize(18, 18))
        self.bCorteT.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bCorteT.setObjectName("bCorteT")
        self.horizontalLayout_3.addWidget(self.bCorteT)
        self.tbImprimir = QtWidgets.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbImprimir.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/print.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbImprimir.setIcon(icon5)
        self.tbImprimir.setIconSize(QtCore.QSize(18, 18))
        self.tbImprimir.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.tbImprimir.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tbImprimir.setAutoRaise(True)
        self.tbImprimir.setObjectName("tbImprimir")
        self.horizontalLayout_3.addWidget(self.tbImprimir)
        self.verticalLayout_3.addWidget(self.frame)
        self.teDetalles = QtWidgets.QTextEdit(self.layoutWidget)
        self.teDetalles.setMaximumSize(QtCore.QSize(320, 16777215))
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(10)
        self.teDetalles.setFont(font)
        self.teDetalles.setObjectName("teDetalles")
        self.verticalLayout_3.addWidget(self.teDetalles)
        self.stackReportes = QtWidgets.QStackedWidget(self.splitter)
        self.stackReportes.setObjectName("stackReportes")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tVentas = QtWidgets.QTableView(self.page_5)
        self.tVentas.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tVentas.setAlternatingRowColors(True)
        self.tVentas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tVentas.setSortingEnabled(True)
        self.tVentas.setObjectName("tVentas")
        self.tVentas.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tVentas)
        self.stackReportes.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gToolbar_3 = QtWidgets.QWidget(self.page_6)
        self.gToolbar_3.setStyleSheet(".QWidget{background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(228, 228, 228, 255));}")
        self.gToolbar_3.setObjectName("gToolbar_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.gToolbar_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.tbGColorear = QtWidgets.QToolButton(self.gToolbar_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbGColorear.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/history.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbGColorear.setIcon(icon6)
        self.tbGColorear.setIconSize(QtCore.QSize(18, 18))
        self.tbGColorear.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbGColorear.setAutoRaise(True)
        self.tbGColorear.setObjectName("tbGColorear")
        self.horizontalLayout_8.addWidget(self.tbGColorear)
        self.tbGEtiquetas = QtWidgets.QToolButton(self.gToolbar_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbGEtiquetas.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/font_size.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbGEtiquetas.setIcon(icon7)
        self.tbGEtiquetas.setIconSize(QtCore.QSize(18, 18))
        self.tbGEtiquetas.setCheckable(True)
        self.tbGEtiquetas.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbGEtiquetas.setAutoRaise(True)
        self.tbGEtiquetas.setObjectName("tbGEtiquetas")
        self.horizontalLayout_8.addWidget(self.tbGEtiquetas)
        self.tbGGuardar = QtWidgets.QToolButton(self.gToolbar_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbGGuardar.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/diskette.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbGGuardar.setIcon(icon8)
        self.tbGGuardar.setIconSize(QtCore.QSize(18, 18))
        self.tbGGuardar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbGGuardar.setAutoRaise(True)
        self.tbGGuardar.setObjectName("tbGGuardar")
        self.horizontalLayout_8.addWidget(self.tbGGuardar)
        self.tbGImprimir = QtWidgets.QToolButton(self.gToolbar_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbGImprimir.setFont(font)
        self.tbGImprimir.setIcon(icon5)
        self.tbGImprimir.setIconSize(QtCore.QSize(18, 18))
        self.tbGImprimir.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbGImprimir.setAutoRaise(True)
        self.tbGImprimir.setObjectName("tbGImprimir")
        self.horizontalLayout_8.addWidget(self.tbGImprimir)
        self.verticalLayout_2.addWidget(self.gToolbar_3)
        self.grafica = QtWidgets.QGraphicsView(self.page_6)
        self.grafica.setRenderHints(QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.TextAntialiasing)
        self.grafica.setObjectName("grafica")
        self.verticalLayout_2.addWidget(self.grafica)
        self.stackReportes.addWidget(self.page_6)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(self.page_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 363, 538))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gToolbar_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gToolbar_2.setStyleSheet(".QWidget{background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(228, 228, 228, 255));}")
        self.gToolbar_2.setObjectName("gToolbar_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.gToolbar_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.tbREtiquetar = QtWidgets.QToolButton(self.gToolbar_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbREtiquetar.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/spreadsheet.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbREtiquetar.setIcon(icon9)
        self.tbREtiquetar.setIconSize(QtCore.QSize(18, 18))
        self.tbREtiquetar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbREtiquetar.setAutoRaise(True)
        self.tbREtiquetar.setObjectName("tbREtiquetar")
        self.horizontalLayout_7.addWidget(self.tbREtiquetar)
        self.tbRGuardar = QtWidgets.QToolButton(self.gToolbar_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbRGuardar.setFont(font)
        self.tbRGuardar.setIcon(icon8)
        self.tbRGuardar.setIconSize(QtCore.QSize(18, 18))
        self.tbRGuardar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbRGuardar.setAutoRaise(True)
        self.tbRGuardar.setObjectName("tbRGuardar")
        self.horizontalLayout_7.addWidget(self.tbRGuardar)
        self.tbRImprimir = QtWidgets.QToolButton(self.gToolbar_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tbRImprimir.setFont(font)
        self.tbRImprimir.setIcon(icon5)
        self.tbRImprimir.setIconSize(QtCore.QSize(18, 18))
        self.tbRImprimir.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbRImprimir.setAutoRaise(True)
        self.tbRImprimir.setObjectName("tbRImprimir")
        self.horizontalLayout_7.addWidget(self.tbRImprimir)
        self.verticalLayout_8.addWidget(self.gToolbar_2)
        self.teResumen = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.teResumen.setMaximumSize(QtCore.QSize(700, 16777215))
        self.teResumen.setReadOnly(True)
        self.teResumen.setObjectName("teResumen")
        self.verticalLayout_8.addWidget(self.teResumen)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.stackReportes.addWidget(self.page_3)
        self.verticalLayout_4.addWidget(self.splitter)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addWidget(self.topReportes)

        self.retranslateUi(Form)
        self.stackReportes.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtCore.QCoreApplication.translate("Form", "Form"))
        self.titulo.setText(QtCore.QCoreApplication.translate("Form", "Reportes de ventas:"))
        self.label_17.setText(QtCore.QCoreApplication.translate("Form", "Desde:"))
        self.deFrom.setDisplayFormat(QtCore.QCoreApplication.translate("Form", "dd MMM yy   "))
        self.label_4.setText(QtCore.QCoreApplication.translate("Form", "Hasta:"))
        self.deTo.setDisplayFormat(QtCore.QCoreApplication.translate("Form", "dd MMM yy   "))
        self.label_8.setText(QtCore.QCoreApplication.translate("Form", "Filtrar formato:"))
        self.cbListas.setItemText(0, QtCore.QCoreApplication.translate("Form", "Ventas"))
        self.cbListas.setItemText(1, QtCore.QCoreApplication.translate("Form", "Compras"))
        self.cbListas.setItemText(2, QtCore.QCoreApplication.translate("Form", "Gastos"))
        self.cbListas.setItemText(3, QtCore.QCoreApplication.translate("Form", "Retiros"))
        self.cbListas.setItemText(4, QtCore.QCoreApplication.translate("Form", "Depositos"))
        self.label.setText(QtCore.QCoreApplication.translate("Form", "Filtrar caja:"))
        self.pbListaVentas.setText(QtCore.QCoreApplication.translate("Form", "Actualizar datos"))
        self.tbListar.setText(QtCore.QCoreApplication.translate("Form", "Listar"))
        self.tbDetallar.setText(QtCore.QCoreApplication.translate("Form", "Detallar"))
        self.tbGraficas.setText(QtCore.QCoreApplication.translate("Form", "Graficar"))
        self.bCorteT.setToolTip(QtCore.QCoreApplication.translate("Form", "Realizar corte de ventas."))
        self.bCorteT.setText(QtCore.QCoreApplication.translate("Form", "Corte"))
        self.tbImprimir.setText(QtCore.QCoreApplication.translate("Form", "Imprimir"))
        self.teDetalles.setHtml(QtWidgets.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-weight:600;\">Tabla general de ventas</span></p>\n"
"<table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" width=\"100%\" cellspacing=\"4\" cellpadding=\"0\">\n"
"<tr>\n"
"<td>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-weight:600;\">Concepto</span></p></td>\n"
"<td>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-weight:600;\">Monto</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">Ventas realizadas</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">$</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">Ventas cobradas</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">$</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">Facturas</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">$</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">Notas</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">$</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">En efectivo</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">$</span></p></td></tr>\n"
"<tr>\n"
"<td>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">En credito</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">#</span></p></td>\n"
"<td>\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:11pt;\">$</span></p></td></tr></table></body></html>", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tbGColorear.setText(QtCore.QCoreApplication.translate("Form", "Color"))
        self.tbGEtiquetas.setText(QtCore.QCoreApplication.translate("Form", "Etiquetas"))
        self.tbGGuardar.setText(QtCore.QCoreApplication.translate("Form", "Guardar"))
        self.tbGImprimir.setText(QtCore.QCoreApplication.translate("Form", "Imprimir"))
        self.tbREtiquetar.setText(QtCore.QCoreApplication.translate("Form", "Exportar"))
        self.tbRGuardar.setText(QtCore.QCoreApplication.translate("Form", "Guardar"))
        self.tbRImprimir.setText(QtCore.QCoreApplication.translate("Form", "Imprimir"))
# 
import icons_rc
  # TODO: regenerate with pyrcc6