# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/modulos/ui_ventas.ui'
#
# Created: Thu May  9 19:02:26 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(741, 464)
        Form.setStyleSheet("QToolButton, QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));\n"
"border-radius:4px;border:1px solid #777; padding:2 9 2 9;color:#333;\n"
"}\n"
"QPushButton::pressed,QToolButton::pressed{\n"
"color:#fff;\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 66, 255, 255), stop:1 rgba(0, 107, 227, 255));\n"
"\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.top = QtWidgets.QWidget(Form)
        self.top.setMinimumSize(QtCore.QSize(0, 40))
        self.top.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top.setObjectName("top")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout_12.setContentsMargins(10, 5, 2, 5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.titulo = QtWidgets.QLabel(self.top)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.horizontalLayout_12.addWidget(self.titulo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.botonUnion_2 = QtWidgets.QFrame(self.top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonUnion_2.sizePolicy().hasHeightForWidth())
        self.botonUnion_2.setSizePolicy(sizePolicy)
        self.botonUnion_2.setStyleSheet(".QFrame{border-radius:3px;\n"
"border: 1.2px solid #999;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(239, 239, 239, 255), stop:0.5 rgba(226, 226, 226, 255), stop:0.509091 rgba(219, 219, 219, 255), stop:0.986364 rgba(179, 179, 179, 255), stop:1 rgba(207, 228, 255, 255));}\n"
"QToolButton::hover{\n"
"    background-color:rgba(133, 217, 255, 100);\n"
"}\n"
"QToolButton::pressed{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(239, 239, 239, 27), stop:1 rgba(68, 68, 68, 205));\n"
"}\n"
"QToolButton{background:transparent; border-radius:0;border:0px; padding:4px}\n"
" \n"
"")
        self.botonUnion_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.botonUnion_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.botonUnion_2.setObjectName("botonUnion_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.botonUnion_2)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pbVerResumen = QtWidgets.QToolButton(self.botonUnion_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbVerResumen.sizePolicy().hasHeightForWidth())
        self.pbVerResumen.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/abacus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbVerResumen.setIcon(icon)
        self.pbVerResumen.setIconSize(QtCore.QSize(18, 18))
        self.pbVerResumen.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.pbVerResumen.setObjectName("pbVerResumen")
        self.horizontalLayout_6.addWidget(self.pbVerResumen)
        self.tboDetalles = QtWidgets.QToolButton(self.botonUnion_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tboDetalles.sizePolicy().hasHeightForWidth())
        self.tboDetalles.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tboDetalles.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/actions/images/actions/black_18/list.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tboDetalles.setIcon(icon1)
        self.tboDetalles.setIconSize(QtCore.QSize(18, 18))
        self.tboDetalles.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tboDetalles.setObjectName("tboDetalles")
        self.horizontalLayout_6.addWidget(self.tboDetalles)
        self.tbGraficar = QtWidgets.QToolButton(self.botonUnion_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/stats_bars.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tbGraficar.setIcon(icon2)
        self.tbGraficar.setIconSize(QtCore.QSize(18, 18))
        self.tbGraficar.setObjectName("tbGraficar")
        self.horizontalLayout_6.addWidget(self.tbGraficar)
        self.tboImprimir = QtWidgets.QToolButton(self.botonUnion_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tboImprimir.sizePolicy().hasHeightForWidth())
        self.tboImprimir.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tboImprimir.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/print.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tboImprimir.setIcon(icon3)
        self.tboImprimir.setIconSize(QtCore.QSize(18, 18))
        self.tboImprimir.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tboImprimir.setObjectName("tboImprimir")
        self.horizontalLayout_6.addWidget(self.tboImprimir)
        self.horizontalLayout_12.addWidget(self.botonUnion_2)
        self.botonUnion = QtWidgets.QFrame(self.top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonUnion.sizePolicy().hasHeightForWidth())
        self.botonUnion.setSizePolicy(sizePolicy)
        self.botonUnion.setStyleSheet("*{border-radius:8px;    \n"
"}\n"
"\n"
"QToolButton::hover{border-radius:8 0 8 0;\n"
"    background-color:rgba(133, 217, 255, 100);\n"
"}\n"
"QToolButton::pressed{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(239, 239, 239, 27), stop:1 rgba(68, 68, 68, 205));\n"
"}\n"
"QToolButton{ background:transparent; border-radius:0;}\n"
" \n"
"")
        self.botonUnion.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.botonUnion.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.botonUnion.setObjectName("botonUnion")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.botonUnion)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_12.addWidget(self.botonUnion)
        self.verticalLayout_3.addWidget(self.top)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.deHasta = QtWidgets.QDateEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deHasta.sizePolicy().hasHeightForWidth())
        self.deHasta.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deHasta.setFont(font)
        self.deHasta.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.deHasta.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.deHasta.setAccelerated(True)
        self.deHasta.setCalendarPopup(True)
        self.deHasta.setObjectName("deHasta")
        self.gridLayout.addWidget(self.deHasta, 1, 1, 1, 1)
        self.deDesde = QtWidgets.QDateEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deDesde.sizePolicy().hasHeightForWidth())
        self.deDesde.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deDesde.setFont(font)
        self.deDesde.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.deDesde.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.deDesde.setAccelerated(True)
        self.deDesde.setCalendarPopup(True)
        self.deDesde.setObjectName("deDesde")
        self.gridLayout.addWidget(self.deDesde, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 0, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tboActualizar = QtWidgets.QToolButton(self.groupBox_6)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/actions/images/actions/color_18/reload.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tboActualizar.setIcon(icon4)
        self.tboActualizar.setIconSize(QtCore.QSize(24, 24))
        self.tboActualizar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tboActualizar.setObjectName("tboActualizar")
        self.horizontalLayout_4.addWidget(self.tboActualizar)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbDepositar = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbDepositar.setFont(font)
        self.pbDepositar.setObjectName("pbDepositar")
        self.verticalLayout.addWidget(self.pbDepositar)
        self.tboInicial = QtWidgets.QToolButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tboInicial.sizePolicy().hasHeightForWidth())
        self.tboInicial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tboInicial.setFont(font)
        self.tboInicial.setIconSize(QtCore.QSize(16, 24))
        self.tboInicial.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tboInicial.setObjectName("tboInicial")
        self.verticalLayout.addWidget(self.tboInicial)
        self.pbVerEnDetallada = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbVerEnDetallada.sizePolicy().hasHeightForWidth())
        self.pbVerEnDetallada.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pbVerEnDetallada.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../../../Users/usr/share/pyventa/images/32/edit-select-all.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbVerEnDetallada.setIcon(icon5)
        self.pbVerEnDetallada.setObjectName("pbVerEnDetallada")
        self.verticalLayout.addWidget(self.pbVerEnDetallada)
        self.pbDetallarProds = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbDetallarProds.setFont(font)
        self.pbDetallarProds.setObjectName("pbDetallarProds")
        self.verticalLayout.addWidget(self.pbDetallarProds)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tbRetirar = QtWidgets.QToolButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbRetirar.sizePolicy().hasHeightForWidth())
        self.tbRetirar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tbRetirar.setFont(font)
        self.tbRetirar.setIconSize(QtCore.QSize(16, 24))
        self.tbRetirar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbRetirar.setObjectName("tbRetirar")
        self.verticalLayout_4.addWidget(self.tbRetirar)
        self.pbAgregarGasto = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pbAgregarGasto.setFont(font)
        self.pbAgregarGasto.setObjectName("pbAgregarGasto")
        self.verticalLayout_4.addWidget(self.pbAgregarGasto)
        self.pbVerDetallada = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbVerDetallada.sizePolicy().hasHeightForWidth())
        self.pbVerDetallada.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pbVerDetallada.setFont(font)
        self.pbVerDetallada.setObjectName("pbVerDetallada")
        self.verticalLayout_4.addWidget(self.pbVerDetallada)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.stack = QtWidgets.QStackedWidget(Form)
        self.stack.setStyleSheet("#stack{background:transparent}")
        self.stack.setObjectName("stack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.page)
        self.widget_2.setStyleSheet(".QWidget{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0.976077 rgba(71, 71, 71, 255), stop:1 rgba(55, 55, 55, 255));\n"
"\n"
"}\n"
"QTextEdit{border:1.5px solid #ccc;border-top:1px;border-bottom:1px;}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_7.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMaximumSize(QtCore.QSize(700, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 425, 420))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.teResumen = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.teResumen.setMaximumSize(QtCore.QSize(700, 16777215))
        self.teResumen.setReadOnly(True)
        self.teResumen.setObjectName("teResumen")
        self.verticalLayout_6.addWidget(self.teResumen)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_7.addWidget(self.scrollArea)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.stack.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.page_2)
        self.widget.setStyleSheet(".QWidget{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0.976077 rgba(71, 71, 71, 255), stop:1 rgba(55, 55, 55, 255));\n"
"\n"
"}\n"
"QTextEdit{border:1.5px solid #ccc;border-top:1px;border-bottom:1px;}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMaximumSize(QtCore.QSize(700, 16777215))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.teEntradasDetalle = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teEntradasDetalle.sizePolicy().hasHeightForWidth())
        self.teEntradasDetalle.setSizePolicy(sizePolicy)
        self.teEntradasDetalle.setMaximumSize(QtCore.QSize(700, 16777215))
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        font.setPointSize(11)
        self.teEntradasDetalle.setFont(font)
        self.teEntradasDetalle.setReadOnly(True)
        self.teEntradasDetalle.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.teEntradasDetalle.setObjectName("teEntradasDetalle")
        self.verticalLayout_7.addWidget(self.teEntradasDetalle)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.addWidget(self.scrollArea_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_2.addWidget(self.widget)
        self.stack.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lblGrafica = QtWidgets.QLabel(self.page_3)
        self.lblGrafica.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblGrafica.setObjectName("lblGrafica")
        self.verticalLayout_8.addWidget(self.lblGrafica)
        self.stack.addWidget(self.page_3)
        self.horizontalLayout.addWidget(self.stack)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtCore.QCoreApplication.translate("Form", "Form"))
        self.titulo.setText(QtCore.QCoreApplication.translate("Form", "Ventas"))
        self.pbVerResumen.setText(QtCore.QCoreApplication.translate("Form", "Simple"))
        self.tboDetalles.setText(QtCore.QCoreApplication.translate("Form", "Detallado"))
        self.tbGraficar.setToolTip(QtCore.QCoreApplication.translate("Form", "Mostrar grafica"))
        self.tbGraficar.setText(QtCore.QCoreApplication.translate("Form", "Grafica"))
        self.tboImprimir.setText(QtCore.QCoreApplication.translate("Form", "Imprimir"))
        self.groupBox_6.setTitle(QtCore.QCoreApplication.translate("Form", "Periodo"))
        self.deHasta.setDisplayFormat(QtCore.QCoreApplication.translate("Form", "dd MMMM yy"))
        self.deDesde.setDisplayFormat(QtCore.QCoreApplication.translate("Form", "dd MMMM yy"))
        self.label_16.setText(QtCore.QCoreApplication.translate("Form", "Hasta"))
        self.label_15.setText(QtCore.QCoreApplication.translate("Form", "Desde:"))
        self.tboActualizar.setText(QtCore.QCoreApplication.translate("Form", "Aplicar periodo"))
        self.groupBox.setTitle(QtCore.QCoreApplication.translate("Form", "Entradas"))
        self.pbDepositar.setText(QtCore.QCoreApplication.translate("Form", "Registrar deposito"))
        self.tboInicial.setText(QtCore.QCoreApplication.translate("Form", "Registrar efectivo inicial"))
        self.pbVerEnDetallada.setText(QtCore.QCoreApplication.translate("Form", "Detallar entradas"))
        self.pbDetallarProds.setText(QtWidgets.QApplication.translate("Form", "Detallar ventas por\n"
"productos", None, QtWidgets.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtCore.QCoreApplication.translate("Form", "Salidas"))
        self.tbRetirar.setText(QtCore.QCoreApplication.translate("Form", "Registrar retiro"))
        self.pbAgregarGasto.setText(QtCore.QCoreApplication.translate("Form", "Registrar gasto"))
        self.pbVerDetallada.setText(QtCore.QCoreApplication.translate("Form", "Detallar salidas"))
        self.teEntradasDetalle.setHtml(QtWidgets.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtWidgets.QApplication.UnicodeUTF8))
        self.lblGrafica.setText(QtCore.QCoreApplication.translate("Form", "Grafica"))
# 
import icons_rc
  # TODO: regenerate with pyrcc6